@extends('layouts.marketing')
@section('title', $author->name.' | LoLo Care Author')
@section('meta_description', \Illuminate\Support\Str::limit($author->bio, 160, ''))
@section('canonical', route('blog.author',$author))
@section('structured_data')
@php($schema=['@context'=>'https://schema.org','@type'=>'ProfilePage','dateCreated'=>$author->created_at?->toIso8601String(),'dateModified'=>$author->updated_at?->toIso8601String(),'mainEntity'=>array_filter(['@type'=>$author->user_id?'Person':'Organization','name'=>$author->name,'description'=>$author->bio,'url'=>route('blog.author',$author),'sameAs'=>$author->same_as?:[],'image'=>$author->avatar?->variantUrl('medium')])])
<script type="application/ld+json">{!! json_encode($schema, JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) !!}</script>
@endsection
@section('content')
<div class="min-h-screen bg-[#F7F3ED]"><header class="border-b border-[#DED6CA] bg-white"><div class="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><a href="{{ route('landing') }}" class="font-extrabold text-[#17313F]">LoLo Care</a><a href="{{ route('blog.index') }}" class="text-sm font-semibold text-[#0F5B52] underline">All resources</a></div></header><main class="mx-auto max-w-6xl px-4 py-12 sm:px-6"><section class="rounded-3xl border border-[#DED6CA] bg-white p-7 sm:p-10"><div class="flex flex-col gap-6 sm:flex-row">@if($author->avatar)<img src="{{ $author->avatar->variantUrl('medium') }}" alt="{{ $author->name }}" class="h-32 w-32 rounded-3xl object-cover">@endif<div><p class="hc-brand-kicker">Author and reviewer profile</p><h1 class="mt-2 font-display text-5xl font-semibold">{{ $author->name }}</h1><p class="mt-3 font-semibold text-[#0F5B52]">{{ $author->headline }}</p><p class="mt-4 max-w-3xl text-lg leading-8 text-[#526474]">{{ $author->bio }}</p>@if($author->credentials)<p class="mt-4 rounded-xl bg-[#EFF8F5] p-4 text-sm"><strong>Credentials and review scope:</strong> {{ $author->credentials }}</p>@endif</div></div></section><section class="mt-12"><h2 class="font-display text-3xl font-semibold">Reviewed contributions</h2><div class="mt-6 grid gap-5 md:grid-cols-2">@forelse($presentedPosts as $item)<article class="rounded-2xl border border-[#DED6CA] bg-white p-5"><h3 class="font-display text-2xl font-semibold"><a href="{{ $item['url'] }}">{{ $item['title'] }}</a></h3><p class="mt-2 text-sm text-[#526474]">{{ $item['excerpt'] }}</p><p class="mt-4 text-xs text-[#6A7784]">{{ $item['published_at']?->format('M j, Y') }} · {{ $item['read_minutes'] }} min</p></article>@empty<p>No public contributions yet.</p>@endforelse</div><div class="mt-8">{{ $posts->links() }}</div></section></main></div>
@endsection
