<?php

return [
    /*
    | This deployment guard is deliberately separate from database controls.
    | A missing environment value must never make customer AI available.
    */
    'runtime_available' => (bool) env('AI_SUPPORT_RUNTIME_AVAILABLE', false),
    'retention_execution_enabled' => (bool) env('AI_SUPPORT_RETENTION_EXECUTION_ENABLED', false),
    'shadow_mutations_allowed' => false,

    /*
    | This switch controls a local, synthetic-only evaluation adapter. It is
    | intentionally independent from the customer runtime and defaults off.
    */
    'offline_evaluation_enabled' => filter_var(
        env('AI_SUPPORT_OFFLINE_EVALUATION_ENABLED', false),
        FILTER_VALIDATE_BOOL,
    ),

    /*
    | Customer-runtime provider access is an additional deployment guard. It is
    | intentionally independent from eligibility and every database control.
    */
    'provider_enabled' => filter_var(env('AI_SUPPORT_PROVIDER_ENABLED', false), FILTER_VALIDATE_BOOL),
    'model' => env('AI_SUPPORT_MODEL', 'gpt-5.6-luna'),
    'reasoning_effort' => env('AI_SUPPORT_REASONING_EFFORT', 'low'),
    'max_output_tokens' => (int) env('AI_SUPPORT_MAX_OUTPUT_TOKENS', 900),
    'safety_identifier_secret' => env('AI_SUPPORT_SAFETY_IDENTIFIER_SECRET'),
    'model_configuration_version' => 'luna-low-v2',
    'prompt_schema_version' => 'interactive-support-v9',
    'provider_retry_attempts' => 2,
    'provider_price_version' => 'openai-gpt-5.6-luna-2026-08-14',
    'provider_price_source' => 'https://developers.openai.com/api/docs/models/gpt-5.6-luna',
    'provider_price_effective_on' => '2026-08-14',
    'provider_input_usd_per_million' => 0.20,
    'provider_cached_input_usd_per_million' => 0.02,
    'provider_output_usd_per_million' => 1.20,
    'conversation_cost_alert_microunits' => 30_000,
    'conversation_cost_stop_microunits' => 50_000,
    'rehearsal_daily_cost_stop_microunits' => 2_000_000,
    'pilot_daily_cost_stop_microunits' => 5_000_000,
    'pilot_daily_model_turn_limit' => 50,
    'provider_monthly_budget_alert_usd' => 25,
    'provider_monthly_budget_alert_required' => false,
    'conversation_p95_target_ms' => 5_000,
    'tool_p95_target_ms' => 8_000,
    'performance_minimum_sample' => 20,
    'draft_retention_days' => 7,
    'confirmation_validity_minutes' => 30,
    'guided_task_validity_minutes' => 60,
    'goal_journey_retention_days' => 7,

    'policy_version' => 'ai-support-availability-v2',
    'context_contract_version' => 'support-context-v1',
    'event_contract_version' => 'support-event-v1',
    'navigation_contract_version' => 'support-navigation-v2',
    'confirmation_contract_version' => 'support-confirmation-v1',

    'default_grant_days' => 14,
    'pilot' => [
        'maximum_active_users' => 2,
    ],
    'general_release_controls' => [
        'master_enabled',
        'user_visible_enabled',
        'role.family',
        'role.caregiver',
        'capability.support_answers_v1',
        'capability.semantic_navigation_v1',
        'capability.family_context_v1',
        'capability.care_intake_v1',
        'capability.care_request_draft_v1',
        'capability.care_request_recap_v1',
        'capability.care_request_publish_v1',
        'capability.care_24h_handoff_v1',
        'capability.family_lifecycle_action_v1',
        'capability.family_care_operations_v1',
        'capability.family_administration_v1',
        'commit.one_time',
        'commit.recurring',
        'tool.care-request.publish.one-time',
        'tool.care-request.publish.recurring',
        'tool.family-profile.save-draft',
        'tool.family-profile.make-ready',
        'tool.family-profile.make-default',
        'tool.family-profile.archive',
        'tool.family-profile.restore',
        'tool.care-request.withdraw',
        'tool.caregiver.invite',
        'tool.caregiver.invitation.cancel',
        'tool.applicant.shortlist',
        'tool.applicant.reject',
        'tool.applicant.conversation',
        'tool.caregiver.message',
        'tool.caregiver.hire',
        'tool.visit.change-request',
        'tool.visit.change-request.resolve',
        'tool.visit.cancel',
        'tool.visit.no-show',
        'tool.visit.complete',
        'tool.visit.hours.approve',
        'tool.visit.time-correction.approve',
        'tool.visit.time-correction.request-changes',
        'tool.visit.review',
        'tool.visit.rebook',
        'tool.regular-care.accept-counter',
        'tool.regular-care.offer',
        'tool.regular-care.schedule-change',
        'tool.regular-care.extra-visit',
        'tool.regular-care.skip-visit',
        'tool.regular-care.pause',
        'tool.regular-care.resume',
        'tool.regular-care.end',
        'tool.regular-care.extra-visit.approve',
        'tool.regular-care.extra-visit.request-changes',
        'tool.account.name.update',
        'tool.account.verification.resend',
        'tool.family-access.invite',
        'tool.family-access.invitation.resend',
        'tool.family-access.invitation.cancel',
        'tool.family-access.member.remove',
        'tool.family-access.leave',
        'tool.notification.mark-read',
        'tool.notification.mark-all-read',
        'tool.notification.preferences.update',
    ],
    'initial_pilot' => [
        // Historical DEC-070 data remains readable but no longer gates operation.
        'enforced' => false,
        'policy_version' => 'dec-070-initial-family-v1',
        'approved_user_ids' => [282, 19],
        'approved_bundle_key' => 'family_support_v1',
        'maximum_non_revoked_grants' => 2,
        'starts_on' => '2026-08-15',
        'expires_on' => '2026-08-29',
        'allowed_control_openings' => [
            'master_enabled',
            'user_visible_enabled',
            'role.family',
            'capability.support_answers_v1',
            'capability.semantic_navigation_v1',
            'capability.family_context_v1',
            'capability.care_intake_v1',
            'capability.care_request_draft_v1',
            'capability.care_request_recap_v1',
            'capability.care_request_publish_v1',
            'capability.care_24h_handoff_v1',
            'capability.family_lifecycle_action_v1',
            'commit.one_time',
            'tool.care-request.publish.one-time',
        ],
        'deferred_evidence_keys' => [
            'provider_data_controls',
            'provider_destination_contract',
            'downstream_extinction_restore',
            'rollback_rehearsal',
            'older_adult_usability',
            'accessibility',
        ],
    ],
    'grant_history_months' => 24,
    'control_history_months' => 24,
    'kb_full_history_months' => 36,
    'kb_tombstone_months' => 24,
    'support_transcript_months' => 12,
    'interaction_event_months' => 24,
    'confirmed_action_months' => 24,
    'deletion_evidence_months' => 36,
    'readiness_evidence_months' => 24,
    'incident_evidence_months' => 24,
    'preview_content_max_hours' => 24,
    'retention_policy_version' => 'ai-support-retention-v1',
    'reason_max_length' => 500,

    'supported_roles' => ['family', 'caregiver'],

    'bundles' => [
        'family_support_v1' => [
            'label' => 'Family support pilot v1',
            'roles' => ['family'],
            'capabilities' => [
                'support_answers_v1',
                'semantic_navigation_v1',
                'family_context_v1',
                'care_intake_v1',
                'care_request_draft_v1',
                'care_request_recap_v1',
                'care_request_publish_v1',
                'care_24h_handoff_v1',
                'family_lifecycle_action_v1',
                'family_care_operations_v1',
                'family_administration_v1',
            ],
        ],
        'caregiver_support_v1' => [
            'label' => 'Caregiver support pilot v1',
            'roles' => ['caregiver'],
            'capabilities' => ['support_answers_v1', 'semantic_navigation_v1'],
        ],
    ],

    'controls' => [
        'master_enabled' => false,
        'user_visible_enabled' => false,
        'general_release_enabled' => false,
        'shadow_enabled' => false,
        'human_only' => true,
        'role.family' => false,
        'role.caregiver' => false,
        'capability.support_answers_v1' => false,
        'capability.semantic_navigation_v1' => false,
        'capability.family_context_v1' => false,
        'capability.care_intake_v1' => false,
        'capability.care_request_draft_v1' => false,
        'capability.care_request_recap_v1' => false,
        'capability.care_request_publish_v1' => false,
        'capability.care_24h_handoff_v1' => false,
        'capability.family_lifecycle_action_v1' => false,
        'capability.family_care_operations_v1' => false,
        'capability.family_administration_v1' => false,
        'commit.one_time' => false,
        'commit.recurring' => false,
        'tool.care-request.publish.one-time' => false,
        'tool.care-request.publish.recurring' => false,
        'tool.family-profile.save-draft' => false,
        'tool.family-profile.make-ready' => false,
        'tool.family-profile.make-default' => false,
        'tool.family-profile.archive' => false,
        'tool.family-profile.restore' => false,
        'tool.care-request.withdraw' => false,
        'tool.caregiver.invite' => false,
        'tool.caregiver.invitation.cancel' => false,
        'tool.applicant.shortlist' => false,
        'tool.applicant.reject' => false,
        'tool.applicant.conversation' => false,
        'tool.caregiver.message' => false,
        'tool.caregiver.hire' => false,
        'tool.visit.change-request' => false,
        'tool.visit.change-request.resolve' => false,
        'tool.visit.cancel' => false,
        'tool.visit.no-show' => false,
        'tool.visit.complete' => false,
        'tool.visit.hours.approve' => false,
        'tool.visit.time-correction.approve' => false,
        'tool.visit.time-correction.request-changes' => false,
        'tool.visit.review' => false,
        'tool.visit.rebook' => false,
        'tool.regular-care.accept-counter' => false,
        'tool.regular-care.offer' => false,
        'tool.regular-care.schedule-change' => false,
        'tool.regular-care.extra-visit' => false,
        'tool.regular-care.skip-visit' => false,
        'tool.regular-care.pause' => false,
        'tool.regular-care.resume' => false,
        'tool.regular-care.end' => false,
        'tool.regular-care.extra-visit.approve' => false,
        'tool.regular-care.extra-visit.request-changes' => false,
        'tool.account.name.update' => false,
        'tool.account.verification.resend' => false,
        'tool.family-access.invite' => false,
        'tool.family-access.invitation.resend' => false,
        'tool.family-access.invitation.cancel' => false,
        'tool.family-access.member.remove' => false,
        'tool.family-access.leave' => false,
        'tool.notification.mark-read' => false,
        'tool.notification.mark-all-read' => false,
        'tool.notification.preferences.update' => false,
    ],

    /*
    | Material-action tools are registered here but remain disabled by default.
    | Each release still requires its exact capability/version entry plus both
    | the capability and tool controls to be explicitly enabled.
    */
    'tools' => [
        'care-request.publish.one-time' => [
            'capability_id' => 'care_request_publish_v1',
            'versions' => ['v1'],
            'preview_validity_minutes' => 30,
        ],
        'care-request.publish.recurring' => [
            'capability_id' => 'care_request_publish_v1',
            'versions' => ['v1'],
            'preview_validity_minutes' => 30,
        ],
        'family-profile.save-draft' => [
            'capability_id' => 'family_lifecycle_action_v1',
            'versions' => ['v1'],
            'preview_validity_minutes' => 30,
        ],
        'family-profile.make-ready' => [
            'capability_id' => 'family_lifecycle_action_v1',
            'versions' => ['v1'],
            'preview_validity_minutes' => 30,
        ],
        'family-profile.make-default' => [
            'capability_id' => 'family_lifecycle_action_v1',
            'versions' => ['v1'],
            'preview_validity_minutes' => 30,
        ],
        'family-profile.archive' => [
            'capability_id' => 'family_lifecycle_action_v1',
            'versions' => ['v1'],
            'preview_validity_minutes' => 30,
        ],
        'family-profile.restore' => [
            'capability_id' => 'family_lifecycle_action_v1',
            'versions' => ['v1'],
            'preview_validity_minutes' => 30,
        ],
        'care-request.withdraw' => [
            'capability_id' => 'family_lifecycle_action_v1',
            'versions' => ['v1'],
            'preview_validity_minutes' => 30,
        ],
        ...collect([
            'caregiver.invite', 'caregiver.invitation.cancel', 'applicant.shortlist',
            'applicant.reject', 'applicant.conversation', 'caregiver.message', 'caregiver.hire',
            'visit.change-request', 'visit.change-request.resolve', 'visit.cancel', 'visit.no-show', 'visit.complete',
            'visit.hours.approve', 'visit.time-correction.approve',
            'visit.time-correction.request-changes', 'visit.review', 'visit.rebook',
            'regular-care.accept-counter', 'regular-care.offer', 'regular-care.schedule-change', 'regular-care.extra-visit',
            'regular-care.skip-visit', 'regular-care.pause', 'regular-care.resume', 'regular-care.end',
            'regular-care.extra-visit.approve', 'regular-care.extra-visit.request-changes',
        ])->mapWithKeys(fn (string $tool): array => [$tool => [
            'capability_id' => 'family_care_operations_v1',
            'versions' => ['v1'],
            'preview_validity_minutes' => 30,
        ]])->all(),
        ...collect([
            'account.name.update', 'account.verification.resend',
            'family-access.invite', 'family-access.invitation.resend', 'family-access.invitation.cancel',
            'family-access.member.remove', 'family-access.leave',
            'notification.mark-read', 'notification.mark-all-read', 'notification.preferences.update',
        ])->mapWithKeys(fn (string $tool): array => [$tool => [
            'capability_id' => 'family_administration_v1',
            'versions' => ['v1'],
            'preview_validity_minutes' => 30,
        ]])->all(),
    ],

    'navigation_targets' => [
        'support.center' => ['route' => 'support.index', 'roles' => ['family', 'caregiver']],
        'family.dashboard' => ['route' => 'dashboard', 'roles' => ['family']],
        'family.care_requests' => [
            'route' => 'family.requests.index',
            'roles' => ['family'],
            'client_target_id' => 'family.care_requests',
            'label' => 'Care',
            'instruction' => 'Use the highlighted Care area to review requests and visits.',
        ],
        'family.new_care_request' => ['route' => 'family.requests.create', 'roles' => ['family']],
        'family.request.overview' => [
            'route' => 'family.requests.show',
            'roles' => ['family'],
            'resource_type' => 'care_request',
            'route_parameter' => 'careRequest',
            'query' => ['tab' => 'overview'],
            'client_target_id' => 'family.request.overview',
            'label' => 'Care request',
            'instruction' => 'Review the highlighted request status and next step.',
        ],
        'family.request.applicants' => [
            'route' => 'family.requests.show',
            'roles' => ['family'],
            'resource_type' => 'care_request',
            'route_parameter' => 'careRequest',
            'query' => ['tab' => 'applicants'],
            'client_target_id' => 'family.request.applicants',
            'label' => 'Caregiver responses',
            'instruction' => 'Review the highlighted caregiver responses.',
        ],
        'family.request.visit' => [
            'route' => 'family.requests.show',
            'roles' => ['family'],
            'resource_type' => 'care_request',
            'route_parameter' => 'careRequest',
            'query' => ['tab' => 'shift'],
            'client_target_id' => 'family.request.visit',
            'label' => 'Visit details',
            'instruction' => 'Review the highlighted visit status and details.',
        ],
        'family.request.visit_issue' => [
            'route' => 'family.requests.show',
            'roles' => ['family'],
            'resource_type' => 'care_request',
            'route_parameter' => 'careRequest',
            'query' => ['tab' => 'shift'],
            'client_target_id' => 'family.request.visit_issue',
            'label' => 'Visit change request',
            'instruction' => 'Review the highlighted visit change, then accept or reject it.',
        ],
        'family.request.timesheet' => [
            'route' => 'family.requests.show',
            'roles' => ['family'],
            'resource_type' => 'care_request',
            'route_parameter' => 'careRequest',
            'query' => ['tab' => 'shift'],
            'client_target_id' => 'family.request.timesheet',
            'label' => 'Submitted hours',
            'instruction' => 'Review the highlighted submitted hours before taking action.',
        ],
        'family.request.payment_attention' => [
            'route' => 'family.requests.show',
            'roles' => ['family'],
            'resource_type' => 'care_request',
            'route_parameter' => 'careRequest',
            'query' => ['tab' => 'shift'],
            'client_target_id' => 'family.request.payment_attention',
            'label' => 'Care payment',
            'instruction' => 'Use the highlighted payment action for this care visit.',
        ],
        'family.regular_care.attention' => [
            'route' => 'family.care.show',
            'roles' => ['family'],
            'resource_type' => 'care_plan',
            'route_parameter' => 'carePlan',
            'client_target_id' => 'family.regular_care.attention',
            'label' => 'Regular care',
            'instruction' => 'Review the highlighted regular-care item that needs attention.',
        ],
        'family.regular_care' => [
            'route' => 'family.care.index',
            'roles' => ['family'],
            'client_target_id' => 'family.regular_care',
            'label' => 'Regular care',
            'instruction' => 'Use the highlighted Regular care area to review plans and upcoming visits.',
        ],
        'family.care_profiles' => [
            'route' => 'family.care-profiles.index',
            'roles' => ['family'],
            'client_target_id' => 'family.care_profiles',
            'label' => 'Care receiver profiles',
            'instruction' => 'Use the highlighted care receiver profile area.',
        ],
        'family.care_profile.create' => [
            'route' => 'family.care-profiles.create',
            'roles' => ['family'],
            'client_target_id' => 'family.care_profile.editor',
            'label' => 'New care receiver profile',
            'instruction' => 'Start with the highlighted first step and save when you are ready.',
        ],
        'family.care_profile.edit' => [
            'route' => 'family.care-profiles.edit',
            'roles' => ['family'],
            'resource_type' => 'care_profile',
            'route_parameter' => 'careRecipientProfile',
            'client_target_id' => 'family.care_profile.editor',
            'label' => 'Care receiver profile',
            'instruction' => 'Continue the highlighted care receiver profile.',
        ],
        'family.care_profile.identity' => [
            'route' => 'family.care-profiles.edit',
            'roles' => ['family'],
            'resource_type' => 'care_profile',
            'route_parameter' => 'careRecipientProfile',
            'query' => ['step' => 1],
            'client_target_id' => 'family.care_profile.editor',
            'label' => 'Care receiver name',
            'instruction' => 'Add the highlighted profile name, then continue.',
        ],
        'family.care_profile.contact' => [
            'route' => 'family.care-profiles.edit',
            'roles' => ['family'],
            'resource_type' => 'care_profile',
            'route_parameter' => 'careRecipientProfile',
            'query' => ['step' => 4],
            'client_target_id' => 'family.care_profile.editor',
            'label' => 'Additional contact',
            'instruction' => 'Complete the highlighted additional-contact step, then continue.',
        ],
        'family.care_profile.review' => [
            'route' => 'family.care-profiles.edit',
            'roles' => ['family'],
            'resource_type' => 'care_profile',
            'route_parameter' => 'careRecipientProfile',
            'query' => ['step' => 5],
            'client_target_id' => 'family.care_profile.editor',
            'label' => 'Care profile review',
            'instruction' => 'Review the highlighted sharing preview and save when it is correct.',
        ],
        'family.messages' => [
            'route' => 'messages.index',
            'roles' => ['family'],
            'client_target_id' => 'family.messages.inbox',
            'label' => 'Messages',
            'instruction' => 'Review the highlighted message inbox.',
        ],
        'family.notifications' => [
            'route' => 'family.notifications.index',
            'roles' => ['family'],
            'client_target_id' => 'family.notifications',
            'label' => 'Notifications',
            'instruction' => 'Review the highlighted notification and preference controls.',
        ],
        'family.message' => [
            'route' => 'messages.show',
            'roles' => ['family'],
            'resource_type' => 'conversation',
            'route_parameter' => 'conversation',
            'client_target_id' => 'family.messages.conversation',
            'label' => 'Conversation',
            'instruction' => 'Review the highlighted conversation and reply if needed.',
        ],
        'family.care_history' => [
            'route' => 'family.care.history',
            'roles' => ['family'],
            'client_target_id' => 'family.care_history',
            'label' => 'Care history',
            'instruction' => 'Use the highlighted care history to review visits, hours, and charges.',
        ],
        'family.access' => ['route' => 'family.access', 'roles' => ['family']],
        'family.billing.payment_method' => [
            'route' => 'family.billing.show',
            'roles' => ['family'],
            'client_target_id' => 'family.billing.manage_payment_method',
            'label' => 'Payment method',
            'instruction' => 'Use the highlighted payment-method button.',
            'fallback_target' => 'family.dashboard',
        ],
        'caregiver.dashboard' => ['route' => 'dashboard', 'roles' => ['caregiver']],
        'caregiver.work_inbox' => ['route' => 'caregiver.work-inbox.index', 'roles' => ['caregiver']],
        'caregiver.shifts' => ['route' => 'caregiver.shifts.index', 'roles' => ['caregiver']],
        'account.profile' => ['route' => 'profile', 'roles' => ['family', 'caregiver']],
    ],
];
