<div class="space-y-6">
    <section class="hc-surface p-5 sm:p-6"><h2 class="hc-care-title">Care details for this recurring care</h2><p class="mt-2 hc-care-subtitle">These are the details saved for this care. Each booked visit keeps the care profile and agreement assigned to that visit.</p><dl class="mt-5 grid gap-6 sm:grid-cols-2"><div><dt class="font-semibold">Care location</dt><dd class="mt-2">{{ data_get($address, 'address_line1') }}@if(data_get($address, 'address_line2'))<br>{{ data_get($address, 'address_line2') }}@endif<br>{{ data_get($address, 'city') }}, {{ data_get($address, 'state') }} {{ data_get($address, 'zip') }}</dd></div><div><dt class="font-semibold">Care notes</dt><dd class="mt-2 whitespace-pre-line">{{ $plan->care_notes ?: 'No extra notes.' }}</dd></div></dl><div class="mt-6"><h3 class="font-semibold">Tasks and instructions</h3><ul class="mt-3 grid gap-3 sm:grid-cols-2">@forelse($tasks as $task)<li class="rounded-xl border border-[#A4B3A7] bg-[#FFF7EA] p-4"><p class="font-semibold">{{ $task['name'] ?? 'Care task' }}</p>@if(filled($task['task_note'] ?? $task['note'] ?? null))<p class="mt-2 whitespace-pre-line">{{ $task['task_note'] ?? $task['note'] }}</p>@endif</li>@empty<li>No task list added.</li>@endforelse</ul></div></section>
    @if ($careProfileSnapshot)
        <x-care-recipient-profile-summary :snapshot="$careProfileSnapshot" />
    @else
        <section class="hc-surface p-5 sm:p-6"><h2 class="hc-care-title">About {{ $plan->recipientName() }}</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2">@foreach(['full_name' => 'Full name', 'date_of_birth' => 'Date of birth', 'gender' => 'Gender', 'mobility_level' => 'Mobility', 'relationship_to_family' => 'Relationship to family', 'care_notes' => 'Care notes'] as $field => $label)@if(filled(data_get($plan->recipient_snapshot, $field)))<div><dt class="font-semibold">{{ $label }}</dt><dd class="mt-1 whitespace-pre-line">{{ data_get($plan->recipient_snapshot, $field) }}</dd></div>@endif@endforeach</dl></section>
    @endif
    @if ($source && collect([$source->scope_of_work, $source->time_expectations, $source->home_access_notes, $source->additional_info])->filter()->isNotEmpty())
        <section class="hc-surface p-5 sm:p-6"><h2 class="hc-care-title">Instructions from your original request</h2><dl class="mt-4 space-y-4">@foreach(['scope_of_work' => 'Scope of care', 'time_expectations' => 'Time expectations', 'home_access_notes' => 'Home access', 'additional_info' => 'Additional information'] as $field => $label)@if(filled($source->{$field}))<div><dt class="font-semibold">{{ $label }}</dt><dd class="mt-2 whitespace-pre-line">{{ $source->{$field} }}</dd></div>@endif@endforeach</dl></section>
    @endif
    @if ($source?->thirdPartyContact)
        <section class="hc-surface p-5 sm:p-6"><h2 class="hc-care-title">Additional care contact</h2><p class="mt-3 font-semibold">{{ $source->thirdPartyContact->full_name }}</p><p class="mt-1">{{ $source->thirdPartyContact->relationship_to_recipient }}</p>@if($source->thirdPartyContact->phone)<p class="mt-2"><a href="tel:{{ $source->thirdPartyContact->phone }}" class="hc-care-text-link">{{ $source->thirdPartyContact->phone }}</a></p>@endif @if($source->thirdPartyContact->email)<p class="mt-2"><a href="mailto:{{ $source->thirdPartyContact->email }}" class="hc-care-text-link">{{ $source->thirdPartyContact->email }}</a></p>@endif</section>
    @endif
    <section class="hc-surface p-5 sm:p-6"><h2 class="hc-care-title">Care record</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2"><div><dt class="text-sm">Care reference</dt><dd class="mt-1 font-semibold">Care #{{ $plan->id }}</dd></div><div><dt class="text-sm">Schedule version</dt><dd class="mt-1">{{ $plan->schedule_version }}</dd></div>@if($plan->offered_at)<div><dt class="text-sm">Offered</dt><dd class="mt-1">{{ $plan->offered_at->format('M j, Y · g:i A') }}</dd></div>@endif @if($plan->accepted_at)<div><dt class="text-sm">Accepted</dt><dd class="mt-1">{{ $plan->accepted_at->format('M j, Y · g:i A') }}</dd></div>@endif @if($plan->ended_at)<div><dt class="text-sm">Ended</dt><dd class="mt-1">{{ $plan->ended_at->format('M j, Y · g:i A') }}</dd></div>@endif</dl></section>
</div>
