<div class="space-y-6">
    <section class="hc-surface p-5 sm:p-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p class="hc-care-eyebrow">{{ $isPending ? 'Proposed recurring schedule' : 'Recurring schedule' }}</p><h2 class="hc-care-title mt-1">{{ $scheduleLabel }}</h2><p class="mt-2 text-sm">{{ $plan->starts_on?->format('M j, Y') }}{{ $plan->ends_on ? ' through '.$plan->ends_on->format('M j, Y') : ' · No set end date' }} · {{ $timezone }}</p></div><span class="hc-care-status">{{ $planStateLabel }}</span></div><p class="mt-4 hc-care-subtitle">Only booked dates appear in the list. Open a visit to manage that date’s hours, payment, care notes or support.</p></section>

    @include('livewire.family.partials.regular-care-management')

    @if ($plan->scheduleChanges->isNotEmpty())
        <section class="hc-surface p-5 sm:p-6"><h2 class="hc-care-title">Schedule & extra-visit requests</h2><div class="mt-4 divide-y divide-[#E3D6C5]">@foreach($plan->scheduleChanges as $change)<article class="py-4 first:pt-0"><div class="flex flex-wrap items-center justify-between gap-2"><h3 class="font-semibold">{{ $change->type === 'extra_visit' ? 'Extra visit' : 'Future schedule' }} · {{ $change->effective_on?->format('M j, Y') }}</h3><span class="rounded-full border border-[#A4B3A7] px-3 py-1 text-sm">{{ $change->status === 'pending' ? 'Waiting for caregiver' : ucfirst($change->status) }}</span></div>@if($change->type === 'extra_visit')<p class="mt-2">{{ \Illuminate\Support\Carbon::parse(data_get($change->proposed_schedule, 'start_at'))->setTimezone($timezone)->format('M j · g:i A') }}–{{ \Illuminate\Support\Carbon::parse(data_get($change->proposed_schedule, 'end_at'))->setTimezone($timezone)->format('g:i A') }}</p>@else<p class="mt-2">{{ \App\Support\WeeklySchedule::label(\App\Support\WeeklySchedule::normalize(data_get($change->proposed_schedule, 'slots', []), data_get($change->proposed_schedule, 'days', []), data_get($change->proposed_schedule, 'start_time'), data_get($change->proposed_schedule, 'end_time'))) }}</p>@endif @if($change->note)<p class="mt-2 whitespace-pre-line text-sm">{{ $change->note }}</p>@endif @if($change->status === 'pending')<p class="mt-2 text-sm">Existing bookings stay unchanged until this request is accepted.</p>@endif</article>@endforeach</div></section>
    @endif

    <section class="hc-surface overflow-hidden" aria-labelledby="booked-visits-heading"><div class="space-y-4 border-b border-[#E3D6C5] p-5 sm:p-6"><h2 id="booked-visits-heading" class="hc-care-title">Your booked visits</h2><div class="flex flex-wrap gap-2" aria-label="Filter visits">@foreach(['upcoming' => 'Upcoming', 'attention' => 'Needs follow-up', 'past' => 'Past', 'cancelled' => 'Cancelled', 'all' => 'All visits'] as $filter => $label)<button type="button" wire:click="setVisitFilter('{{ $filter }}')" aria-pressed="{{ $visitFilter === $filter ? 'true' : 'false' }}" class="{{ $visitFilter === $filter ? 'hc-primary-button' : 'hc-secondary-button' }}">{{ $label }}</button>@endforeach</div><p class="text-sm">{{ $visits->total() }} {{ Str::plural('visit', $visits->total()) }}{{ $visitFilter === 'attention' ? ' to follow up' : ' in this view' }}</p></div><div class="divide-y divide-[#E3D6C5]">@forelse($visits as $visit)@include('livewire.family.partials.regular-care-visit-card', ['visit' => $visit, 'prominent' => false])@empty<p class="p-5 hc-care-subtitle sm:p-6">{{ $visitFilter === 'attention' ? 'No booked visits need follow-up in this view.' : ($isPending ? 'Visits will appear after your caregiver accepts and bookings are created.' : 'No booked visits in this view.') }}</p>@endforelse</div>@if($visits->hasPages())<div class="border-t border-[#E3D6C5] p-5">{{ $visits->links() }}</div>@endif</section>

    @include('livewire.family.partials.completed-extra-visits')
</div>
