<?php

$reviewBy = '2026-11-18';

$sourceCatalog = [
    'SRC-FAMILY-WORKFLOW-001' => ['Family care receiver workflow', 'Request, hire, visit, payment, and rebooking lifecycle'],
    'SRC-FAMILY-ACCESS-001' => ['Family account access specification', 'Family roles, shared access, action attribution, billing, and communication behavior'],
    'SRC-RECIPIENT-001' => ['Care recipient profile specification', 'Care-profile creation, visibility, versioning, privacy, and care attachment behavior'],
    'SRC-REGULAR-CARE-001' => ['Regular care product specification', 'Regular-care offers, schedules, visits, changes, payment, and lifecycle behavior'],
    'SRC-CODE-AI-GUIDE-001' => ['Current app-aware guided assistance implementation', 'Authorized Family state reads, semantic destinations, exact guidance, and completion boundaries'],
    'SRC-CODE-DASHBOARD-001' => ['Current role-aware dashboard implementation', 'Current Family dashboard, action state, notifications, and registered destinations'],
    'SRC-CODE-CARE-REQUESTS-001' => ['Current Family Care implementation', 'Current request, applicant, visit, submitted-hours, care-payment, and history behavior'],
    'SRC-CODE-FAMILY-ACCESS-001' => ['Current Family access implementation', 'Current owner/member controls, invitations, shared records, and account-scoped authorization'],
    'SRC-CODE-ACCOUNT-SETTINGS-001' => ['Current Account Settings implementation', 'Current personal profile, password, contact, and notification-settings behavior'],
    'SRC-LOLO-SAFETY-001' => ['LoLo Acceptable Use and Safety Policy', 'Non-medical, emergency, safety, and prohibited-content boundaries'],
];

$entry = static function (
    string $stableId,
    string $title,
    string $answer,
    string $productArea,
    string $target,
    array $intentIds,
    array $factsMayState,
    array $specificBoundaries,
    array $matches,
    array $noMatches,
    array $sourceIds,
    array $specificEscalations = [],
) use ($reviewBy, $sourceCatalog): array {
    $evaluationPrefix = str_replace('KB-', 'EVAL-KB-', $stableId);
    $factSummary = implode(' ', $factsMayState);

    return [
        'stable_id' => $stableId,
        'intent_ids' => array_values($intentIds),
        'type' => 'task_playbook',
        'title' => $title,
        'answer_body' => $answer,
        'sensitivity' => 'authenticated',
        'product_area' => $productArea,
        'locale' => 'en-US',
        'roles' => ['family'],
        'membership_states' => ['active'],
        'route_target_ids' => [$target],
        'capability_ids' => ['support_answers_v1'],
        'facts_may_state' => array_values($factsMayState),
        'facts_must_not_infer' => array_values(array_unique([
            ...$specificBoundaries,
            'A current account, request, caregiver, visit, profile, message, payment, or completion state without a fresh authorized application read.',
            'That an action succeeded merely because a page or control was opened.',
            'Caregiver availability, a response time, a support wait time, or a queue position.',
        ])),
        'next_actions' => ['navigate:'.$target, 'handoff:SUP-HANDOFF-001'],
        'escalation_conditions' => array_values(array_unique([
            ...$specificEscalations,
            'The user asks for a person.',
            'Authorization or the current account state cannot be resolved safely.',
            'The application does not expose a valid next step for the current state.',
        ])),
        'retrieval_examples_match' => array_values($matches),
        'retrieval_examples_no_match' => array_values($noMatches),
        'evaluation_ids' => [
            $evaluationPrefix.'-POSITIVE',
            $evaluationPrefix.'-BOUNDARY',
            $evaluationPrefix.'-WRONG-ROLE',
            $evaluationPrefix.'-UNSUPPORTED-STATE',
            $evaluationPrefix.'-HANDOFF',
        ],
        'change_note' => 'Family Operations KB Wave 1 approved source definition.',
        'review_by' => $reviewBy,
        'expires_on' => null,
        'sources' => array_values(array_map(
            static function (string $sourceId) use ($sourceCatalog, $factSummary): array {
                [$title, $scope] = $sourceCatalog[$sourceId];

                return [
                    'source_id' => $sourceId,
                    'title' => $title,
                    'url' => null,
                    'section_anchor' => $scope,
                    'fact_supported' => $factSummary,
                ];
            },
            $sourceIds,
        )),
    ];
};

$entries = [
    $entry(
        'KB-FOP-PAY-001',
        'Securely add or change the Family payment method',
        'Use Billing & Payments to add or change the Family payment method. LoLo opens a secure payment flow for card details; card numbers and security codes must never be typed into support chat. After the secure flow returns, the assistant can check whether the new safe card summary is on file before saying the update worked.',
        'Family billing',
        'family.billing.payment_method',
        ['FAM-PAY-001', 'FAM-PAY-003', 'FAM-PAY-004', 'FAM-PAY-005', 'FAM-PAY-006'],
        ['Billing & Payments contains the secure saved-payment-method flow.', 'Chat may use only a safe card summary such as brand, last four digits, and expiration.', 'Success requires a fresh authoritative card-state check.'],
        ['Full card numbers, CVCs, payment tokens, and bank authentication details never belong in chat.'],
        ['I need to add a credit card.', 'Help me use a different card.', 'Where can I update an expired payment method?'],
        ['What is the hourly price?', 'Refund this charge.', 'Did the caregiver get paid?'],
        ['SRC-CODE-AI-GUIDE-001', 'SRC-FAMILY-ACCESS-001'],
    ),
    $entry(
        'KB-FOP-PAY-002',
        'Who may use the shared Family payment method flow',
        'The saved payment method belongs to the Family Account. Any active Family member may use the current secure Billing & Payments flow to add or update it, and only a safe summary is shown in support. Care-related actions are recorded under the signed-in person. LoLo must verify active Family access again before opening billing.',
        'Family billing',
        'family.billing.payment_method',
        ['FAM-PAY-002', 'FAM-PAY-008', 'FAM-ACCESS-014', 'FAM-ACCESS-015'],
        ['The payment method is shared at the Family Account level.', 'The current secure flow is available to active Family Account members.', 'Payment-affecting actions remain attributed to the signed-in person.'],
        ['Active membership or a named person’s access must not be inferred from conversation text.', 'Access to a safe card summary never authorizes disclosure of full payment credentials.'],
        ['Can a Family member update the card?', 'Who can change our shared payment method?', 'Whose name is recorded when I approve a charge?'],
        ['Show another family’s card.', 'Tell me the full card number.', 'Transfer Family Account ownership.'],
        ['SRC-CODE-AI-GUIDE-001', 'SRC-CODE-FAMILY-ACCESS-001'],
    ),
    $entry(
        'KB-FOP-PAY-003',
        'When payment authorization and capture happen',
        'Publishing a care request does not charge or authorize the card. Payment authorization belongs to the later caregiver-hire or booking step. Capture happens later through the completed-care and approved-hours flow. The assistant must read the current care and payment state before explaining what happened in a specific case.',
        'Care payments',
        'family.care_requests',
        ['FAM-PAY-009', 'FAM-PAY-010', 'FAM-REQUEST-033', 'FAM-VISIT-034'],
        ['Request publication alone does not authorize payment.', 'Authorization occurs at the later hire or booking boundary.', 'Capture follows completed care and approved hours.'],
        ['That a request, hire, booking, authorization, capture, or refund exists without current state.', 'A bank posting or release timeline.'],
        ['Did posting my request charge me?', 'When is my card authorized?', 'Does approving hours trigger payment?'],
        ['How much does care cost?', 'Change my payment card.', 'Has a caregiver applied?'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
    ),
    $entry(
        'KB-FOP-PAY-004',
        'Authorization hold versus completed charge',
        'An authorization is a temporary reservation used before final payment. A captured charge is money the platform has completed through its payment flow. Care history may show authorized, captured, refunded, and net-paid amounts when those records exist. LoLo should use the exact application label and current amount rather than guess from a bank statement.',
        'Care payments',
        'family.care_history',
        ['FAM-PAY-011', 'FAM-PAY-020', 'FAM-HISTORY-007'],
        ['Authorization and capture are different payment states.', 'Family-visible history may distinguish authorized, captured, refunded, and net-paid values.', 'A current amount requires an authoritative payment record.'],
        ['That a pending bank transaction is captured.', 'A promise about when a financial institution will release a hold.'],
        ['Is this pending amount a real charge?', 'What is the difference between authorized and captured?', 'Show what was refunded and actually paid.'],
        ['What is the caregiver payout?', 'Add a promo code.', 'Approve these hours now.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
    ),
    $entry(
        'KB-FOP-PAY-005',
        'Pending payment and card authentication',
        'A pending or action-required payment means the payment flow is not complete. Open the highlighted care-payment step and follow any secure bank or card-provider prompt there. Never send an authentication code or card security detail in chat. If LoLo cannot verify the updated state afterward, it must say that it could not verify it and offer Check again or a person.',
        'Care payments',
        'family.care_requests',
        ['FAM-PAY-012', 'FAM-PAY-015', 'FAM-PAY-021', 'FAM-VISIT-026'],
        ['Action-required payment steps remain in the secure application or provider flow.', 'The assistant may guide to the exact care-payment area.', 'Completion requires a fresh payment-state check.'],
        ['The content or result of a bank challenge.', 'That the payment completed because the user clicked a provider button.'],
        ['Why is my payment pending?', 'My bank says more action is required.', 'Continue the payment after my time correction.'],
        ['Tell me my CVC.', 'Publish a care request.', 'Compare two caregivers.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-PAY-006',
        'Failed card authorization and retry',
        'A failed authorization means LoLo could not complete the required card authorization for that care action. The assistant may explain the safe normalized status and open the existing secure retry or payment-method control. It must not expose provider error text, guess the bank’s reason, or claim that a retry worked until the application verifies it.',
        'Care payments',
        'family.care_requests',
        ['FAM-PAY-013', 'FAM-PAY-014'],
        ['A safe normalized failure state may be explained.', 'Retry remains in the existing secure care-payment workflow.', 'Provider error details are not support-chat facts.'],
        ['A specific decline reason not exposed by the application.', 'That replacing a card guarantees authorization.'],
        ['Why did my card authorization fail?', 'Help me retry the failed payment.', 'My card was declined for this care.'],
        ['Refund this care.', 'Why are there no applicants?', 'Change the visit date.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-PAY-007',
        'Payment after approved hours or corrected time',
        'After care, the Family reviews submitted hours or a time correction before the related payment continues. If payment then needs attention, open the exact visit, correction, or extra-visit recovery area. The assistant may explain the current safe state, but it cannot change hours, approve payment, or retry a charge unless that exact action is separately enabled and confirmed.',
        'Care payments',
        'family.care_requests',
        ['FAM-PAY-016', 'FAM-PAY-017', 'FAM-PAY-018', 'FAM-REGULAR-017'],
        ['Submitted hours and corrected-time payment use the related care record.', 'Payment attention can be guided to an exact authorized care record.', 'The normal application remains authoritative for approval and retry.'],
        ['That hours were approved or payment captured without a receipt.', 'Caregiver payout status.'],
        ['Payment failed after I approved care.', 'Retry payment for corrected hours.', 'The extra visit payment needs attention.'],
        ['Change my password.', 'Invite a family member.', 'Create a care profile.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-PAY-008',
        'Payment history and receipts',
        'Open Care history to review completed care and the Family-visible payment information attached to it. A receipt or amount must come from the exact care/payment record. Email receipts follow the Family billing workflow and may go to the billing contact. If the needed document is not available, LoLo should not create one or invent an amount; it can transfer the request to a person.',
        'Care history',
        'family.care_history',
        ['FAM-PAY-019', 'FAM-PAY-020', 'FAM-PAY-026', 'FAM-HISTORY-001', 'FAM-HISTORY-007'],
        ['Care history is the Family destination for past care and Family-visible payment records.', 'Receipt and amount claims require the exact authoritative record.', 'The application may not offer every document type.'],
        ['A receipt, invoice, tax document, amount, or email delivery not proven by the application.', 'Caregiver payout details.'],
        ['Show my payment history.', 'Where is the receipt for my visit?', 'How much was captured and refunded?'],
        ['Create a tax document.', 'Show the caregiver’s bank payout.', 'Change the card on file.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-PAY-009',
        'Refunds, disputes, and unfamiliar charges',
        'Refunds, charge disputes, duplicate-looking charges, and unfamiliar charges need review of the exact care and payment records. LoLo may help open Care history and prepare the care reference and user’s concern, but a person handles exceptional refund or charge decisions. Do not send full card details in chat. Contact the card issuer promptly as well if unauthorized card use is suspected.',
        'Care payments',
        'support.center',
        ['FAM-PAY-022', 'FAM-PAY-023', 'FAM-PAY-024', 'FAM-PAY-025'],
        ['Exceptional refunds and charge disputes require human review.', 'The assistant may prepare an authorized care reference and the user’s stated concern.', 'Full payment credentials remain outside chat.'],
        ['That a charge is duplicate, fraudulent, refundable, or already refunded without evidence.', 'A promised refund outcome or timing.'],
        ['I need a refund.', 'I do not recognize this charge.', 'These two charges look the same.'],
        ['What is the hourly price?', 'Add a new card.', 'Did my message send?'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
        ['The user reports suspected unauthorized card use or asks for an exceptional refund or dispute decision.'],
    ),

    $entry(
        'KB-FOP-REQ-001',
        'Find current care requests and their status',
        'Open Care to see the Family Account’s current requests. The assistant may read the latest authorized request state and open the exact request when one can be selected safely. Status must come from the current request record; a request that is open, booked, completed, withdrawn, or expired has different valid next actions.',
        'Care requests',
        'family.care_requests',
        ['FAM-REQUEST-034', 'FAM-REQUEST-035'],
        ['Care is the Family destination for requests and visits.', 'A specific request status requires an account-scoped current read.', 'Valid next actions depend on the current lifecycle state.'],
        ['Which request the user means when several records are plausible.', 'That a caregiver viewed or applied without current evidence.'],
        ['What is the status of my care request?', 'Show my open requests.', 'Has anyone applied to my request?'],
        ['Create a brand-new request.', 'Show another Family’s request.', 'Change my payment method.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-REQ-002',
        'What request states mean',
        'A care request is the Family’s request for caregivers to consider. Publishing makes it visible to eligible caregivers; it does not mean someone is hired, a visit is scheduled, or payment is authorized. The request page shows the current lifecycle state and the next available step. LoLo must not describe a later state until the application confirms it.',
        'Care requests',
        'family.care_requests',
        ['FAM-REQUEST-031', 'FAM-REQUEST-032', 'FAM-REQUEST-034'],
        ['A published request is not a hire, booking, or payment authorization.', 'The request page is authoritative for its current state.', 'Later lifecycle claims require application evidence.'],
        ['That publication guarantees a caregiver response.', 'That an applicant is hired.'],
        ['What happens after I publish?', 'Does open mean somebody is hired?', 'Why is my request still waiting?'],
        ['How much does care cost?', 'Approve the caregiver’s hours.', 'Update a recipient profile.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
    ),
    $entry(
        'KB-FOP-REQ-003',
        'Caregiver applications and no-response states',
        'An open request may have no caregiver responses yet, or it may have applications or conversations waiting for review. The assistant can read the current authorized count and open the caregiver-responses area. It must not invent interest, explain why a specific caregiver did not respond, or promise when someone will apply.',
        'Applicants',
        'family.care_requests',
        ['FAM-REQUEST-035', 'FAM-MATCH-013'],
        ['Current applicant and response counts may be read from the authorized request.', 'No response is not proof that the request is broken.', 'Caregiver timing and interest cannot be promised.'],
        ['Why a caregiver did or did not apply.', 'That a profile view means an application or commitment.'],
        ['Did any caregivers respond?', 'Why do I have no applicants?', 'Show me who applied.'],
        ['Guarantee someone applies today.', 'Hire somebody automatically.', 'Show applicants for another account.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-REQ-004',
        'Review and compare caregiver applicants',
        'Compare applicants only from the facts LoLo currently shows to the Family, such as profile information, experience, ratings, reviews, and the caregiver’s response. These facts can help the Family decide, but they are not a guarantee of fit, safety, availability, or future performance. Open each authorized profile or conversation to review details.',
        'Applicants',
        'family.care_requests',
        ['FAM-MATCH-004', 'FAM-MATCH-005', 'FAM-MATCH-014', 'FAM-MATCH-023'],
        ['Only Family-visible applicant facts may be compared.', 'Ratings, reviews, experience, and reliability indicators are not guarantees.', 'The Family chooses between caregivers.'],
        ['A hidden credential, background result, protected characteristic, or subjective safety conclusion.', 'That the assistant selected the best caregiver.'],
        ['Compare the caregivers who applied.', 'What do these ratings mean?', 'Open this applicant’s profile.'],
        ['Reveal a private background check.', 'Guarantee this caregiver is safe.', 'Show an unrelated caregiver’s account.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
    ),
    $entry(
        'KB-FOP-REQ-005',
        'Invite or reinvite a caregiver',
        'A caregiver invitation asks someone to consider an open request; it is not a hire or booking. Available invitation controls depend on the request and caregiver’s current state. Review the exact request and caregiver before sending, and do not promise that the caregiver will accept or respond. If an invitation cannot be sent, use the state shown by the application or ask a person for help.',
        'Applicants',
        'family.care_requests',
        ['FAM-MATCH-008', 'FAM-MATCH-009', 'FAM-MATCH-010', 'FAM-MATCH-011', 'FAM-MATCH-012'],
        ['An invitation is not a hire or booking.', 'Invitation controls depend on current request and caregiver state.', 'A sent invitation does not guarantee a response.'],
        ['That a caregiver is eligible or available without current evidence.', 'That an invitation was sent, canceled, or accepted without a receipt.'],
        ['Invite this caregiver to my request.', 'What is the invitation status?', 'Can I reinvite someone I know?'],
        ['Promise the caregiver will accept.', 'Invite a caregiver to another Family’s request.', 'Transfer account ownership.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
    ),
    $entry(
        'KB-FOP-REQ-006',
        'Message an applicant or hired caregiver',
        'Use the conversation linked to the request, applicant, or hired caregiver. A message remains attributed to the signed-in Family member. The assistant may open the exact conversation and later prepare an editable draft, but it must not say a message was sent or read without the application’s confirmation.',
        'Care messages',
        'family.messages',
        ['FAM-MATCH-017', 'FAM-MATCH-018', 'FAM-MATCH-019', 'FAM-COMMS-002', 'FAM-COMMS-003'],
        ['Messages use the conversation linked to the authorized care relationship.', 'The signed-in Family member remains the sender.', 'Sent and read states require application evidence.'],
        ['That a recipient read, received, or replied to a message without evidence.', 'A private conversation outside the Family Account.'],
        ['Open my conversation with the applicant.', 'Help me message the hired caregiver.', 'Was my message delivered?'],
        ['Send a message as another family member.', 'Show another Family’s conversation.', 'Approve submitted hours.'],
        ['SRC-FAMILY-ACCESS-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-REQ-007',
        'Hiring prerequisites and blocked hiring',
        'Hiring is a material Family action that creates the care relationship or booking through the normal application workflow. Review the caregiver, request, schedule, care details, and payment prerequisites before confirming. If hiring is blocked, LoLo should explain only the current safe prerequisite shown by the application and open the correct step or transfer to a person.',
        'Hiring',
        'family.care_requests',
        ['FAM-MATCH-020', 'FAM-MATCH-021', 'FAM-MATCH-022'],
        ['Hiring is separate from application and messaging.', 'The normal workflow checks schedule, care, and payment prerequisites.', 'A successful hire requires an authoritative booking or care-relationship receipt.'],
        ['That an applicant is hired because the Family selected or messaged them.', 'That payment or availability is ready without current evidence.'],
        ['Hire the caregiver who applied.', 'What happens when I hire someone?', 'Why is the hire button blocked?'],
        ['Hire without showing me the recap.', 'Guarantee this caregiver is available.', 'Show private caregiver verification data.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
    ),
    $entry(
        'KB-FOP-REQ-008',
        'Change, withdraw, or duplicate a live request',
        'Open the current request to see which changes are allowed in its present state. Withdrawing stops an open request from continuing to receive responses. Duplicating starts a new request from prior information and still requires review. Live editing is not available in every state, so LoLo must not promise that a field can be changed or that caregivers were notified until the application confirms it.',
        'Care requests',
        'family.care_requests',
        ['FAM-REQUEST-036', 'FAM-REQUEST-038', 'FAM-REQUEST-040'],
        ['Available request mutations depend on current lifecycle state.', 'Withdrawal and duplication are different actions.', 'A duplicated request remains a new request that must be reviewed.'],
        ['That every live request field is editable.', 'That withdrawing, editing, duplicating, or notifying caregivers succeeded without a receipt.'],
        ['Change the time on my open request.', 'Withdraw this request.', 'Make a copy of my last request.'],
        ['Silently change a booked visit.', 'Reopen a request that cannot be restored.', 'Modify another Family’s request.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
    ),
    $entry(
        'KB-FOP-REQ-009',
        'Expired or withdrawn care request',
        'An expired or withdrawn request is no longer an active open request. The application may offer a new or duplicated request using prior information, but restoration is not guaranteed. Review dates, schedule, recipient, tasks, address, and notes again before publishing a replacement. Use a person when the historical request or existing booking makes the next step unclear.',
        'Care requests',
        'family.care_requests',
        ['FAM-REQUEST-039', 'FAM-REQUEST-040'],
        ['Expired and withdrawn requests are not active open requests.', 'A new or duplicated request requires fresh review.', 'Restoration depends on supported application behavior.'],
        ['That a request can be reopened or that prior details remain current.', 'That a replacement request preserves a caregiver commitment.'],
        ['Can I reopen my expired request?', 'What happened to the request I withdrew?', 'Use the old request to start again.'],
        ['Restore it without asking me.', 'Keep the previous caregiver automatically.', 'Change a completed historical record.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
    ),
    $entry(
        'KB-FOP-REQ-010',
        'Caregiver availability and response times are not guaranteed',
        'LoLo is a marketplace and cannot guarantee that a caregiver will view, apply, accept, or respond by a particular time. The assistant can show the current request and response state and help with the next available action. It must not invent availability or promise a response time. For urgent non-emergency coordination, transfer to LoLo Support; for immediate danger, call 911.',
        'Care requests',
        'support.center',
        ['FAM-REQUEST-044', 'FAM-MATCH-002', 'FAM-MATCH-006', 'FAM-MATCH-007'],
        ['Caregiver visibility, interest, and availability are not guaranteed.', 'Current response state may be read from the authorized request.', 'Urgent coordination is different from an emergency.'],
        ['A guaranteed applicant, caregiver, acceptance, response, or arrival time.', 'That Support can create availability.'],
        ['When will a caregiver respond?', 'Guarantee someone accepts my request.', 'Why was this caregiver recommended?'],
        ['Call 911 for me.', 'Show hidden caregiver data.', 'Promise a support reply time.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-AI-GUIDE-001'],
        ['The user needs urgent coordination that the marketplace cannot promise.'],
    ),

    $entry(
        'KB-FOP-VIS-001',
        'Next visit details and current status',
        'The visit page shows the current date, time, duration, location, care tasks, instructions, caregiver, and lifecycle status that the Family is allowed to see. The assistant may read and summarize the next or current authorized visit, then open it. If several visits could match, ask which one instead of guessing.',
        'Visits',
        'family.care_requests',
        ['FAM-VISIT-001', 'FAM-VISIT-002', 'FAM-VISIT-003'],
        ['The next or current visit may be read from the authorized Family care records.', 'Visit details and status come from the exact booking.', 'Ambiguous visit selection requires clarification.'],
        ['Which visit the user means when several records match.', 'That a scheduled caregiver is currently present.'],
        ['When is my next visit?', 'Who is coming and for how long?', 'What is the status of today’s care?'],
        ['Show another Family’s visit.', 'Guarantee the caregiver arrives.', 'Change my card.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-VIS-002',
        'Message the hired caregiver about a visit',
        'Use the authorized conversation connected to the hired caregiver and care request. Messages are shared with active Family members and remain attributed to the person who sends them. Chat may open the conversation or prepare an editable message later, but it cannot guarantee an immediate reply or treat messaging as an emergency channel.',
        'Visits',
        'family.messages',
        ['FAM-VISIT-004', 'FAM-REGULAR-025', 'FAM-COMMS-002', 'FAM-COMMS-003'],
        ['The care conversation is the normal place to message the hired caregiver.', 'Messages remain attributed to their real sender.', 'Messaging is not an emergency service.'],
        ['That the caregiver will see or answer immediately.', 'That another member authored the message.'],
        ['Message the caregiver before the visit.', 'Open the conversation for today’s care.', 'Help me write to our regular caregiver.'],
        ['Use this for an emergency.', 'Send as the account owner.', 'Show a private unrelated conversation.'],
        ['SRC-FAMILY-ACCESS-001', 'SRC-FAMILY-WORKFLOW-001'],
    ),
    $entry(
        'KB-FOP-VIS-003',
        'Reschedule or cancel a visit',
        'Open the exact scheduled visit to see whether reschedule or cancellation is currently allowed and what consequences the application shows. A request to change a visit is not complete until the normal workflow confirms it. Late-cancellation consequences depend on the applicable policy and current timing; LoLo must not invent a fee, refund, or caregiver response.',
        'Visits',
        'family.care_requests',
        ['FAM-VISIT-005', 'FAM-VISIT-006', 'FAM-VISIT-007', 'FAM-VISIT-008'],
        ['Reschedule and cancellation availability depends on the exact visit state and timing.', 'The normal workflow must confirm a change.', 'Policy consequences require approved current product truth.'],
        ['That cancellation is allowed or free in every state.', 'That a caregiver accepted a reschedule without evidence.'],
        ['I need to reschedule the visit.', 'Cancel tomorrow’s care.', 'What happens if I cancel late?'],
        ['Cancel another Family’s visit.', 'Promise there is no charge.', 'Tell the caregiver without confirmation.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
    ),
    $entry(
        'KB-FOP-VIS-004',
        'Caregiver schedule-change request',
        'A caregiver change request proposes a specific schedule change; it does not take effect merely because it was sent. Open the exact visit and review the current schedule beside the proposed change. Accept or reject only through the normal decision control, and verify the resulting booking state before saying the schedule changed.',
        'Visits',
        'family.care_requests',
        ['FAM-VISIT-009', 'FAM-VISIT-010', 'FAM-VISIT-011'],
        ['A proposed change and the current schedule are distinct.', 'The Family reviews the exact difference before deciding.', 'Completion requires the resulting booking state.'],
        ['That a proposed change already changed the visit.', 'That accept or reject succeeded because the button was clicked.'],
        ['The caregiver asked to change the visit.', 'Show the old and new time.', 'Help me accept or reject the schedule request.'],
        ['Change the schedule without showing me.', 'Promise the caregiver accepts my change.', 'Open another account’s booking.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-VIS-005',
        'Check-in, lateness, and no-show',
        'Check-in or check-out status comes from the exact visit record and may not by itself prove where a person physically is. If a caregiver is late, use the care conversation or visit-support action. Marking a no-show is a material report and must use the supported visit workflow with explicit confirmation. Immediate danger requires 911 before LoLo Support.',
        'Visit problems',
        'family.care_requests',
        ['FAM-VISIT-012', 'FAM-VISIT-013', 'FAM-VISIT-014'],
        ['Visit check-in/out state is an application record.', 'Late and no-show are different states and actions.', 'A no-show report requires the supported visit workflow.'],
        ['A person’s physical location or safety from an app timestamp alone.', 'That a late caregiver is a confirmed no-show.'],
        ['Did the caregiver check in?', 'The caregiver is late.', 'How do I report a no-show?'],
        ['Track the caregiver’s location.', 'Mark no-show without confirmation.', 'Wait for support during an emergency.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
    ),
    $entry(
        'KB-FOP-VIS-006',
        'Safety issue or problem with a visit',
        'For immediate danger or urgent medical help, call 911 now; LoLo Support is not a substitute. For a non-emergency safety issue, serious complaint, or visit problem, LoLo can prepare the visit reference and the user’s description and transfer the same conversation to a person. The assistant must not diagnose, investigate, decide fault, or promise an outcome.',
        'Visit problems',
        'support.center',
        ['FAM-VISIT-015', 'FAM-VISIT-016', 'FAM-VISIT-027', 'FAM-VISIT-028'],
        ['Immediate danger receives 911-first instructions.', 'Non-emergency visit problems may transfer with authorized visit context.', 'A person handles investigation and exceptional dispute outcomes.'],
        ['Fault, liability, diagnosis, severity, or resolution.', 'That LoLo contacted emergency services.'],
        ['Report a safety problem during the visit.', 'I need support about this care.', 'Escalate the hours dispute to LoLo.'],
        ['Diagnose this injury.', 'Tell me who is at fault.', 'Promise a refund.'],
        ['SRC-LOLO-SAFETY-001', 'SRC-FAMILY-WORKFLOW-001'],
        ['The user reports immediate danger, medical need, serious safety concern, or a material dispute.'],
    ),
    $entry(
        'KB-FOP-VIS-007',
        'What submitted-hours review means',
        'After care, the caregiver may submit start time, end time, total duration, completed tasks, and notes for Family review. Compare those values with the Family’s understanding before approving. Opening or viewing submitted hours does not approve them or trigger payment. The assistant can read the current review state and open the exact record.',
        'Submitted hours',
        'family.care_requests',
        ['FAM-VISIT-018', 'FAM-VISIT-019'],
        ['Submitted hours are caregiver-reported values awaiting the applicable Family workflow.', 'Viewing does not equal approval.', 'The exact booking is authoritative for submitted values and review state.'],
        ['That submitted values are correct or approved.', 'That payment occurred when the review opened.'],
        ['What is a timesheet review?', 'Show the caregiver’s submitted hours.', 'What tasks and notes were reported?'],
        ['Approve without showing the hours.', 'Change the card.', 'Show a different Family’s timesheet.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-VIS-008',
        'Approve submitted hours and payment',
        'Approving submitted hours is a payment-affecting action. Review the caregiver-reported start, end, duration, tasks, notes, and amount before confirming through the normal application. The assistant must show the material recap and receive an authoritative approval/payment result before saying the hours were approved or paid.',
        'Submitted hours',
        'family.care_requests',
        ['FAM-VISIT-020', 'FAM-VISIT-024', 'FAM-VISIT-034'],
        ['Hours approval is payment-affecting.', 'Material submitted values and amount must be reviewed before confirmation.', 'Success requires the authoritative domain result.'],
        ['That hours are accurate, approved, or paid without confirmation and receipt.', 'Caregiver payout status.'],
        ['Approve the submitted hours.', 'Does approving this trigger payment?', 'Approve the corrected time and pay.'],
        ['Approve without a recap.', 'Tell me the caregiver’s bank payout.', 'Change submitted hours silently.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
    ),
    $entry(
        'KB-FOP-VIS-009',
        'Question or correct submitted hours',
        'If submitted hours look wrong, do not approve them. Open the exact visit to question the hours, ask the caregiver for a correction, review a returned correction, or escalate a dispute. A prepared correction or message remains editable and is not sent until the normal workflow confirms it. LoLo does not decide whose version is correct.',
        'Submitted hours',
        'family.care_requests',
        ['FAM-VISIT-021', 'FAM-VISIT-022', 'FAM-VISIT-023', 'FAM-VISIT-025', 'FAM-VISIT-027', 'FAM-VISIT-028', 'FAM-VISIT-029'],
        ['The Family should not approve hours it believes are wrong.', 'Correction, returned correction, and dispute are distinct states.', 'The assistant may prepare context but does not decide factual fault.'],
        ['Which party is correct.', 'That a correction request, dispute, or payment change was submitted without a receipt.'],
        ['These submitted hours are wrong.', 'Ask the caregiver to correct the time.', 'What is the status of my hours dispute?'],
        ['Approve the disputed hours anyway.', 'Change the record without telling anyone.', 'Promise the dispute outcome.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
        ['The parties disagree materially or the user asks for an investigation.'],
    ),
    $entry(
        'KB-FOP-VIS-010',
        'Completed visit, review, and booking again',
        'After a visit and its required hours/payment steps are complete, Care history keeps the authorized record. The Family may leave a review or start a new one-time or regular-care request with the same caregiver when the product offers those actions. Rebooking is a new care commitment with a new schedule and confirmation; it does not reuse old dates or guarantee availability.',
        'Care history',
        'family.care_history',
        ['FAM-VISIT-030', 'FAM-VISIT-032', 'FAM-VISIT-033', 'FAM-HISTORY-011', 'FAM-HISTORY-012'],
        ['Completed care appears in Care history.', 'Review and rebooking are later optional actions.', 'Rebooking requires a new schedule and confirmation.'],
        ['That a prior caregiver is available.', 'That old dates, payment, or approval carry into new care.'],
        ['Leave a review for the completed visit.', 'Book the same caregiver again.', 'Turn this good visit into weekly care.'],
        ['Guarantee the caregiver accepts.', 'Reuse the old date without review.', 'Delete the historical record.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-AI-GUIDE-001'],
    ),

    $entry(
        'KB-FOP-PRO-001',
        'What a care-receiver profile is and who sees it',
        'A care-receiver profile stores reusable information about the person receiving non-medical care. The Family controls it. Candidate caregivers see only the approved candidate summary connected to an active care opportunity; an assigned caregiver may see additional care-coordination information after care is confirmed. The profile is not public, and empty sections are not shown.',
        'Care profiles',
        'family.care_profiles',
        ['FAM-PROFILE-001', 'FAM-PROFILE-015', 'FAM-PROFILE-016'],
        ['Care profiles are reusable Family-controlled records.', 'Candidate and assigned caregivers receive different authorized views.', 'Profiles are not public and empty sections are omitted.'],
        ['That every caregiver can see a profile.', 'A field or contact that is not in the authorized snapshot.'],
        ['What is a care receiver profile?', 'What can an applicant see?', 'What will the hired caregiver see?'],
        ['Make the profile public.', 'Show this profile to an unrelated caregiver.', 'Add medical treatment instructions.'],
        ['SRC-RECIPIENT-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-PRO-002',
        'Draft and Ready-to-use care profiles',
        'A Draft care profile is saved but may still need information or the final sharing review. Ready to use means the Family completed the profile review so it can be selected for new care. A draft can be finished later. The assistant may read the next missing profile step and open it, but must verify the save or Ready state before saying it is complete.',
        'Care profiles',
        'family.care_profiles',
        ['FAM-PROFILE-002', 'FAM-PROFILE-003', 'FAM-PROFILE-004', 'FAM-PROFILE-005'],
        ['Draft profiles can be saved and finished later.', 'Ready to use follows the profile sharing review.', 'The next missing step may be read from the authorized profile.'],
        ['That a Draft is safe or complete enough for care.', 'That a profile became Ready because its page was opened.'],
        ['Why is this care profile a draft?', 'Help me finish the recipient profile.', 'Mark the profile ready for requests.'],
        ['Publish a care request instead.', 'Show an unrelated profile.', 'Skip the sharing review and call it ready.'],
        ['SRC-RECIPIENT-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-PRO-003',
        'Recipient identity and relationship information',
        'A care profile identifies who receives care, whether that person is the Family user, and the Family relationship. Preferred name and other identity fields help caregivers address the person respectfully. Review sensitive identity information before saving and correct it in the profile; the assistant must not infer a date of birth, pronouns, relationship, or legal identity.',
        'Care profiles',
        'family.care_profiles',
        ['FAM-PROFILE-006', 'FAM-PROFILE-007'],
        ['The profile records who receives care and the Family relationship.', 'Identity fields should be reviewed before save.', 'The assistant may prepare only explicitly supplied or authorized saved values.'],
        ['Date of birth, pronouns, relationship, preferred name, or legal identity from other context.'],
        ['The care is for me.', 'Change the recipient’s preferred name.', 'Fix the relationship on the care profile.'],
        ['Guess their date of birth.', 'Copy identity from another account.', 'Change the person after a completed booking.'],
        ['SRC-RECIPIENT-001'],
    ),
    $entry(
        'KB-FOP-PRO-004',
        'Non-medical care notes and safety boundaries',
        'Care profiles may include interests, comforts, communication, mobility, routines, food or allergy context, personal-care preferences, overnight preferences, and non-medical safety notes that help a caregiver provide good support. Do not put medication dosages, treatment instructions, passwords, financial details, urgent medical instructions, or other secrets in the profile. Medical needs go to a licensed professional; immediate danger requires 911.',
        'Care profiles',
        'family.care_profiles',
        ['FAM-PROFILE-008', 'FAM-PROFILE-009', 'FAM-PROFILE-010', 'FAM-PROFILE-011', 'FAM-PROFILE-012', 'FAM-PROFILE-013'],
        ['Care profiles support non-medical everyday care context.', 'Sensitive secrets and clinical instructions do not belong in the profile.', 'Medical and emergency boundaries still apply.'],
        ['A diagnosis, treatment, dosage, clinical instruction, or emergency assessment.', 'That a profile field makes a clinical task permitted.'],
        ['Add communication and mobility notes.', 'Where do I put food allergies?', 'Help me describe a good visit.'],
        ['Tell the caregiver an insulin dose.', 'Save my password or bank details.', 'Use the profile instead of calling 911.'],
        ['SRC-RECIPIENT-001', 'SRC-LOLO-SAFETY-001'],
        ['The user asks for medical/clinical help or describes immediate danger.'],
    ),
    $entry(
        'KB-FOP-PRO-005',
        'Additional contact for care coordination',
        'A Family may add an additional contact for care coordination. Review the contact’s name, relationship, and permitted details before saving. Candidate caregivers do not automatically receive assigned-care contact information. The assistant must not copy contact information from another account or reveal it without the authorized profile and care relationship.',
        'Care profiles',
        'family.care_profiles',
        ['FAM-PROFILE-014'],
        ['An additional contact is care-coordination information.', 'Candidate and assigned visibility differ.', 'Contact details require account-scoped authorization.'],
        ['A contact’s identity, phone, email, permission, or visibility without the profile record.', 'That adding a contact authorizes emergency or medical decisions.'],
        ['Add my sister as an additional contact.', 'Who sees the care contact?', 'Change the contact on the profile.'],
        ['Copy a contact from another Family.', 'Show the contact to every caregiver.', 'Make the contact a medical decision-maker.'],
        ['SRC-RECIPIENT-001'],
    ),
    $entry(
        'KB-FOP-PRO-006',
        'Profile changes and current care',
        'Saving a reusable profile creates a new current version, but existing requests, bookings, or care plans keep their attached historical version until the Family deliberately applies an update where supported. Saving a profile must not silently change current care. LoLo should show which care may be affected and require a separate review before applying a newer version.',
        'Care profiles',
        'family.care_profiles',
        ['FAM-PROFILE-017', 'FAM-PROFILE-018'],
        ['Reusable profiles have current versions while care records keep attached historical versions.', 'Saving does not silently update active care.', 'Applying an update to current care is a separate reviewed action.'],
        ['That every current caregiver received a profile update.', 'That active care changed because the reusable profile was saved.'],
        ['Apply the profile update to current care.', 'Save this without changing existing visits.', 'Will editing the profile change the booking?'],
        ['Silently replace every attached version.', 'Rewrite historical care.', 'Tell me the caregiver saw the update without evidence.'],
        ['SRC-RECIPIENT-001'],
    ),
    $entry(
        'KB-FOP-PRO-007',
        'Default, archived, and restored care profiles',
        'The default profile is only the person preselected to make new care easier; the Family may choose another profile. Archiving removes a profile from ordinary new-care selection but does not break historical care that already uses a saved version. Restore makes an archived profile available again when the product allows it. Each state change requires the application’s confirmation.',
        'Care profiles',
        'family.care_profiles',
        ['FAM-PROFILE-019', 'FAM-PROFILE-020', 'FAM-PROFILE-021'],
        ['Default means preselected, not permanently privileged.', 'Archiving does not destroy attached historical versions.', 'Restore and state-change success require application confirmation.'],
        ['That an archived profile is deleted.', 'That default or archive changed without a receipt.'],
        ['Change the default care profile.', 'Archive this recipient profile.', 'Restore the archived profile.'],
        ['Permanently delete all historical care.', 'Archive another Family’s profile.', 'Call it restored because the page opened.'],
        ['SRC-RECIPIENT-001'],
    ),
    $entry(
        'KB-FOP-PRO-008',
        'Reuse a care profile, address, and home notes',
        'A new request may propose an authorized Ready-to-use care profile, the Family household address, and home-access notes. Those saved values are suggestions for the new request, not automatic confirmation. The Family can choose a different profile or edit the address and notes before the recap. Previous request information is reused only when the user asks for it.',
        'Care profiles',
        'family.new_care_request',
        ['FAM-PROFILE-022', 'FAM-PROFILE-023', 'FAM-PROFILE-024', 'FAM-REQUEST-017', 'FAM-REQUEST-018', 'FAM-REQUEST-020', 'FAM-REQUEST-021'],
        ['Authorized saved profile and household data may be proposed for a new request.', 'Every proposed value remains visible and editable.', 'Previous-request reuse requires explicit instruction.'],
        ['That saved information is current or confirmed for new care.', 'A door code, secret, or stale address not explicitly reviewed.'],
        ['Use the saved care profile in this request.', 'Change the address LoLo filled in.', 'Use the same details as my last request.'],
        ['Reuse everything without showing me.', 'Copy another Family’s address.', 'Publish before the recap.'],
        ['SRC-RECIPIENT-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-ACC-001',
        'Account owner and Family member roles',
        'Each person uses their own LoLo login. The Account owner manages invitations, access removal, ownership, and account closure. Active Family members share authorized care, visits, messages, history, and day-to-day care actions. The current application also allows active members to use the secure shared payment-method flow. Every sensitive action is attributed to the signed-in person.',
        'Family access',
        'family.access',
        ['FAM-ACCESS-001', 'FAM-ACCESS-003', 'FAM-ACCESS-005', 'FAM-ACCESS-014', 'FAM-ACCESS-015'],
        ['The user-facing roles are Account owner and Family member.', 'Each person uses a separate login and actions keep their real actor.', 'Owner-only access administration remains distinct from shared day-to-day care.', 'The current secure payment-method flow is available to active members.'],
        ['A named person’s role or membership without fresh account context.', 'Granular per-recipient or per-conversation permissions that the product does not offer.'],
        ['What can a Family member do?', 'Who manages Family access?', 'Can a member use the shared card flow?'],
        ['Show another account’s members.', 'Make me the owner automatically.', 'Hide one recipient from a member.'],
        ['SRC-CODE-FAMILY-ACCESS-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-ACC-002',
        'Invite and accept a Family member',
        'Only the Account owner manages Family invitations. The invited person uses their own email and login, reviews the shared-access disclosure, and accepts a valid invitation. Invitations expire and may become unavailable after cancellation, replacement, or use. LoLo must read the current invitation state rather than expose a token or assume which account the person should join.',
        'Family access',
        'family.access',
        ['FAM-ACCESS-004', 'FAM-ACCESS-005', 'FAM-ACCESS-007', 'FAM-ACCESS-009', 'FAM-ACCESS-010', 'FAM-ACCESS-011'],
        ['Family invitations are Account-owner actions.', 'The invited person uses their own login.', 'Invitation state and validity are server-authoritative.'],
        ['An invitation token, invited email, membership, or acceptance state without authorization.', 'That an invitation guarantees eligibility.'],
        ['Invite my daughter to help.', 'How does someone accept Family access?', 'This invitation expired.'],
        ['Paste the invitation token in chat.', 'Invite from a non-owner account.', 'Join two Family Accounts automatically.'],
        ['SRC-FAMILY-ACCESS-001', 'SRC-CODE-FAMILY-ACCESS-001'],
    ),
    $entry(
        'KB-FOP-ACC-003',
        'Resend, cancel, remove, leave, or recover Family access',
        'The Account owner may manage a pending invitation and remove another member. A non-owner member may leave the Family Account. Removal or leaving ends future access immediately but does not erase historical messages or actions. Ownership transfer, duplicate-account repair, wrong-account membership, and unclear access loss require LoLo Support to verify the people and account safely.',
        'Family access',
        'family.access',
        ['FAM-ACCESS-006', 'FAM-ACCESS-008', 'FAM-ACCESS-012', 'FAM-ACCESS-013', 'FAM-ACCESS-016', 'FAM-ACCESS-018', 'FAM-ACCESS-019'],
        ['Owner and member exit actions differ.', 'Access removal does not erase historical attribution.', 'Ownership and conflicting-account repairs are support-assisted.'],
        ['That removed access can still view current care.', 'That historical actions are deleted.', 'That ownership transferred without human verification.'],
        ['Resend the Family invitation.', 'Remove this member’s access.', 'Why did my Family access end?'],
        ['Erase all of the member’s history.', 'Transfer ownership without verification.', 'Show care after removal.'],
        ['SRC-FAMILY-ACCESS-001', 'SRC-CODE-FAMILY-ACCESS-001'],
        ['The request involves ownership transfer, duplicate accounts, wrong-account membership, or disputed access.'],
    ),

    $entry(
        'KB-FOP-COM-001',
        'Family message inbox and unread conversations',
        'The Family message inbox contains authorized caregiver conversations. Active Family members share the conversation, while each member has their own unread state. The assistant may tell the signed-in user that an authorized conversation is unread and open it. Reading for one member must not be described as clearing another member’s unread state.',
        'Messages',
        'family.messages',
        ['FAM-COMMS-001', 'FAM-COMMS-002', 'FAM-COMMS-003'],
        ['Family caregiver conversations are shared care records.', 'Unread state is personal to each active Family member.', 'Exact conversation access is re-authorized.'],
        ['Another member’s unread state.', 'A conversation outside the active Family Account.'],
        ['Open my message inbox.', 'Which caregiver message is unread?', 'Find the conversation for this request.'],
        ['Clear everyone’s unread messages.', 'Show another Family’s inbox.', 'Read a removed member’s conversation.'],
        ['SRC-FAMILY-ACCESS-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-COM-002',
        'Message sending problems and unsafe messages',
        'A message may be unavailable when the conversation, care relationship, or Family access no longer permits sending. Use the current application state; do not guess that a caregiver blocked or ignored the user. Harassment, abuse, threats, unsafe content, or serious credential concerns should be preserved in the conversation and transferred to LoLo Support. Immediate danger requires 911.',
        'Messages',
        'support.center',
        ['FAM-COMMS-004', 'FAM-COMMS-005', 'FAM-MATCH-024', 'FAM-MATCH-025'],
        ['Send availability depends on current conversation and access state.', 'Unsafe messaging and serious profile concerns require human review.', 'Immediate danger receives emergency instructions first.'],
        ['Why a person did not respond.', 'That a caregiver blocked the user or committed misconduct without evidence.'],
        ['Why can’t I send this message?', 'Report unsafe messages.', 'This caregiver profile seems misleading.'],
        ['Diagnose the caregiver.', 'Delete evidence from the conversation.', 'Promise disciplinary action.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
        ['The user reports harassment, abuse, threats, immediate danger, or serious credential concerns.'],
    ),
    $entry(
        'KB-FOP-COM-003',
        'Notifications, read state, and filters',
        'Family notifications describe shared care events and link back to the authorized request, visit, message, or payment record. The notification text is a pointer, not proof that the linked state is still unchanged. Read/unread filters affect the signed-in member’s presentation. Re-authorize the linked record when it is opened.',
        'Notifications',
        'family.dashboard',
        ['FAM-COMMS-006', 'FAM-COMMS-007', 'FAM-COMMS-008', 'FAM-COMMS-009', 'FAM-COMMS-010', 'FAM-COMMS-011', 'FAM-COMMS-012'],
        ['Notifications point to shared care events.', 'Linked state must be freshly re-authorized and read.', 'Read state and filters belong to the signed-in member.'],
        ['That an old notification proves the current domain state.', 'Another member’s notification read state.'],
        ['What does this notification mean?', 'Open the visit from this alert.', 'Show only my unread notifications.'],
        ['Use an old link after access ended.', 'Mark another person’s notifications read.', 'Treat a notification as a payment receipt.'],
        ['SRC-FAMILY-ACCESS-001', 'SRC-CODE-DASHBOARD-001'],
    ),
    $entry(
        'KB-FOP-COM-004',
        'Notification preferences and missing delivery',
        'In-app notifications for shared care and each person’s email preferences are separate. A missing email may relate to that member’s verified contact information, preferences, delivery, or the event’s channel. Open Account Settings to review personal notification settings. Do not promise that an email was sent or delivered without a delivery record, and transfer persistent delivery problems to a person.',
        'Notifications',
        'account.profile',
        ['FAM-COMMS-013', 'FAM-COMMS-014', 'FAM-COMMS-015', 'FAM-COMMS-016'],
        ['Notification preferences are personal to each user.', 'In-app and email delivery are distinct.', 'Sent/delivered claims require a delivery record.'],
        ['That a missing email proves the event did not happen.', 'A destination email or verification state without authorized account data.'],
        ['Change my notification preferences.', 'Why did I not receive the email?', 'Unsubscribe from non-essential messages.'],
        ['Disable required safety notices without policy.', 'Show another member’s email.', 'Promise delivery next time.'],
        ['SRC-FAMILY-ACCESS-001', 'SRC-CODE-ACCOUNT-SETTINGS-001'],
    ),
    $entry(
        'KB-FOP-REG-001',
        'Regular-care plan status and upcoming visits',
        'Regular care repeats on an agreed schedule. A plan may be pending, active, paused, or ended, and generated visits have their own dates and states. The assistant may read the authorized plan status and next relevant visit and open the plan. It must not infer that a pending plan is accepted or that a future caregiver is available.',
        'Regular care',
        'family.regular_care',
        ['FAM-REGULAR-001', 'FAM-REGULAR-009', 'FAM-REGULAR-010'],
        ['Regular-care plan state and generated-visit state are distinct.', 'Plan status and next visit require current authorized reads.', 'Pending does not equal accepted.'],
        ['Caregiver acceptance or availability from a pending plan.', 'That every future visit is confirmed.'],
        ['Show my regular-care plan.', 'When is the next weekly visit?', 'Is regular care active or paused?'],
        ['Guarantee every future visit.', 'Show another Family’s plan.', 'Call pending accepted.'],
        ['SRC-REGULAR-CARE-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-REG-002',
        'Regular-care offer and caregiver counteroffer',
        'Setting up regular care with a known caregiver requires the weekly schedule, care details, a message, and the applicable payment method before the offer is sent. A caregiver may accept, decline, or propose a counteroffer. Review the exact current and proposed schedule before accepting. An offer or counteroffer is not active care until the application confirms the accepted plan.',
        'Regular care',
        'family.regular_care',
        ['FAM-REGULAR-002', 'FAM-REGULAR-003', 'FAM-REGULAR-004', 'FAM-REGULAR-005', 'FAM-REGULAR-006', 'FAM-REGULAR-007', 'FAM-REGULAR-008'],
        ['Regular-care offers include schedule, care details, and a message.', 'Counteroffers require a clear current-versus-proposed comparison.', 'Accepted active care requires an authoritative plan result.'],
        ['That a caregiver accepted or is available.', 'That payment readiness or an offer exists without current state.'],
        ['Set up weekly care with this caregiver.', 'What is the caregiver’s counteroffer?', 'Why do I need a payment method for regular care?'],
        ['Accept without showing the differences.', 'Guarantee the caregiver agrees.', 'Create a plan for another Family.'],
        ['SRC-REGULAR-CARE-001', 'SRC-FAMILY-WORKFLOW-001'],
    ),
    $entry(
        'KB-FOP-REG-003',
        'Skip, add, or change regular-care visits',
        'A Family may use the regular-care plan to manage an upcoming visit, request a future schedule change, or add an extra visit when the current plan state permits it. Skipping one visit does not automatically pause or end the plan. An extra visit has its own date, time, duration, completion, review, and payment steps. Verify each resulting visit or request before saying it changed.',
        'Regular care',
        'family.regular_care',
        ['FAM-REGULAR-011', 'FAM-REGULAR-012', 'FAM-REGULAR-013', 'FAM-REGULAR-014', 'FAM-REGULAR-015', 'FAM-REGULAR-016', 'FAM-REGULAR-017', 'FAM-REGULAR-018', 'FAM-REGULAR-019'],
        ['Skipping one visit, changing the future schedule, and adding an extra visit are distinct.', 'Extra visits have separate completion and payment states.', 'Every change requires the resulting plan/visit state.'],
        ['That one skipped visit pauses the plan.', 'That an extra visit is accepted, completed, approved, or paid without evidence.'],
        ['Skip next week’s regular visit.', 'Add one extra visit.', 'Change the future weekly schedule.'],
        ['End the whole plan when I skip once.', 'Call the extra visit paid without approval.', 'Guarantee the caregiver accepts the change.'],
        ['SRC-REGULAR-CARE-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-REG-004',
        'Pause, resume, or end regular care',
        'Pausing regular care temporarily stops future plan activity according to the plan workflow; resuming restarts it from an authorized current state. Ending care is different and may affect future visits, including the next one. Review the impact on generated visits before confirming. Replacing the caregiver or resolving a disputed end state requires LoLo Support when the product does not offer a clear control.',
        'Regular care',
        'family.regular_care',
        ['FAM-REGULAR-020', 'FAM-REGULAR-021', 'FAM-REGULAR-022', 'FAM-REGULAR-023', 'FAM-REGULAR-024', 'FAM-REGULAR-025', 'FAM-REGULAR-026'],
        ['Pause, resume, and end are distinct plan actions.', 'The effect on future and next visits must be reviewed.', 'Caregiver replacement may require human help.'],
        ['That pausing or ending automatically handles every generated visit.', 'That a replacement caregiver is available.'],
        ['Pause my regular care.', 'Resume the weekly plan.', 'End regular care and cancel the next visit.'],
        ['End the plan without showing the next visit.', 'Replace the caregiver automatically.', 'Promise the schedule restarts unchanged.'],
        ['SRC-REGULAR-CARE-001', 'SRC-CODE-AI-GUIDE-001'],
        ['The user needs caregiver replacement or the plan/visit impact cannot be resolved safely.'],
    ),
    $entry(
        'KB-FOP-HIS-001',
        'Find and understand Care history',
        'Care history contains authorized past visits and related Family-visible records. Use its filters or exact record to review the caregiver, recipient, tasks, timeline, change requests, incidents, reviews, and available payment values. Summary totals and amounts must be calculated from the current records, not remembered or estimated by the assistant.',
        'Care history',
        'family.care_history',
        ['FAM-HISTORY-001', 'FAM-HISTORY-002', 'FAM-HISTORY-003', 'FAM-HISTORY-004', 'FAM-HISTORY-005', 'FAM-HISTORY-006', 'FAM-HISTORY-007', 'FAM-HISTORY-008', 'FAM-HISTORY-009', 'FAM-HISTORY-010'],
        ['Care history is the Family destination for past care records.', 'Filters and exact records determine the displayed history.', 'Totals and amounts require current authoritative records.'],
        ['A missing historical record, total, incident, review, or amount.', 'Caregiver payout or private provider details.'],
        ['Open my Care history.', 'Find the visit with this caregiver.', 'Explain the totals in my history.'],
        ['Show another Family’s history.', 'Estimate missing payment amounts.', 'Reveal caregiver payout.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-AI-GUIDE-001'],
    ),
    $entry(
        'KB-FOP-HIS-002',
        'Book again, reuse prior care, or correct history',
        'A past visit may help start a new one-time or regular-care request with the same caregiver or reused care details, but the new schedule and recap must be reviewed and caregiver availability is not guaranteed. Download or print options depend on the current product. An inaccurate historical record or unsupported document request should be prepared with the exact visit reference and transferred to LoLo Support rather than silently rewritten.',
        'Care history',
        'family.care_history',
        ['FAM-HISTORY-011', 'FAM-HISTORY-012', 'FAM-HISTORY-013', 'FAM-HISTORY-014', 'FAM-HISTORY-015'],
        ['Rebooking creates new care and requires a new schedule/recap.', 'History export availability depends on the product.', 'Historical record correction requires controlled support review.'],
        ['That a prior caregiver is available.', 'That historical care can be silently edited or that a download exists.'],
        ['Book the same caregiver again.', 'Reuse this visit with a different schedule.', 'This historical record is wrong.'],
        ['Rewrite the old record silently.', 'Guarantee the caregiver accepts.', 'Invent a downloadable invoice.'],
        ['SRC-FAMILY-WORKFLOW-001', 'SRC-CODE-CARE-REQUESTS-001'],
        ['The user disputes a historical record or needs a document the product does not provide.'],
    ),
];

$initial = require __DIR__.'/v1.php';
$familyAccessRevision = null;
foreach ((array) $initial['entries'] as $candidate) {
    if (($candidate['stable_id'] ?? null) === 'KB-FAM-004') {
        $familyAccessRevision = $candidate;
        $familyAccessRevision['intent_ids'] = [
            'FAM-ACCESS-001', 'FAM-ACCESS-005', 'FAM-ACCESS-014', 'FAM-ACCESS-015',
            'FAM-PAY-002', 'FAM-PAY-008',
        ];
        $familyAccessRevision['change_note'] = 'Correct Family payment-method guidance to match the current active-member secure flow and Family Operations KB Wave 1.';
        $familyAccessRevision['review_by'] = $reviewBy;
        $familyAccessRevision['evaluation_ids'] = [
            'EVAL-KB-FAM-004-V2-POSITIVE',
            'EVAL-KB-FAM-004-V2-BOUNDARY',
            'EVAL-KB-FAM-004-V2-WRONG-ROLE',
            'EVAL-KB-FAM-004-V2-UNSUPPORTED-STATE',
            'EVAL-KB-FAM-004-V2-HANDOFF',
        ];
        break;
    }
}

if (! is_array($familyAccessRevision)) {
    throw new RuntimeException('KB-FAM-004 revision source is missing.');
}

return [
    'version' => 'family-operations-kb-v1',
    'approved_at' => '2026-08-18',
    'entries' => $entries,
    'revisions' => [$familyAccessRevision],
];
