<?php

$reviewBy = '2026-11-12';

$entry = static function (
    string $id,
    string $title,
    string $answer,
    string $target,
    array $mayState,
    array $mustNotInfer,
    array $matches,
    array $noMatches,
    string $sourceSection,
    array $roles = ['family'],
    string $capability = 'support_answers_v1',
    string $type = 'task_playbook',
) use ($reviewBy): array {
    $evalPrefix = str_replace('KB-', 'EVAL-KB-', $id);

    return [
        'stable_id' => $id,
        'type' => $type,
        'title' => $title,
        'answer_body' => $answer,
        'sensitivity' => 'authenticated',
        'product_area' => 'Interactive care requests',
        'locale' => 'en-US',
        'roles' => $roles,
        'membership_states' => ['active'],
        'route_target_ids' => [$target],
        'capability_ids' => [$capability],
        'facts_may_state' => $mayState,
        'facts_must_not_infer' => $mustNotInfer,
        'next_actions' => ['navigate:'.$target, 'handoff:SUP-HANDOFF-001'],
        'escalation_conditions' => [
            'The user asks for a person.',
            'Current authorization or authoritative account state cannot be resolved safely.',
        ],
        'retrieval_examples_match' => $matches,
        'retrieval_examples_no_match' => $noMatches,
        'evaluation_ids' => [
            $evalPrefix.'-POSITIVE',
            $evalPrefix.'-BOUNDARY',
            $evalPrefix.'-WRONG-ROLE',
            $evalPrefix.'-UNSUPPORTED-STATE',
            $evalPrefix.'-HANDOFF',
        ],
        'change_note' => 'Approved interactive-support definition under DEC-048 through DEC-066.',
        'review_by' => $reviewBy,
        'expires_on' => null,
        'sources' => [[
            'source_id' => 'SRC-AI-INTERACTIVE-001',
            'title' => 'Interactive Assistant Approved Build Contract',
            'url' => null,
            'section_anchor' => $sourceSection,
            'fact_supported' => implode(' ', $mayState),
        ]],
    ];
};

return [
    'version' => 'interactive-kb-v1',
    'approved_at' => '2026-08-14',
    'entries' => [
        $entry(
            'KB-CARE-001',
            'Choosing one-time, regular, or 24/7 care',
            'Choose one-time care for one specific visit. Choose regular care for visits that repeat each week. For continuous day-and-night or 24/7 coverage, LoLo Support needs to help. The assistant recommends a path, but you choose it before a private draft starts.',
            'family.new_care_request',
            ['One-time care is one specific visit.', 'Regular care repeats weekly.', '24/7 coverage transfers to LoLo Support.', 'The Family user explicitly chooses the path.'],
            ['Caregiver availability.', 'That a request, booking, hire, or payment already exists.', 'A care path when the need remains ambiguous.'],
            ['Which type of request do I need?', 'Is this one-time or regular care?', 'I need care all day and night.'],
            ['Hire a caregiver now.', 'Change my payment method.', 'A Caregiver wants to accept work.'],
            'Sections 1 and 3',
        ),
        $entry(
            'KB-CARE-002',
            'What a one-time care request needs',
            'A one-time request needs the person receiving care, at least one kind of non-medical help, the care address, a future date, a clear start time, and a visit length from 1 to 12 hours in 30-minute steps. The recap shows Eastern Time before confirmation.',
            'family.new_care_request',
            ['Required one-time fields are recipient, approved task, address, future date, start time, and duration.', 'Durations are 1 to 12 hours in 30-minute increments.', 'The recap says Eastern Time.'],
            ['A vague morning or afternoon as a start time.', 'A medical task.', 'That a private draft is already live.'],
            ['What information do I need for one visit?', 'Can I ask for a two-hour visit?', 'What timezone is shown?'],
            ['Set up weekly care.', 'Arrange 24/7 coverage.', 'Has someone applied?'],
            'Section 3 and CARE-REQUEST-005',
        ),
        $entry(
            'KB-CARE-003',
            'What a regular care request needs',
            'A regular care request needs the person receiving care, at least one kind of non-medical help, the address, one or more weekdays, a start time and visit length for every chosen day, and the first service date. Care may be ongoing or have an end date.',
            'family.new_care_request',
            ['Different recurring weekdays may have different times and durations.', 'Every selected weekday needs a start time and duration.', 'Care may be ongoing or use an end date.'],
            ['A missing weekday schedule.', 'That every day must use the same time.', 'Caregiver availability.'],
            ['What do I need for weekly care?', 'Can Monday and Friday use different times?', 'Can regular care be ongoing?'],
            ['I need just one visit.', 'I need 24/7 coverage.', 'Cancel my current request.'],
            'Section 3 and CARE-REQUEST-005',
        ),
        $entry(
            'KB-CARE-004',
            'Human help for 24/7 coverage',
            'Continuous day-and-night or 24/7 coverage is coordinated with LoLo Support. The assistant transfers the same conversation promptly and does not make you complete a long request intake first. It does not promise availability or a response time.',
            'support.center',
            ['A 24/7 need transfers to LoLo Support.', 'The same canonical conversation continues.', 'A 24/7 need alone is not automatically an emergency.'],
            ['Queue position, wait time, business hours, or staffing availability.', 'A one-time or recurring request as a substitute for continuous coverage.', 'That support has arranged coverage.'],
            ['I need round-the-clock help.', 'Can you arrange all-day-and-night care?', 'Is 24/7 care an emergency?'],
            ['I need an eight-hour visit.', 'Where are my care requests?', 'Submit weekly care for me.'],
            'Section 1 and CARE-24H-001',
            ['family'],
            'support_answers_v1',
            'escalation',
        ),
        $entry(
            'KB-CARE-005',
            'Non-medical care and emergency boundaries',
            'LoLo supports non-medical care. It cannot give medical advice or arrange a clinical procedure through the automated request flow. If someone is in immediate danger, call 911 now; LoLo is not an emergency service. The conversation is then transferred to LoLo Support.',
            'support.center',
            ['LoLo supports non-medical care.', 'Immediate danger requires calling 911 now.', 'Medical or clinical requests transfer to LoLo Support.'],
            ['Medical diagnosis or advice.', 'That LoLo contacted emergency services.', 'That 24/7 care alone is an emergency.'],
            ['Can a caregiver give medical advice?', 'Someone cannot breathe.', 'I need an injection.'],
            ['Where is my dashboard?', 'How do recurring visits work?', 'Change my email.'],
            'Sections 1 and 3',
            ['family', 'caregiver'],
            'support_answers_v1',
            'escalation',
        ),
        $entry(
            'KB-CARE-006',
            'Approved hourly price - publication held',
            'The approved platform price is $30 per hour for care. This answer remains unavailable to the production assistant until the pricing and payment implementation is reconciled with that approved truth.',
            'support.center',
            ['The approved business price is $30 per hour.', 'Production assistant pricing is held until authoritative implementation reconciliation.'],
            ['A production total while the hold is active.', 'Current payment, payout, fee, authorization, or override state.', 'Caregiver availability.'],
            ['How much does care cost?', 'What is the hourly rate?', 'Calculate the cost of care.'],
            ['Create my request.', 'Was my card charged?', 'What is the support queue?'],
            'Sections 7 and 14',
            ['family'],
            'pricing_answers_held_v1',
            'product_fact',
        ),
        $entry(
            'KB-CARE-007',
            'A published request is not a hired caregiver',
            'Publishing makes the request live so eligible caregivers can see it. It does not mean a caregiver has applied, been selected, or been hired. Current application or hiring status must come from the request itself, not from a general support answer.',
            'family.care_requests',
            ['A live request is visible to eligible caregivers.', 'Publication does not hire a caregiver.', 'Current application and hiring state require authorized live data.'],
            ['That a specific caregiver saw, applied to, or accepted a request.', 'That coverage is available.', 'A booking that is not in authoritative context.'],
            ['What does live mean?', 'Did publishing hire someone?', 'Who can see my request?'],
            ['Hire this caregiver.', 'Change my weekly schedule.', 'What is the hourly price?'],
            'Sections 5 and 7',
            ['family'],
            'support_answers_v1',
            'product_fact',
        ),
        $entry(
            'KB-CARE-008',
            'Payment is not authorized when a request is published',
            'Publishing a care request does not authorize or capture payment. Payment authorization occurs later in the normal hiring and booking flow. Current payment state always requires authorized live account data.',
            'family.care_requests',
            ['Request publication creates no payment authorization or capture.', 'Payment authorization occurs later in the normal hire and booking flow.'],
            ['That a card is valid, charged, authorized, refunded, or selected.', 'Any payment amount or fee from KB memory.', 'A payment-method change.'],
            ['Will publishing charge my card?', 'When is payment authorized?', 'Does a live request mean I paid?'],
            ['Change my card.', 'Refund this booking.', 'Tell me another family payment status.'],
            'Sections 5 and CARE-REQUEST-007',
            ['family'],
            'support_answers_v1',
            'product_fact',
        ),
        $entry(
            'KB-CARE-009',
            'Reusing saved care information safely',
            'The assistant may show saved recipients and the household address that the signed-in Family user is currently allowed to use. The user can review or change every reused value. A previous request is reused only after an explicit request such as same as last time.',
            'family.new_care_request',
            ['Authorized saved recipient and household information may be proposed.', 'Every reused material value appears in the recap.', 'Previous-request reuse requires an explicit request.'],
            ['Another Family account record.', 'A guessed profile or request ID.', 'That saved information is still valid without current authorization.'],
            ['Can you use my saved address?', 'Use the same as last time.', 'Can I change a saved recipient in the recap?'],
            ['Show another family address.', 'Guess which recipient I mean.', 'Reuse an old request without asking.'],
            'Section 4 and CARE-CONTEXT-001',
        ),
        $entry(
            'KB-CARE-010',
            'Seven-day private drafts and confirmation renewal',
            'A private chat-created request draft is saved for seven days after the last valid update. It is not visible to caregivers. A recap confirmation lasts 30 minutes. If it expires, Review and confirm again reloads the current draft and shows a fresh recap without retyping valid details.',
            'family.new_care_request',
            ['Private drafts last seven days after the last valid update.', 'Drafts are not marketplace-visible.', 'Confirmation lasts 30 minutes.', 'Expired confirmation can be renewed from the saved draft.'],
            ['That a draft is a live request.', 'That an expired confirmation may publish later.', 'That logout or access loss preserves commit authority.'],
            ['How long is my draft saved?', 'What if confirmation expires?', 'Can caregivers see my draft?'],
            ['Publish without confirmation.', 'Restore a draft after Family access ends.', 'Show another member private draft.'],
            'Sections 2 and 4',
        ),
        $entry(
            'KB-CARE-011',
            'Modifying and confirming a request',
            'The recap shows who needs care, tasks, schedule, Eastern Time, address, instructions, and response preference. Choose Modify something to change a section. Choose Confirm and create request only after every detail is correct. Any material change invalidates the earlier confirmation and creates a fresh recap.',
            'family.new_care_request',
            ['The recap is server-rendered from the normalized draft.', 'Material changes invalidate earlier confirmation.', 'The confirm button is required for publication.'],
            ['Conversational yes as initial commit authority.', 'A client-edited recap as authoritative.', 'A price while the pricing hold is active.'],
            ['How do I change the recap?', 'What does confirm do?', 'Why must I review again after a change?'],
            ['Publish my unreviewed notes.', 'Skip confirmation.', 'Change a caregiver payout.'],
            'Section 3 and CARE-REQUEST-006',
        ),
        $entry(
            'KB-CARE-012',
            'What happens after publication',
            'After confirmed publication, the request is live and eligible caregivers can see it. The receipt includes View request. No caregiver is hired and no payment is authorized at publication. Use the request page for current applications, hiring, and request status.',
            'family.care_requests',
            ['The authoritative receipt says the request is live.', 'Eligible caregivers can see an open request.', 'View request opens the authoritative request.', 'No hire or payment authorization occurs at publication.'],
            ['That a caregiver will apply.', 'A response time or availability promise.', 'Current application, hire, booking, or payment state without authorized data.'],
            ['What happens after I publish?', 'Where can I view the live request?', 'Does publication hire someone?'],
            ['Guarantee someone will apply.', 'Tell me queue status.', 'Approve a timesheet.'],
            'Sections 5 and CARE-REQUEST-007',
            ['family'],
            'support_answers_v1',
            'product_fact',
        ),
    ],
];
