<?php

$reviewBy = '2026-11-20';

$sources = [
    'SRC-B67-MATCH-001' => ['Current caregiver marketplace implementation', 'Family-visible search, profile, invitation, application, conversation, and hiring behavior.'],
    'SRC-B67-VISIT-001' => ['Current visit and submitted-hours implementation', 'Booking, schedule change, cancellation, check-in, completion, correction, payment, dispute, and review behavior.'],
    'SRC-B67-REGULAR-001' => ['Current recurring-care implementation', 'Offer, counter, generated visit, schedule change, extra visit, skip, pause, resume, end, and payment behavior.'],
    'SRC-B67-CONFIRM-001' => ['AI Support material-action contract', 'Exact actor/account binding, visible recap, explicit confirmation, stale-state denial, idempotency, execution, and verified receipt.'],
    'SRC-B67-BOUNDARY-001' => ['AI Support Family safety and authority policy', 'Family-visible facts only, no availability promise, no subjective caregiver selection, urgent-safety response, and human exception paths.'],
    'SRC-B67-PRICE-001' => ['Approved LoLo marketplace pricing truth', 'Family care is $30/hour plus a $1/hour processing fee; caregiver gross is $27/hour minus actual Stripe processing fees on successful charges.'],
];

$definitions = [
    ['MATCH-001', 'Find and browse caregivers', 'Families can browse active marketplace caregivers and search by the filters the app exposes. Search results are possible matches, not a promise that a caregiver will accept or be available. The assistant can open Find Caregivers or the exact request’s caregiver responses when that request is known.', ['family.caregivers', 'family.request.applicants'], range(1, 3), ['The app exposes caregiver search and certification filters.', 'Search results do not guarantee acceptance or availability.'], ['A guaranteed match or response.', 'Private or unlisted caregiver data.'], ['Show me caregivers.', 'Find caregivers for my request.', 'Filter by verified certifications.'], ['Approve these hours.', 'Pause recurring care.'], ['SRC-B67-MATCH-001', 'SRC-B67-BOUNDARY-001']],
    ['MATCH-002', 'Caregiver profile facts and recommendations', 'The assistant may summarize only facts visible on the caregiver profile, such as name, service area, stated experience, ratings and review count, reliability shown by LoLo, badges, certifications and whether a credential is verified or self-reported. It does not invent a recommendation reason or decide who is safest or best.', ['family.request.applicants'], range(4, 7), ['Only Family-visible profile and request-fit facts may be compared.', 'Verified and self-reported credentials must be distinguished.'], ['A hidden ranking or recommendation reason.', 'A clinical, safety, or character judgment.'], ['Compare the caregiver profiles.', 'What does this rating mean?', 'Why is this caregiver shown?'], ['Send Amy a message.', 'Cancel tomorrow’s visit.'], ['SRC-B67-MATCH-001', 'SRC-B67-BOUNDARY-001']],
    ['MATCH-003', 'Invite or reinvite a caregiver', 'An invitation can be sent only for an authorized open request that has no hired caregiver and, for one-time care, is still in the future. The assistant prepares the exact request, caregiver, optional message, and whether this is a reinvitation; it sends only after the Family confirms the recap.', ['family.request.applicants'], range(8, 10), ['Invitation eligibility comes from the current request, caregiver, application, and prior-invitation state.', 'A sent invitation is not an acceptance or hire.'], ['That a past or filled request is eligible.', 'That the caregiver will accept.'], ['Invite Amy to my Sunday request.', 'Send this caregiver an invitation.', 'Invite her again.'], ['Hire this applicant.', 'Show submitted hours.'], ['SRC-B67-MATCH-001', 'SRC-B67-CONFIRM-001']],
    ['MATCH-004', 'Invitation status and cancellation', 'The assistant can read whether an invitation is pending, accepted, declined, expired, cancelled, or replaced by a caregiver reply. A still-pending invitation may be cancelled only after a clear recap and confirmation. Cancellation does not alter the care request itself.', ['family.request.applicants'], range(11, 12), ['Invitation status is read from the authoritative invitation record.', 'Only a pending invitation can be cancelled.'], ['That an invitation was read.', 'That cancelling an invitation withdraws the request.'], ['Did Amy accept my invitation?', 'Cancel the pending invitation.'], ['Cancel the whole request.', 'End recurring care.'], ['SRC-B67-MATCH-001', 'SRC-B67-CONFIRM-001']],
    ['MATCH-005', 'Applicants, comparison, shortlist, and rejection', 'The assistant can list active applicants and compare only the same Family-visible facts shown in the app. Saving an applicant for follow-up or declining an applicant changes only that application state. The Family remains responsible for choosing; each change requires confirmation.', ['family.request.applicants'], range(13, 16), ['Applicant status and visible comparison facts may be read.', 'Shortlisting and rejection require exact application selection and confirmation.'], ['A best-caregiver decision.', 'A guarantee about availability, quality, or safety.'], ['Who applied?', 'Compare my applicants.', 'Save Amy for later.', 'Decline this applicant.'], ['Why did my card fail?', 'Create a profile.'], ['SRC-B67-MATCH-001', 'SRC-B67-CONFIRM-001', 'SRC-B67-BOUNDARY-001']],
    ['MATCH-006', 'Applicant conversations and messages', 'The assistant can open an authorized applicant or hired-caregiver conversation. It may prepare an exact message and send it only after the Family reviews and confirms. LoLo may show that a message was sent and the last-message state; it must not claim the caregiver read it unless the product has an authoritative read record.', ['family.messages', 'family.message'], range(17, 19), ['Authorized conversations and sent-message records may be read.', 'A prepared message is not sent until confirmation.'], ['That a recipient read or agreed with a message.', 'A conversation outside the Family Account.'], ['Open Amy’s conversation.', 'Tell Amy we will be five minutes late.', 'Was my message read?'], ['Reject the applicant.', 'Approve a counteroffer.'], ['SRC-B67-MATCH-001', 'SRC-B67-CONFIRM-001']],
    ['MATCH-007', 'Hiring an applicant', 'Hiring selects one eligible applicant, closes other active applications, creates the booking or recurring-care plan, and starts the existing payment-authorization workflow. The assistant shows the caregiver, request, schedule, rate, payment consequence, and affected applicants before confirmation, then verifies the resulting booking or plan.', ['family.request.applicants', 'family.request.visit'], range(20, 22), ['The request must still be open and the application eligible.', 'Hiring creates care and can require secure card confirmation.', 'All care is $30/hour to the Family.'], ['That hiring is complete before the booking or plan is verified.', 'That a payment authorization succeeded without authoritative state.'], ['Hire Amy for request 42.', 'What happens if I hire her?', 'Why is hiring blocked?'], ['Invite a new caregiver.', 'Report a no-show.'], ['SRC-B67-MATCH-001', 'SRC-B67-CONFIRM-001', 'SRC-B67-PRICE-001']],
    ['MATCH-008', 'Choosing between caregivers', 'The assistant can organize comparable Family-visible facts and explain what each field means, but the Family makes the final caregiver choice. It does not make a subjective safety, clinical, personality, or “best caregiver” decision.', ['family.request.applicants'], [23], ['The Family makes the final selection.', 'The assistant may summarize comparable visible facts.'], ['Who is safest, best, or guaranteed to work out.', 'An unstated preference or hidden score.'], ['Which caregiver should I choose?', 'Help me compare Amy and Barbara.'], ['Approve the timesheet.', 'Update my card.'], ['SRC-B67-MATCH-001', 'SRC-B67-BOUNDARY-001']],
    ['MATCH-009', 'Profile or credential concerns', 'Misleading profile information, credential concerns, and requests to block future contact require human review. The assistant preserves the current conversation and authorized caregiver/request context when transferring; it does not decide that a credential is false.', ['support.center'], [24, 25], ['Credential and blocking concerns transfer to a person.', 'The transcript and safe context are preserved.'], ['That a credential is fraudulent.', 'That a caregiver was blocked or disciplined.'], ['This certification looks wrong.', 'I do not want this caregiver contacting me again.'], ['Invite the caregiver.', 'View my next visit.'], ['SRC-B67-MATCH-001', 'SRC-B67-BOUNDARY-001']],

    ['VISIT-001', 'Next visit details and status', 'The assistant can read the next or current authorized visit’s caregiver, date, time, duration, location summary, requested tasks, instructions, and current booking/check-in state. It shows only the signed-in Family Account’s visit and offers the exact Visit details page.', ['family.request.visit'], range(1, 3), ['Authorized booking schedule, task, location-summary, and status fields may be read.', 'The current state must be refreshed before stating it.'], ['Another Family Account’s visit.', 'An arrival or completion that the booking state does not show.'], ['When is my next visit?', 'Show today’s visit details.', 'What is the visit status?'], ['Compare applicants.', 'Pause recurring care.'], ['SRC-B67-VISIT-001']],
    ['VISIT-002', 'Message the hired caregiver', 'An authorized Family member may open the hired caregiver conversation. The assistant can prepare a message tied to the exact conversation, show it for review, and send it only after explicit confirmation.', ['family.message'], [4], ['The message is bound to an authorized conversation and exact text.', 'Sending requires confirmation.'], ['That the caregiver read, accepted, or acted on the message.'], ['Tell my caregiver the door code changed.', 'Message the caregiver for today’s visit.'], ['Hire an applicant.', 'Approve hours.'], ['SRC-B67-MATCH-001', 'SRC-B67-CONFIRM-001']],
    ['VISIT-003', 'Visit reschedule or cancellation request', 'Before check-in, a Family can request a reschedule or cancellation from the caregiver. The assistant prepares the reason and any proposed future start and end, shows the current and proposed schedule, and sends only after confirmation. The current visit remains unchanged until a request is accepted.', ['family.request.visit'], [5, 6], ['A pending change request does not alter the current schedule.', 'Reschedule dates must be in the future and end after start.'], ['That the caregiver accepted a requested change.', 'That an active or completed visit can use the same workflow.'], ['Ask to move Friday’s visit to Saturday.', 'Request cancellation of tomorrow’s visit.'], ['Cancel it immediately.', 'Review submitted hours.'], ['SRC-B67-VISIT-001', 'SRC-B67-CONFIRM-001']],
    ['VISIT-004', 'Direct visit cancellation and late-cancellation impact', 'A scheduled visit may be cancelled directly when the existing visit workflow allows it. The recap shows the exact visit, reason, whether it is inside the platform’s late-cancellation window, and that payment authorization will be released or reconciled by the existing service. Nothing changes until confirmation.', ['family.request.visit'], [7, 8], ['Only a scheduled visit is directly cancellable.', 'The current late-cancellation result is computed by the booking policy.'], ['A fee, refund, or penalty not present in the authoritative record.', 'That the caregiver agreed to the cancellation.'], ['Cancel tomorrow’s scheduled visit.', 'Will this be a late cancellation?'], ['End the recurring-care plan.', 'Cancel an invitation.'], ['SRC-B67-VISIT-001', 'SRC-B67-CONFIRM-001']],
    ['VISIT-005', 'Caregiver schedule-change decision', 'When the caregiver has submitted a pending visit change, the assistant can recap the current schedule, proposed schedule, reason, and effect. It can take the Family to the exact Accept or Reject controls. The current schedule remains in effect until a decision is recorded.', ['family.request.visit_issue'], range(9, 11), ['Only a current pending caregiver request is presented.', 'The exact current and proposed values are compared.'], ['That a pending change is already accepted.', 'A schedule not present in the request.'], ['What change did the caregiver ask for?', 'Accept the caregiver’s reschedule.', 'Reject this change.'], ['Send an invitation.', 'Review a recurring-care counter.'], ['SRC-B67-VISIT-001', 'SRC-B67-CONFIRM-001']],
    ['VISIT-006', 'Check-in, lateness, and no-show', 'The assistant can explain the authoritative check-in/check-out state. A caregiver no-show can be marked only for a still-scheduled visit at least 30 minutes after scheduled start, after a strong confirmation. Being late before that point is handled as a message or human support request, not a no-show claim.', ['family.request.visit'], range(12, 14), ['No-show eligibility begins 30 minutes after scheduled start while the visit remains scheduled.', 'Marking no-show cancels the visit and affects the preserved reliability record.'], ['That lateness automatically means no-show.', 'A no-show before the eligibility time.'], ['Did the caregiver check in?', 'My caregiver is late.', 'Mark the caregiver no-show.'], ['Reject an applicant.', 'Pause next month’s care.'], ['SRC-B67-VISIT-001', 'SRC-B67-CONFIRM-001']],
    ['VISIT-007', 'Visit safety incident and support', 'Immediate danger requires calling 911 first. Other safety incidents, serious visit problems, and record disputes transfer to a person in the same support conversation with the authorized booking context preserved. The assistant does not make a finding of fault or promise an outcome or response time.', ['support.center'], range(15, 16), ['Immediate danger gets emergency instructions before transfer.', 'Non-emergency incidents transfer with booking context.'], ['Fault, liability, discipline, or resolution timing.', 'Clinical advice.'], ['Report a safety incident.', 'I need help with this visit.'], ['Approve hours.', 'Invite Amy.'], ['SRC-B67-VISIT-001', 'SRC-B67-BOUNDARY-001']],
    ['VISIT-008', 'Marking a visit complete', 'For a visit in progress or paused, the Family may mark it complete. The assistant shows the exact booking and state, explains that this records completion and submitted-hours timing, and executes only after confirmation. It then verifies the booking state.', ['family.request.visit'], [17], ['Only an in-progress or paused visit can be marked complete by this action.', 'Completion is verified from the booking record.'], ['That payment or a review is complete at the same time.'], ['The caregiver left; mark the visit complete.', 'Tell the app this visit ended.'], ['Cancel a pending invitation.', 'Accept a counteroffer.'], ['SRC-B67-VISIT-001', 'SRC-B67-CONFIRM-001']],
    ['VISIT-009', 'Submitted hours and payment approval', 'The assistant can recap submitted start, end, breaks, duration, completed-task marks, notes, scheduled-versus-worked difference, and current payment state. Confirming submitted hours may capture the authorized payment. The exact duration and financial effect are shown before confirmation, and secure card action may still be required.', ['family.request.timesheet', 'family.request.payment_attention'], range(18, 20), ['Submitted-hours facts and Family-visible payment state come from the exact booking.', 'Payment approval requires explicit confirmation and authoritative payment processing.'], ['A charge succeeded before the payment state is verified.', 'Unsubmitted or inferred hours.'], ['Show the submitted hours.', 'Approve these hours and payment.', 'What is a timesheet review?'], ['Compare caregivers.', 'Skip a regular visit.'], ['SRC-B67-VISIT-001', 'SRC-B67-CONFIRM-001', 'SRC-B67-PRICE-001']],
    ['VISIT-010', 'Questions and corrections to submitted time', 'The assistant can prepare a clear request for corrected time or other changes. A caregiver-submitted correction is shown as original versus proposed start, end, breaks, duration, and charge. Approving a correction may process a payment difference; requesting changes sends the stated reason without approving payment.', ['family.request.timesheet'], range(21, 26), ['The latest correction version and exact financial preview must remain current.', 'Approving and requesting changes are different explicit actions.'], ['That a correction was approved because it was prepared.', 'A payment amount not in the current preview.'], ['Ask the caregiver to correct the end time.', 'Review the proposed correction.', 'Approve the time correction.', 'Request changes to this correction.'], ['Invite a caregiver.', 'End recurring care.'], ['SRC-B67-VISIT-001', 'SRC-B67-CONFIRM-001']],
    ['VISIT-011', 'Time disputes and exceptional records', 'A time-correction escalation, post-care dispute, or request to alter a completed audit record transfers to human support with the exact booking and current correction context. Payment is not approved merely by opening or preparing the dispute.', ['support.center'], [27, 28, 29, 35], ['Current dispute status may be read.', 'Exceptional completed-record changes stay human-reviewed.'], ['A dispute outcome, refund, fault, or completion time.', 'That a preserved record was altered.'], ['Escalate this time correction.', 'Dispute the submitted hours.', 'What is my dispute status?', 'Correct the completed record.'], ['Leave a review.', 'Send a message.'], ['SRC-B67-VISIT-001', 'SRC-B67-BOUNDARY-001']],
    ['VISIT-012', 'Caregiver rating and review', 'After eligible care, the Family may provide a 1-to-5 star rating and optional review text. The assistant can prepare the exact rating and text, show a recap, and submit only after confirmation. Submitting can also confirm eligible completed care and process its authorized payment through the existing workflow.', ['family.request.visit'], [30, 31], ['Rating must be an explicit integer from 1 to 5.', 'Review text is optional and shown before submission.'], ['A rating the user did not state.', 'That review editing or removal is available without a defined policy.'], ['Leave Amy five stars and say she was patient.', 'Can I edit my review?'], ['Cancel the visit.', 'Compare applicants.'], ['SRC-B67-VISIT-001', 'SRC-B67-CONFIRM-001']],
    ['VISIT-013', 'Rebook or move into recurring care', 'The Family can reuse a successful care relationship for another one-time request or a recurring-care setup. A rebook is a new request with its own future schedule and invitation; it does not silently reuse an old payment or claim the caregiver accepted. Recurring care uses a separate offer and acceptance lifecycle.', ['family.request.overview', 'family.care_arrangements'], range(32, 33), ['Rebooking creates a distinct request and invitation.', 'Recurring care requires a separate schedule and caregiver acceptance.'], ['That the caregiver is booked before accepting.', 'An unstated new date or schedule.'], ['Book Amy again next Sunday.', 'Turn this into weekly care.'], ['Approve the old timesheet.', 'Cancel a card.'], ['SRC-B67-VISIT-001', 'SRC-B67-REGULAR-001', 'SRC-B67-CONFIRM-001']],
    ['VISIT-014', 'Payment effect of hours approval', 'Approving hours confirms the worked time and lets LoLo use the existing payment authorization or request secure card action. Family care is $30/hour plus a $1/hour processing fee. Caregiver gross is $27/hour minus actual Stripe processing fees recorded on successful Family charges. The current booking and payment record—not a guess—determines the exact amount and outcome.', ['family.request.timesheet', 'family.request.payment_attention'], [34], ['Exact financial state comes from the booking payment record.', 'Family total is $31 per worked hour; caregiver net is finalized from actual Stripe processing fees.'], ['That payment succeeded without a captured or transferred state.', 'Fees not in governed truth.'], ['Does approving hours charge me?', 'How much will these hours cost?'], ['Invite Amy.', 'Pause recurring care.'], ['SRC-B67-VISIT-001', 'SRC-B67-PRICE-001']],

    ['REGULAR-001', 'Recurring-care plan list and status', 'The assistant can list the signed-in Family Account’s pending, countered, active, payment-attention, paused, ended, declined, or expired plans and open an exact plan. It may read the next and later generated visits without claiming ungenerated visits exist.', ['family.care_arrangements', 'family.regular_care.attention'], [1, 9, 10], ['Plan and generated-visit state are authoritative.', 'Only generated visits are described as booked.'], ['A visit that has not been generated.', 'Another Family Account’s plan.'], ['Show my recurring-care plans.', 'When is the next weekly visit?', 'Show later visits.'], ['Compare applicants.', 'Dispute one-time hours.'], ['SRC-B67-REGULAR-001']],
    ['REGULAR-002', 'Set up and send a recurring-care offer', 'Recurring care with a known caregiver uses an authorized recurring request or eligible prior care, weekly per-day times, start and optional end, care details, and an optional message. The assistant prepares a complete offer recap and sends only after confirmation. The caregiver must accept; the offer itself does not book all future visits.', ['family.care_arrangements'], range(2, 6), ['The exact schedule and message are shown before sending.', 'The caregiver must accept the offer.', 'A Family payment method is required by the existing workflow.'], ['That an offer is accepted or all future visits are booked.', 'A schedule or care detail the Family did not confirm.'], ['Set up weekly care with Amy.', 'Use the old request details.', 'Add a message to the recurring-care offer.', 'Why is a card required?'], ['Cancel tomorrow’s one-time visit.', 'Reject an applicant.'], ['SRC-B67-REGULAR-001', 'SRC-B67-CONFIRM-001', 'SRC-B67-PRICE-001']],
    ['REGULAR-003', 'Caregiver counteroffer', 'A counteroffer is the caregiver’s proposed schedule or start change. The assistant compares the original and countered schedule, start, and note. Accepting it changes the plan and may create the next visit, so it requires a material recap and explicit confirmation.', ['family.regular_care.attention'], range(7, 8), ['Original and counter schedules are compared from the plan.', 'Acceptance requires the plan to remain countered.'], ['That the counter is already accepted.', 'A caregiver reason not present in the note.'], ['What did Amy counter?', 'Accept the recurring-care counteroffer.'], ['Accept a one-time visit change.', 'Invite Amy.'], ['SRC-B67-REGULAR-001', 'SRC-B67-CONFIRM-001']],
    ['REGULAR-004', 'Skip or add a future recurring-care visit', 'The Family may skip one specific upcoming scheduled plan visit or request one extra future visit. The recap shows the exact date/time, duration, and any late-cancellation result. An extra visit is a request until the caregiver accepts; skipping one visit does not end the regular schedule.', ['family.regular_care.attention'], range(11, 12), ['Skip applies to one authorized scheduled plan booking.', 'Extra-visit start/end must be future and non-overlapping.'], ['That skipping ends the plan.', 'That the caregiver accepted an extra-visit request.'], ['Skip next Tuesday’s visit.', 'Add an extra visit Friday at 2 PM for two hours.'], ['End the whole plan.', 'Approve completed extra care.'], ['SRC-B67-REGULAR-001', 'SRC-B67-CONFIRM-001']],
    ['REGULAR-005', 'Completed extra visit review', 'For a caregiver-reported completed extra visit, the assistant can recap the date, time, duration, notes, reason, and current financial preview. Approval can process payment; requesting changes sends a reason without payment; disputes and exceptional payment cases transfer for human review.', ['family.regular_care.attention'], range(13, 18), ['Only the current latest report is actionable.', 'Approval, request changes, retry, dispute, and escalation have distinct outcomes.'], ['That a disputed report was paid.', 'That a secure payment retry completed in chat.'], ['Review the completed extra visit.', 'Approve and pay it.', 'Ask Amy to correct it.', 'Dispute this extra visit.', 'Retry the payment.'], ['Invite an applicant.', 'Change my care profile.'], ['SRC-B67-REGULAR-001', 'SRC-B67-CONFIRM-001', 'SRC-B67-BOUNDARY-001']],
    ['REGULAR-006', 'Future recurring-care schedule change', 'A schedule-change request contains the current schedule, proposed weekly per-day schedule, effective future date, optional end date, and note. Current visits remain unchanged until the caregiver accepts. The assistant sends only after the Family confirms the comparison.', ['family.regular_care.attention'], [19], ['The exact old/new schedule and effective date are shown.', 'Current visits remain until acceptance.'], ['That a submitted schedule request is accepted.', 'A past effective date.'], ['Change weekly care to Mondays and Thursdays at 9.', 'Ask for a new regular schedule next month.'], ['Move a one-time visit.', 'Update a profile.'], ['SRC-B67-REGULAR-001', 'SRC-B67-CONFIRM-001']],
    ['REGULAR-007', 'Pause, resume, or end recurring care', 'Pausing recurring care suppresses affected future generated visits from the selected date and may include a return date. Resuming restarts generation from current plan rules. Ending stops future plan generation; the Family explicitly chooses whether the next already-confirmed visit is also cancelled. Each action requires a strong impact recap and confirmation.', ['family.regular_care.attention'], range(20, 23), ['Pause, resume, and end use the current plan state and schedule version.', 'Ending and cancelling the next visit are separate choices.'], ['That an already-completed visit is changed.', 'That ending automatically cancels the next confirmed visit without the explicit choice.'], ['Pause recurring care until September.', 'Resume my weekly care.', 'End recurring care.', 'End it and cancel the next visit.'], ['Cancel a pending applicant invitation.', 'Approve one-time hours.'], ['SRC-B67-REGULAR-001', 'SRC-B67-CONFIRM-001']],
    ['REGULAR-008', 'Recurring-care history and caregiver messages', 'Recurring-care history and Family-visible payments remain available through Care history. The assistant can open an authorized conversation with the recurring caregiver and prepare a message for explicit confirmation. It never claims a message was read without authoritative evidence.', ['family.care_history', 'family.message'], range(24, 25), ['Authorized plan history and conversation records may be read.', 'Prepared messages require confirmation.'], ['Caregiver payout details.', 'A message-read claim without an authoritative read record.'], ['Show recurring-care history.', 'Message my recurring caregiver.'], ['Replace the caregiver.', 'Delete a profile.'], ['SRC-B67-REGULAR-001', 'SRC-B67-MATCH-001']],
    ['REGULAR-009', 'Replace a recurring-care caregiver', 'Replacing the caregiver on a live recurring-care plan does not yet have one deterministic self-service workflow. The assistant transfers the same support conversation with the current plan context and does not end the plan, cancel visits, or invite a replacement automatically.', ['support.center'], [26], ['Replacement stays human-led until a product workflow is defined.', 'No plan state changes before human handling.'], ['That a replacement is selected or available.', 'That the existing plan or visits were cancelled.'], ['Replace my recurring caregiver.', 'I need someone else for weekly care.'], ['Pause recurring care.', 'Invite a caregiver to an open request.'], ['SRC-B67-REGULAR-001', 'SRC-B67-BOUNDARY-001']],
];

$entry = static function (array $definition) use ($reviewBy, $sources): array {
    [$suffix, $title, $answer, $targets, $numbers, $mayState, $mustNotInfer, $matches, $noMatches, $sourceIds] = $definition;
    [$domain, $sequence] = explode('-', $suffix, 2);
    $stableId = 'KB-B67-'.$suffix;
    $intentDomain = $domain === 'MATCH' ? 'MATCH' : ($domain === 'VISIT' ? 'VISIT' : 'REGULAR');
    $intentIds = array_map(static fn (int $number): string => sprintf('FAM-%s-%03d', $intentDomain, $number), (array) $numbers);
    $prefix = str_replace('KB-', 'EVAL-KB-', $stableId);

    return [
        'stable_id' => $stableId,
        'intent_ids' => $intentIds,
        'type' => 'task_playbook',
        'title' => $title,
        'answer_body' => $answer,
        'sensitivity' => 'authenticated',
        'product_area' => match ($domain) {
            'MATCH' => 'Caregiver matching and hiring',
            'VISIT' => 'Visits and submitted hours',
            default => 'Recurring care',
        },
        'locale' => 'en-US',
        'roles' => ['family'],
        'membership_states' => ['active'],
        'route_target_ids' => array_values($targets),
        'capability_ids' => ['support_answers_v1', 'family_care_operations_v1'],
        'facts_may_state' => array_values($mayState),
        'facts_must_not_infer' => array_values(array_unique([
            ...$mustNotInfer,
            'Another Family Account’s caregiver, application, invitation, conversation, booking, plan, payment, or private note.',
            'That a prepared, displayed, or pending action succeeded.',
            'That a caregiver will respond, accept, arrive, or be available.',
        ])),
        'next_actions' => array_values(array_map(static fn (string $target): string => 'navigate:'.$target, array_filter($targets, static fn (string $target): bool => ! str_starts_with($target, 'support.')))),
        'escalation_conditions' => ['The user asks for a person.', 'The authorized current state does not expose a safe deterministic next step.', 'The issue requires a subjective safety, credential, dispute, exceptional-payment, or completed-record decision.'],
        'retrieval_examples_match' => array_values($matches),
        'retrieval_examples_no_match' => array_values($noMatches),
        'evaluation_ids' => [$prefix.'-POSITIVE', $prefix.'-BOUNDARY', $prefix.'-WRONG-ACCOUNT', $prefix.'-STALE-OR-UNAVAILABLE', $prefix.'-HANDOFF'],
        'change_note' => 'Batches 6 and 7 caregiver, visit, and regular-care knowledge approved for the exact two-user pilot.',
        'review_by' => $reviewBy,
        'expires_on' => null,
        'sources' => array_values(array_map(static fn (string $sourceId): array => [
            'source_id' => $sourceId,
            'title' => $sources[$sourceId][0],
            'url' => null,
            'section_anchor' => $sources[$sourceId][1],
            'fact_supported' => implode(' ', $mayState),
        ], $sourceIds)),
    ];
};

return [
    'version' => 'marketplace-care-kb-v1',
    'approved_at' => '2026-08-20',
    'entries' => array_map($entry, $definitions),
];
