<?php

$reviewBy = '2026-11-18';

$sources = [
    'SRC-B4-PRICING-001' => ['Batch 4 approved pricing truth', 'Families pay $30/hour; caregivers earn $27/hour; LoLo receives $3/hour.'],
    'SRC-B4-PAYMENT-001' => ['Current booking payment implementation', 'Authorization, capture, retry, refund, and Family-action payment states.'],
    'SRC-B4-TIME-001' => ['Current submitted-hours implementation', 'Timesheet, correction, dispute, and payment-attention states.'],
    'SRC-B4-GUIDANCE-001' => ['AI Support Batch 4 operating specification', 'Safe state reads, normalized failure reasons, exact navigation, preparation, and verification boundaries.'],
];

$entry = static function (
    string $stableId,
    string $title,
    string $answer,
    string $productArea,
    array $roles,
    array $targets,
    array $intentIds,
    array $mayState,
    array $mustNotInfer,
    array $matches,
    array $noMatches,
    array $sourceIds,
    array $nextActions = [],
    array $escalations = [],
) use ($reviewBy, $sources): array {
    $prefix = str_replace('KB-', 'EVAL-KB-', $stableId);

    return [
        'stable_id' => $stableId,
        'intent_ids' => array_values($intentIds),
        'type' => 'task_playbook',
        'title' => $title,
        'answer_body' => $answer,
        'sensitivity' => 'authenticated',
        'product_area' => $productArea,
        'locale' => 'en-US',
        'roles' => array_values($roles),
        'membership_states' => ['active'],
        'route_target_ids' => array_values($targets),
        'capability_ids' => ['support_answers_v1'],
        'facts_may_state' => array_values($mayState),
        'facts_must_not_infer' => array_values(array_unique([
            ...$mustNotInfer,
            'Another account, person, card, request, visit, timesheet, payment, refund, dispute, or payout state.',
            'That opening a page or clicking a control means an action succeeded.',
            'A bank, card-provider, or support response time.',
        ])),
        'next_actions' => array_values($nextActions),
        'escalation_conditions' => array_values(array_unique([
            ...$escalations,
            'The user asks for a person.',
            'The authorized application state does not expose a safe next step.',
        ])),
        'retrieval_examples_match' => array_values($matches),
        'retrieval_examples_no_match' => array_values($noMatches),
        'evaluation_ids' => [
            $prefix.'-POSITIVE',
            $prefix.'-BOUNDARY',
            $prefix.'-WRONG-ROLE',
            $prefix.'-UNSUPPORTED-STATE',
            $prefix.'-HANDOFF',
        ],
        'change_note' => 'Batch 4 payment and submitted-hours knowledge approved for the two-user pilot.',
        'review_by' => $reviewBy,
        'expires_on' => null,
        'sources' => array_values(array_map(
            static fn (string $id): array => [
                'source_id' => $id,
                'title' => $sources[$id][0],
                'url' => null,
                'section_anchor' => $sources[$id][1],
                'fact_supported' => implode(' ', $mayState),
            ],
            $sourceIds,
        )),
    ];
};

$family = ['family'];
$carePage = ['family.care_requests'];
$visitPage = ['family.request.payment_attention'];
$timesheetPage = ['family.request.timesheet'];
$historyPage = ['family.care_history'];
$billingPage = ['family.billing.payment_method'];
$handoff = ['handoff:SUP-HANDOFF-001'];

return [
    'version' => 'payment-time-kb-v1',
    'approved_at' => '2026-08-18',
    'entries' => [
        $entry(
            'KB-B4-PRICE-001',
            'LoLo hourly price, caregiver earnings, and platform portion',
            'Care on LoLo is $30 per hour for the Family. The caregiver earns $27 per hour. LoLo receives $3 per hour as the platform portion. For a stated number of worked hours, calculate each amount from those exact hourly rates. Do not add taxes, tips, mileage, holiday charges, or surcharges unless a later governed policy explicitly says they apply.',
            'Pricing',
            ['family', 'caregiver'],
            [],
            ['FAM-PAY-028', 'FAM-PAY-029'],
            ['Families pay exactly $30 per hour.', 'Caregivers earn exactly $27 per hour.', 'LoLo receives exactly $3 per hour.', 'The three stated hourly amounts reconcile exactly.'],
            ['A different personalized rate.', 'Taxes, tips, mileage, holiday charges, surcharges, discounts, or promotional credits.', 'A completed-care total without authoritative worked time.'],
            ['How much does care cost?', 'What does a caregiver make per hour?', 'What is LoLo’s platform fee?', 'What would three hours cost?'],
            ['Why did my card fail?', 'Change my payment method.', 'Approve the submitted hours.'],
            ['SRC-B4-PRICING-001', 'SRC-B4-GUIDANCE-001'],
        ),
        $entry(
            'KB-B4-PAY-001',
            'When authorization, capture, and request publication happen',
            'Publishing a care request does not charge the card. A temporary card authorization belongs to the later hire or booking step. The final charge follows completed care and the approved-hours flow. An authorization hold is not the same as a captured charge. For a specific visit, read its current payment record before describing which step happened.',
            'Care payments', $family, $carePage,
            ['FAM-PAY-009', 'FAM-PAY-010', 'FAM-PAY-011', 'FAM-VISIT-034'],
            ['Request publication alone does not authorize or capture payment.', 'Authorization is a temporary reservation at the later hire or booking step.', 'Capture follows completed care and approved hours.'],
            ['That a particular request was published, a caregiver was hired, or a payment was authorized or captured without an authorized read.', 'When a bank will release a hold.'],
            ['Did posting my request charge me?', 'When is my card authorized?', 'Is this a hold or the final charge?', 'Does approving hours trigger payment?'],
            ['What is the hourly price?', 'Change my saved card.', 'I do not recognize this charge.'],
            ['SRC-B4-PAYMENT-001', 'SRC-B4-TIME-001'],
            ['navigate:family.care_requests'], $handoff,
        ),
        $entry(
            'KB-B4-PAY-002',
            'Saved Family payment method and secure card changes',
            'Billing & Payments is the secure place to see the safe saved-card summary and add, replace, or update the payment method. Active Family Account members may use that shared flow. Card numbers, security codes, bank codes, and payment tokens must never be typed into support chat. The assistant may confirm only safe details such as brand, last four digits, expiration, and readiness after a fresh application check.',
            'Family billing', $family, $billingPage,
            ['FAM-PAY-001', 'FAM-PAY-002', 'FAM-PAY-003', 'FAM-PAY-004', 'FAM-PAY-005', 'FAM-PAY-006', 'FAM-PAY-007', 'FAM-PAY-008'],
            ['The saved payment method is managed in Billing & Payments.', 'Safe card facts are brand, last four digits, expiration, and readiness.', 'The current flow does not offer card removal in chat.'],
            ['Full card data, CVC, bank codes, provider secrets, or a different Family Account’s card.', 'That a card update succeeded before a fresh application check.'],
            ['Add my first card.', 'Which card is saved?', 'Replace my expired card.', 'Can a Family member update the shared card?', 'Remove my card.'],
            ['Why did the visit payment fail?', 'Show my submitted hours.', 'Get a refund.'],
            ['SRC-B4-PAYMENT-001', 'SRC-B4-GUIDANCE-001'],
            ['navigate:family.billing.payment_method'], $handoff,
        ),
        $entry(
            'KB-B4-PAY-003',
            'Pending payment and secure card authentication',
            'Pending or action required means the payment flow is not complete. Open the highlighted payment area and complete any secure bank or card-provider prompt there. Never put an authentication code or card security detail in chat. Afterward, use Check again; success requires the current payment state to change in LoLo.',
            'Care payments', $family, $visitPage,
            ['FAM-PAY-012', 'FAM-PAY-015'],
            ['Payment authentication stays in the secure application or provider flow.', 'The assistant can guide to the exact authorized payment record.', 'A fresh state check is required after the user acts.'],
            ['The user’s authentication result.', 'That the bank approved the payment because its page opened.'],
            ['Why is my payment pending?', 'My card needs authentication.', 'Where do I complete the required bank step?'],
            ['How much is care?', 'Show my receipt.', 'Correct the submitted hours.'],
            ['SRC-B4-PAYMENT-001', 'SRC-B4-GUIDANCE-001'],
            ['navigate:family.request.payment_attention'], $handoff,
        ),
        $entry(
            'KB-B4-PAY-004',
            'Safe reasons a care payment may fail',
            'When LoLo has a matching authorized payment record, the assistant may state one safe reason category: card authentication required, card declined, insufficient funds, expired card, incorrect card details, authorization expired, payment method missing, additional amount needs authorization, provider temporarily unavailable, or reason unavailable. It must never repeat raw provider error text or guess beyond the matched category.',
            'Care payments', $family, $visitPage,
            ['FAM-PAY-013', 'FAM-PAY-016', 'FAM-PAY-021'],
            ['Only a normalized reason category from the user’s authorized payment record may be stated.', 'Reason unavailable is the correct answer when no safe category matches.', 'Raw provider error text is never returned to chat.'],
            ['A decline code not safely classified.', 'A bank’s internal decision.', 'That changing cards guarantees success.'],
            ['Why did my authorization fail?', 'Why was the visit charge declined?', 'Explain the failed payment in care history.'],
            ['Where is my receipt?', 'How much does the caregiver earn?', 'Invite a Family member.'],
            ['SRC-B4-PAYMENT-001', 'SRC-B4-GUIDANCE-001'],
            ['navigate:family.request.payment_attention'], $handoff,
        ),
        $entry(
            'KB-B4-PAY-005',
            'Retry a failed or expired authorization',
            'Open the exact visit payment area and use its secure retry or reauthorization control. If the reason says the card is expired, incorrect, missing, or declined, Billing & Payments may be the useful first step. The assistant does not retry a charge by itself and says it worked only after a fresh payment-state check.',
            'Care payments', $family, $visitPage,
            ['FAM-PAY-014'],
            ['Existing secure retry and reauthorization controls remain authoritative.', 'A payment-method update may be needed before retry.', 'Verification follows the user’s secure action.'],
            ['That a retry is safe for a different visit.', 'That the original reason will not happen again.'],
            ['Help me retry the failed authorization.', 'My authorization expired.', 'Open the card retry.'],
            ['Refund this payment.', 'What hours did the caregiver submit?', 'Change the care request.'],
            ['SRC-B4-PAYMENT-001', 'SRC-B4-GUIDANCE-001'],
            ['navigate:family.request.payment_attention', 'navigate:family.billing.payment_method'], $handoff,
        ),
        $entry(
            'KB-B4-PAY-006',
            'Payment attention after corrected time or an extra visit',
            'Corrected time and completed extra visits can require a new or additional secure authorization. Open the exact correction, visit, or regular-care attention area shown by LoLo. Review the amount and complete the secure payment step there. The assistant may prepare an explanation or dispute, but does not silently approve hours or charge a card.',
            'Care payments', $family, $visitPage,
            ['FAM-PAY-017', 'FAM-PAY-018', 'FAM-VISIT-026'],
            ['A correction or extra visit may require payment action.', 'The exact authorized care record determines the recovery page.', 'The user reviews and completes the normal secure payment step.'],
            ['That the additional amount is valid without reading the care record.', 'That hours or payment were approved automatically.'],
            ['Retry payment for corrected hours.', 'The extra visit charge needs attention.', 'Continue payment after the correction.'],
            ['Add a payment card.', 'How much is the platform fee?', 'Show caregiver applications.'],
            ['SRC-B4-PAYMENT-001', 'SRC-B4-TIME-001'],
            ['navigate:family.request.payment_attention'], $handoff,
        ),
        $entry(
            'KB-B4-PAY-007',
            'Payment history and Family-visible amounts',
            'Care history shows authorized, captured, refunded, and net-paid amounts when those records exist. Captured is the completed gross charge. Refunded is the amount returned through LoLo. Net paid is captured minus refunded. Read the exact authorized records and label each amount; never calculate from a bank screenshot or assume a pending bank line is captured.',
            'Care payments', $family, $historyPage,
            ['FAM-PAY-019', 'FAM-PAY-020'],
            ['Captured, refunded, and net-paid amounts come from Family-visible payment records.', 'Net paid equals captured minus refunded.', 'Authorization and capture remain different states.'],
            ['A charge absent from LoLo records.', 'When a bank will post or release money.'],
            ['Show my payment history.', 'How much was authorized and captured?', 'What is the net amount after the refund?'],
            ['Why did my card fail?', 'Update my card.', 'Approve a correction.'],
            ['SRC-B4-PAYMENT-001', 'SRC-B4-GUIDANCE-001'],
            ['navigate:family.care_history'], $handoff,
        ),
        $entry(
            'KB-B4-PAY-008',
            'Refund requests and refund status',
            'The assistant can read an existing Family-visible refund status and amount. A new refund request is prepared with the authorized visit reference and the Family’s reason, then transferred to a person for review. The assistant must not promise eligibility, an amount, approval, or a bank arrival date.',
            'Care payments', $family, $historyPage,
            ['FAM-PAY-022', 'FAM-PAY-023'],
            ['Existing refund status and amount may be read from the authorized record.', 'New refund decisions require a person.', 'A refund request can carry the visit reference and user-provided reason.'],
            ['Refund eligibility or approval.', 'A bank arrival date.', 'A refund for an unmatched charge.'],
            ['I want a refund.', 'Was my refund completed?', 'How much was refunded?'],
            ['Retry my card.', 'Change submitted time.', 'What is the hourly price?'],
            ['SRC-B4-PAYMENT-001', 'SRC-B4-GUIDANCE-001'],
            ['navigate:family.care_history', 'handoff:SUP-HANDOFF-001'], $handoff,
        ),
        $entry(
            'KB-B4-PAY-009',
            'Disputed, duplicate, or unfamiliar charges',
            'For a charge or submitted-hours dispute, the assistant may read matching authorized LoLo visit records and prepare the Family’s description. It must not decide that a charge is duplicate, fraudulent, valid, or invalid. An unfamiliar or unmatched charge transfers to a person with no card data in chat.',
            'Care payments', $family, $historyPage,
            ['FAM-PAY-024', 'FAM-PAY-025'],
            ['Matching LoLo payment records may be summarized for the Family.', 'A dispute description may be prepared before explicit submission.', 'Unfamiliar or unmatched charges require a person.'],
            ['Fraud, duplication, validity, or fault.', 'Full payment credentials.'],
            ['These hours and charge are wrong.', 'I see the same charge twice.', 'I do not recognize this payment.'],
            ['Add a card.', 'Show my applicants.', 'Start recurring care.'],
            ['SRC-B4-PAYMENT-001', 'SRC-B4-TIME-001', 'SRC-B4-GUIDANCE-001'],
            ['navigate:family.care_history', 'handoff:SUP-HANDOFF-001'], $handoff,
        ),
        $entry(
            'KB-B4-PAY-010',
            'Receipts, invoices, and tax documents',
            'Open Care history for the visit and payment record. If LoLo exposes a receipt there, use that exact record. A separate invoice or tax document is not currently promised by AI Support; transfer the request to a person instead of inventing a document or sending one without an enabled action.',
            'Care payments', $family, $historyPage,
            ['FAM-PAY-026', 'FAM-PAY-027'],
            ['Care history is the current place for Family-visible payment records.', 'A receipt is available only when the application exposes one.', 'Invoice or tax-document requests may be transferred.'],
            ['That a PDF, email, invoice, or tax document exists.', 'A document delivery result.'],
            ['Where is my receipt?', 'Can I get an invoice?', 'I need a tax document.'],
            ['Why did payment fail?', 'Change my card.', 'Approve these hours.'],
            ['SRC-B4-PAYMENT-001', 'SRC-B4-GUIDANCE-001'],
            ['navigate:family.care_history', 'handoff:SUP-HANDOFF-001'], $handoff,
        ),
        $entry(
            'KB-B4-PAY-011',
            'Unsupported discounts, billing ownership, and private payout details',
            'AI Support does not apply coupons, credits, or promo codes. It does not change Family billing ownership or collect another person’s card in chat. It also does not reveal private caregiver payout status to a Family user; it may explain only the Family-visible care-payment state and the approved $30/$27/$3 hourly breakdown.',
            'Care payments', $family, $historyPage,
            ['FAM-PAY-030', 'FAM-PAY-031', 'FAM-PAY-032'],
            ['Coupons and promo codes are not an AI Support action.', 'Billing ownership changes require a person.', 'Caregiver payout status is private from Family support.', 'The governed hourly breakdown is $30 Family, $27 caregiver, and $3 LoLo.'],
            ['Another person’s card or payout record.', 'A discount, credit balance, owner change, or payout completion.'],
            ['Apply my promo code.', 'Change the billing owner.', 'Did the caregiver receive the payout?'],
            ['Why is my card declined?', 'Show the submitted hours.', 'Get my receipt.'],
            ['SRC-B4-PRICING-001', 'SRC-B4-PAYMENT-001', 'SRC-B4-GUIDANCE-001'],
            ['navigate:family.care_history', 'handoff:SUP-HANDOFF-001'], $handoff,
        ),
        $entry(
            'KB-B4-TIME-001',
            'What submitted-hours review means',
            'After a caregiver submits a visit, the Family reviews the recorded start, end, unpaid break if present, total worked duration, task record, and notes before approval. The assistant can read and recap the current authorized submission, then open the exact hours area. It must not say the hours are correct merely because they were submitted.',
            'Submitted hours', $family, $timesheetPage,
            ['FAM-VISIT-018', 'FAM-VISIT-019'],
            ['Submitted hours remain pending until the Family or current workflow resolves them.', 'The recap may include recorded start, end, break, duration, tasks, and notes.', 'The exact visit page is authoritative.'],
            ['That submitted hours are accurate.', 'Missing notes or tasks.', 'Another Family’s visit.'],
            ['What is a timesheet review?', 'What hours did the caregiver submit?', 'Show the start, end, duration, tasks, and notes.'],
            ['Why did my card fail?', 'Change my payment method.', 'How much does care cost?'],
            ['SRC-B4-TIME-001', 'SRC-B4-GUIDANCE-001'],
            ['navigate:family.request.timesheet'], $handoff,
        ),
        $entry(
            'KB-B4-TIME-002',
            'Approve submitted hours through the normal visit review',
            'Before approval, show the submitted-hours recap and open the exact visit review. The Family completes the existing approval control. Approval can continue the final payment flow. The assistant does not approve hours or trigger payment from a conversational answer, and it verifies the changed visit and payment state before saying approval worked.',
            'Submitted hours', $family, $timesheetPage,
            ['FAM-VISIT-020', 'FAM-VISIT-034'],
            ['The normal visit review contains the approval control.', 'Approval can continue final payment.', 'Success requires authoritative visit and payment state.'],
            ['That submitted hours are correct.', 'That approval or payment completed from navigation alone.'],
            ['Approve these submitted hours.', 'Will approval charge my card?', 'Take me to the hours approval.'],
            ['Get a refund.', 'Add a Family member.', 'Change the caregiver.'],
            ['SRC-B4-TIME-001', 'SRC-B4-PAYMENT-001'],
            ['navigate:family.request.timesheet'], $handoff,
        ),
        $entry(
            'KB-B4-TIME-003',
            'Question submitted hours or request a correction',
            'The assistant may prepare the Family’s reason and proposed correction for the matching visit. It shows the prepared text before anything is sent. The Family explicitly submits through the existing visit workflow. The assistant must not alter immutable submitted records, invent replacement times, or send a request without confirmation.',
            'Submitted hours', $family, $timesheetPage,
            ['FAM-VISIT-021', 'FAM-VISIT-022'],
            ['A correction request may be prepared for the matching authorized visit.', 'The Family reviews the prepared reason before submission.', 'Original submitted records remain preserved.'],
            ['Replacement start or end times not stated by the Family.', 'That the caregiver accepted the requested change.'],
            ['These submitted hours look wrong.', 'Ask the caregiver to correct the time.', 'Prepare a change request for this timesheet.'],
            ['Retry my card.', 'Where is my receipt?', 'Change my care profile.'],
            ['SRC-B4-TIME-001', 'SRC-B4-GUIDANCE-001'],
            ['navigate:family.request.timesheet'], $handoff,
        ),
        $entry(
            'KB-B4-TIME-004',
            'Review or approve a caregiver time correction',
            'For a pending correction, recap the original and proposed start, end, break, worked duration, and Family charge when those fields exist. Then open the exact correction review. The Family uses the normal approve or request-changes control. Approval and any resulting payment are not complete until the application state confirms them.',
            'Submitted hours', $family, $timesheetPage,
            ['FAM-VISIT-023', 'FAM-VISIT-024'],
            ['A pending correction can be compared with its preserved original snapshot.', 'The correction review is tied to one authorized visit.', 'Approval may lead to payment processing or payment action required.'],
            ['Missing original or proposed values.', 'That the proposed correction is accurate or approved.'],
            ['Review the caregiver’s time correction.', 'What changed in these hours?', 'Approve this correction and payment.'],
            ['What is the hourly price?', 'Add a card.', 'Show request applicants.'],
            ['SRC-B4-TIME-001', 'SRC-B4-PAYMENT-001'],
            ['navigate:family.request.timesheet'], $handoff,
        ),
        $entry(
            'KB-B4-TIME-005',
            'Request correction changes or continue its payment',
            'If a correction needs changes, prepare the Family’s note and open the exact correction review for explicit submission. If approved hours instead show payment action required, open the secure payment continuation. These are different states; read the current correction and payment records before choosing the button.',
            'Submitted hours', $family, $timesheetPage,
            ['FAM-VISIT-025', 'FAM-VISIT-026'],
            ['Changes requested and payment action required are different correction states.', 'The current correction state determines the next control.', 'Payment authentication stays in the secure flow.'],
            ['That a changes request was sent.', 'That payment completed after authentication.'],
            ['Ask for another change to this correction.', 'The corrected hours need card confirmation.', 'Continue payment for the approved correction.'],
            ['Show my payment history.', 'How much does the caregiver earn?', 'Create recurring care.'],
            ['SRC-B4-TIME-001', 'SRC-B4-PAYMENT-001'],
            ['navigate:family.request.timesheet', 'navigate:family.request.payment_attention'], $handoff,
        ),
        $entry(
            'KB-B4-TIME-006',
            'Escalated corrections, post-care disputes, and their status',
            'A correction or post-care dispute may be prepared with the matching visit, recorded hours, payment summary, and the Family’s own reason. Explicit submission transfers it for LoLo review. The assistant can read a current dispute or escalation status, but it cannot decide the outcome, assign fault, promise a response time, or change money by itself.',
            'Submitted hours', $family, $timesheetPage,
            ['FAM-VISIT-027', 'FAM-VISIT-028', 'FAM-VISIT-029'],
            ['A dispute or escalation is tied to an authorized visit.', 'Current status may be read from the application.', 'Outcome and financial decisions require the normal review path or a person.'],
            ['An outcome, fault, refund, adjustment, or response time.', 'Private caregiver information.'],
            ['Escalate this time correction.', 'Open a dispute after care.', 'What is the status of my hours dispute?'],
            ['Update my card.', 'Show the hourly price.', 'Post a care request.'],
            ['SRC-B4-TIME-001', 'SRC-B4-GUIDANCE-001'],
            ['navigate:family.request.timesheet', 'handoff:SUP-HANDOFF-001'], $handoff,
        ),
    ],
];
