<?php

$reviewBy = '2026-11-18';

$sources = [
    'SRC-B5-PROFILE-001' => ['Current care-receiver profile implementation', 'Draft, ready, default, sharing, revision, archive, restore, and permission behavior.'],
    'SRC-B5-REQUEST-001' => ['Current Family care-request implementation', 'Draft, publication, lifecycle status, applicants, booking, withdrawal, and copy behavior.'],
    'SRC-B5-CONFIRM-001' => ['AI Support Batch 5 confirmation contract', 'Recap, exact actor/account binding, stale-state denial, idempotency, authoritative commit, and verification.'],
    'SRC-B5-BOUNDARY-001' => ['AI Support Family operating policy', 'Non-medical, 24/7 handoff, permanent-deletion, live-edit replacement, and no-availability-promise boundaries.'],
];

$entry = static function (
    string $stableId,
    string $title,
    string $answer,
    string $productArea,
    array $targets,
    array $intentIds,
    array $mayState,
    array $mustNotInfer,
    array $matches,
    array $noMatches,
    array $sourceIds,
    array $nextActions = [],
    array $escalations = [],
) use ($reviewBy, $sources): array {
    $prefix = str_replace('KB-', 'EVAL-KB-', $stableId);

    return [
        'stable_id' => $stableId,
        'intent_ids' => array_values($intentIds),
        'type' => 'task_playbook',
        'title' => $title,
        'answer_body' => $answer,
        'sensitivity' => 'authenticated',
        'product_area' => $productArea,
        'locale' => 'en-US',
        'roles' => ['family'],
        'membership_states' => ['active'],
        'route_target_ids' => array_values($targets),
        'capability_ids' => ['support_answers_v1'],
        'facts_may_state' => array_values($mayState),
        'facts_must_not_infer' => array_values(array_unique([
            ...$mustNotInfer,
            'Another Family Account, profile, request, applicant, caregiver, address, booking, payment, or private note.',
            'That opening a page, preparing details, or displaying a confirmation means an action succeeded.',
            'That a caregiver will apply, respond, accept, or be available.',
        ])),
        'next_actions' => array_values($nextActions),
        'escalation_conditions' => array_values(array_unique([
            ...$escalations,
            'The user asks for a person.',
            'The authorized current state does not expose a safe next step.',
        ])),
        'retrieval_examples_match' => array_values($matches),
        'retrieval_examples_no_match' => array_values($noMatches),
        'evaluation_ids' => [
            $prefix.'-POSITIVE',
            $prefix.'-BOUNDARY',
            $prefix.'-WRONG-ACCOUNT',
            $prefix.'-STALE-OR-UNAVAILABLE',
            $prefix.'-HANDOFF',
        ],
        'change_note' => 'Batch 5 care-profile and request-lifecycle knowledge approved for the two-user pilot.',
        'review_by' => $reviewBy,
        'expires_on' => null,
        'sources' => array_values(array_map(
            static fn (string $id): array => [
                'source_id' => $id,
                'title' => $sources[$id][0],
                'url' => null,
                'section_anchor' => $sources[$id][1],
                'fact_supported' => implode(' ', $mayState),
            ],
            $sourceIds,
        )),
    ];
};

$profiles = ['family.care_profiles'];
$newProfile = ['family.care_profile.create'];
$profileIdentity = ['family.care_profile.identity'];
$profileContact = ['family.care_profile.contact'];
$profileReview = ['family.care_profile.review'];
$requests = ['family.care_requests'];
$newRequest = ['family.new_care_request'];
$requestOverview = ['family.request.overview'];
$requestApplicants = ['family.request.applicants'];
$handoff = ['handoff:SUP-HANDOFF-001'];

return [
    'version' => 'profile-request-kb-v1',
    'approved_at' => '2026-08-18',
    'entries' => [
        $entry(
            'KB-B5-PROFILE-001',
            'What a care-receiver profile is and who can use it',
            'A care-receiver profile keeps the Family Account’s reusable information about the person receiving non-medical care. Active Family Account members can review and update profiles in that account. Candidate caregivers receive only the candidate sharing view; a hired caregiver may receive the assigned-care view. The assistant must read only profiles in the signed-in user’s Family Account.',
            'Care receiver profiles', $profiles,
            ['FAM-PROFILE-001', 'FAM-PROFILE-002', 'FAM-PROFILE-015', 'FAM-PROFILE-016', 'FAM-PROFILE-025'],
            ['Profiles belong to one Family Account.', 'Active Family members may use profiles in that account.', 'Candidate and assigned-care sharing views can differ.'],
            ['That a caregiver saw a profile.', 'That every private Family note is shared.', 'A profile outside the current Family Account.'],
            ['What is a care receiver profile?', 'Who can see Maria’s profile?', 'Show my care profiles.', 'What will candidates see?'],
            ['Delete my account.', 'Why did my payment fail?', 'Show caregiver earnings.'],
            ['SRC-B5-PROFILE-001', 'SRC-B5-BOUNDARY-001'],
            ['navigate:family.care_profiles'], $handoff,
        ),
        $entry(
            'KB-B5-PROFILE-002',
            'Profile draft, ready state, and required information',
            'A profile can be saved as a Draft and finished later. To mark it Ready, it needs the preferred name caregivers should use, at least one helpful shareable care detail, and confirmation that the Family understands the sharing preview. Ready means the profile can be proposed for a care request; it does not publish a request or hire a caregiver.',
            'Care receiver profiles', $profileReview,
            ['FAM-PROFILE-003', 'FAM-PROFILE-004', 'FAM-PROFILE-005'],
            ['A draft may be saved with a preferred name and finished later.', 'Ready requires a preferred name, helpful shareable content, and sharing acknowledgement.', 'Ready does not publish a request.'],
            ['That optional profile fields are mandatory.', 'That Ready means care is booked.', 'That a missing sharing acknowledgement can be assumed.'],
            ['What is missing from this profile?', 'Save this profile and finish later.', 'Make Maria’s profile ready.'],
            ['Create a care request for Friday.', 'Withdraw my open request.', 'Change my card.'],
            ['SRC-B5-PROFILE-001', 'SRC-B5-CONFIRM-001'],
            ['navigate:family.care_profile.review'], $handoff,
        ),
        $entry(
            'KB-B5-PROFILE-003',
            'Profile identity and relationship details',
            'The Family can add or change whether the recipient is the requester, preferred name, full name, relationship, date of birth or age range, and pronouns. The assistant prepares only details the user explicitly provides, shows a recap, and saves only after confirmation. Sensitive identity details must not be guessed.',
            'Care receiver profiles', $profileIdentity,
            ['FAM-PROFILE-006', 'FAM-PROFILE-007'],
            ['Identity and relationship fields may be prepared from explicit Family input.', 'A recap and confirmation are required before saving chat-prepared changes.'],
            ['A date of birth, relationship, pronoun, or full name not stated by the user.', 'That preparation saved the profile.'],
            ['Change her preferred name to Maria.', 'This profile is for my mother.', 'Use she and her pronouns.'],
            ['Change the visit time.', 'Who applied to my request?', 'Refund a charge.'],
            ['SRC-B5-PROFILE-001', 'SRC-B5-CONFIRM-001'],
            ['navigate:family.care_profile.identity'], $handoff,
        ),
        $entry(
            'KB-B5-PROFILE-004',
            'Helpful care, communication, mobility, and routine details',
            'A profile may include the person’s interests, good-visit notes, communication preferences, everyday non-medical context, support areas, mobility, routines, food and drink notes, personal-care preferences, overnight preferences, comfort needs, and calming approaches. These details should be factual, respectful, and limited to what helps provide non-medical care.',
            'Care receiver profiles', $profiles,
            ['FAM-PROFILE-008', 'FAM-PROFILE-009', 'FAM-PROFILE-010', 'FAM-PROFILE-011', 'FAM-PROFILE-012'],
            ['The Family controls these reusable non-medical care details.', 'The assistant may prepare only supported fields and explicit values.'],
            ['A diagnosis, clinical instruction, medical conclusion, or unstated care need.', 'That a caregiver is clinically qualified.'],
            ['Add that he uses a walker.', 'She needs short clear sentences.', 'Add her morning routine.', 'Note the peanut allergy.'],
            ['Administer insulin.', 'Change a catheter.', 'Show my invoices.'],
            ['SRC-B5-PROFILE-001', 'SRC-B5-BOUNDARY-001', 'SRC-B5-CONFIRM-001'],
            ['navigate:family.care_profiles'], $handoff,
        ),
        $entry(
            'KB-B5-PROFILE-005',
            'Safety notes, caregiver preferences, and additional contacts',
            'The Family may add practical non-medical safety information, caregiver qualities, do and avoid notes, and an additional contact. Urgent danger is not stored as an ordinary profile update: the user should call 911 when someone is in immediate danger, and the conversation transfers to a person. Contact details stay inside the authorized Family Account and assigned-care workflow.',
            'Care receiver profiles', $profileContact,
            ['FAM-PROFILE-013', 'FAM-PROFILE-014'],
            ['Practical non-medical safety notes and caregiver preferences may be stored.', 'An additional contact is optional and account-authorized.', 'Immediate danger triggers emergency instructions and transfer.'],
            ['Medical advice.', 'Permission to contact or disclose information beyond the product workflow.', 'That a safety note replaces emergency help.'],
            ['Add fall risk to her profile.', 'Add my sister as the additional contact.', 'He needs a calm patient caregiver.'],
            ['Someone is not breathing.', 'Add a credit card.', 'Withdraw my request.'],
            ['SRC-B5-PROFILE-001', 'SRC-B5-BOUNDARY-001'],
            ['navigate:family.care_profile.contact'], $handoff,
        ),
        $entry(
            'KB-B5-PROFILE-006',
            'Saving profile changes and current-care impact',
            'Saving a profile creates a new reusable profile version. Existing assigned care keeps its previous attached information unless the Family separately chooses to apply the latest profile to current care. Before that separate action, LoLo shows the affected care and any caregiver-notification impact. The assistant never silently changes current care.',
            'Care receiver profiles', $profileReview,
            ['FAM-PROFILE-017', 'FAM-PROFILE-018'],
            ['Profile-only save and apply-to-current-care are separate actions.', 'Applying a profile can affect current care and caregiver notifications.'],
            ['That a profile edit automatically changes an existing visit.', 'That a caregiver was notified without an authoritative receipt.'],
            ['Save this without changing current care.', 'Will this update my current caregiver?', 'Apply the new profile to current care.'],
            ['Edit the live request silently.', 'Retry my card.', 'Show submitted hours.'],
            ['SRC-B5-PROFILE-001', 'SRC-B5-CONFIRM-001'],
            ['navigate:family.care_profile.review'], $handoff,
        ),
        $entry(
            'KB-B5-PROFILE-007',
            'Default profile selection',
            'The default care-receiver profile is suggested first when starting new care. Changing the default does not modify existing requests, visits, or assigned care. The assistant reads the current default, shows the proposed change, and confirms the saved account state after the Family approves it.',
            'Care receiver profiles', $profiles,
            ['FAM-PROFILE-019', 'FAM-PROFILE-022', 'FAM-PROFILE-023'],
            ['One active profile can be suggested first for new care.', 'Changing the default does not rewrite existing care.'],
            ['That default means the only permitted recipient.', 'That current requests changed.'],
            ['Make Maria the default profile.', 'Use John instead for this request.', 'Which profile is suggested first?'],
            ['Archive Maria.', 'Change the saved card.', 'Hire this caregiver.'],
            ['SRC-B5-PROFILE-001', 'SRC-B5-CONFIRM-001'],
            ['navigate:family.care_profiles'], $handoff,
        ),
        $entry(
            'KB-B5-PROFILE-008',
            'Archive, restore, and permanent deletion boundaries',
            'Archiving hides a profile from normal new-care selection without permanently deleting its history. If the archived profile was the default, LoLo selects another active profile when available. Restoring returns it to Draft or Ready according to its saved version. Permanent profile deletion is not available through AI Support; ask a person for help with that request.',
            'Care receiver profiles', $profiles,
            ['FAM-PROFILE-020', 'FAM-PROFILE-021', 'FAM-PROFILE-026'],
            ['Archive is reversible.', 'Restore returns the profile to its prior usable readiness basis.', 'Permanent deletion is human-assisted.'],
            ['That archive deletes history.', 'That a profile with active dependencies can be permanently deleted.', 'That restore changes current care.'],
            ['Archive Maria’s profile.', 'Restore the archived profile.', 'Delete this profile forever.'],
            ['Withdraw a care request.', 'Close my Family Account.', 'Remove my card.'],
            ['SRC-B5-PROFILE-001', 'SRC-B5-BOUNDARY-001', 'SRC-B5-CONFIRM-001'],
            ['navigate:family.care_profiles'], $handoff,
        ),
        $entry(
            'KB-B5-PROFILE-009',
            'Saved address and home-access information in new care',
            'When authorized household address or home-access information is available, LoLo may propose it in a private request draft. The Family can change it before publication. It is not made live until the final request recap is confirmed, and secure access details must not be repeated outside the authorized request flow.',
            'Care receiver profiles', $newRequest,
            ['FAM-PROFILE-024'],
            ['Authorized saved address and access notes may be proposed in a private draft.', 'The Family reviews and may change the proposal.'],
            ['A different account’s address.', 'That draft address information is already public.'],
            ['Use my saved address.', 'Change the home access notes for this request.', 'Where will care happen?'],
            ['Show a caregiver’s address.', 'Change my card.', 'Archive a profile.'],
            ['SRC-B5-PROFILE-001', 'SRC-B5-REQUEST-001'],
            ['navigate:family.new_care_request'], $handoff,
        ),
        $entry(
            'KB-B5-REQUEST-001',
            'Choosing one-time, regular, or human-led 24/7 care',
            'One specific visit is one-time care. Care repeating on selected weekdays is regular care. A request for continuous day-and-night or 24/7 coverage transfers to LoLo Support for human coordination and does not create an AI marketplace request. Mentioning 24/7 is not itself an emergency unless someone is in immediate danger.',
            'Care requests', $newRequest,
            array_map(static fn (int $number): string => sprintf('FAM-REQUEST-%03d', $number), range(1, 5)),
            ['One-time and regular care can use the conversational request draft.', '24/7 coverage transfers to human support.', 'Immediate danger receives 911 instructions first.'],
            ['That 24/7 availability is guaranteed.', 'That a human-led 24/7 request was published.', 'A medical care path.'],
            ['I need help once on Friday.', 'I need care every Monday and Wednesday.', 'I need someone there day and night.'],
            ['Change my card.', 'Archive a profile.', 'Approve submitted hours.'],
            ['SRC-B5-REQUEST-001', 'SRC-B5-BOUNDARY-001'],
            ['navigate:family.new_care_request'], $handoff,
        ),
        $entry(
            'KB-B5-REQUEST-002',
            'Information collected for a care request',
            'A request needs the person receiving care, at least one approved non-medical task, the care address, and a schedule. One-time care needs a future date, start time, and duration. Regular care needs weekdays, a start time and duration for each day, a start date, and either ongoing care or an end date. The Family can add task notes and other instructions before reviewing the recap.',
            'Care requests', $newRequest,
            array_map(static fn (int $number): string => sprintf('FAM-REQUEST-%03d', $number), range(6, 19)),
            ['Recipient, tasks, address, and schedule are required.', 'One-time and regular schedules have different required details.', 'Only approved non-medical tasks are accepted.'],
            ['An unstated date, time, duration, recipient, address, or task.', 'A clinical or medical task.'],
            ['What information do you need?', 'Add companionship and light housekeeping.', 'Use Tuesday at 9 AM for three hours.', 'Make it every Monday.'],
            ['Withdraw my request.', 'Who applied?', 'Why was my card declined?'],
            ['SRC-B5-REQUEST-001', 'SRC-B5-BOUNDARY-001'],
            ['navigate:family.new_care_request'], $handoff,
        ),
        $entry(
            'KB-B5-REQUEST-003',
            'Private drafts, resume, changes, recap, and confirmation',
            'Chat-collected request details remain a private draft until the Family confirms the full recap. A usable draft can be resumed for seven days. The Family may change any supported section; every material change invalidates the earlier confirmation and produces a fresh recap. A confirmation expires after 30 minutes, but the saved draft can produce a new confirmation without retyping. Discarding removes the private draft content.',
            'Care requests', $newRequest,
            array_map(static fn (int $number): string => sprintf('FAM-REQUEST-%03d', $number), range(22, 30)),
            ['A chat draft is private and resumable for seven days.', 'Material changes require a fresh recap.', 'Confirmation lasts 30 minutes and can be renewed from the saved draft.'],
            ['That a draft is live.', 'That an expired confirmation requires retyping.', 'That discarded draft content remains available.'],
            ['Is this draft live?', 'Resume my saved request.', 'Change the time.', 'Review the recap again.', 'Discard this draft.'],
            ['Withdraw my live request.', 'Show applicants.', 'Archive a care profile.'],
            ['SRC-B5-REQUEST-001', 'SRC-B5-CONFIRM-001'],
            ['navigate:family.new_care_request'], $handoff,
        ),
        $entry(
            'KB-B5-REQUEST-004',
            'Reuse, duplicate, and copy an earlier request',
            'The assistant can start a new private draft from an authorized earlier request. It may reuse the recipient, tasks, notes, address, access notes, request type, and reusable regular schedule. A one-time date and start time are cleared because they must be future choices; a regular-care start date is cleared. The source request is never changed by making the copy.',
            'Care requests', $newRequest,
            ['FAM-REQUEST-020', 'FAM-REQUEST-021', 'FAM-REQUEST-040'],
            ['Copying creates a separate private draft.', 'Past one-time timing and a past regular-care start date are not silently reused.', 'The source request remains unchanged.'],
            ['That duplicate means publish.', 'That an expired date is valid.', 'That the original request was withdrawn.'],
            ['Reuse my last request.', 'Duplicate the companionship request.', 'Start from Maria’s saved profile instead.'],
            ['Edit the original silently.', 'Withdraw the request.', 'Restore a profile.'],
            ['SRC-B5-REQUEST-001', 'SRC-B5-CONFIRM-001'],
            ['navigate:family.new_care_request'], $handoff,
        ),
        $entry(
            'KB-B5-REQUEST-005',
            'What happens after a request is published',
            'After explicit confirmation, the request becomes Open and eligible caregivers can see it. Publication does not hire a caregiver and does not authorize or capture payment. LoLo returns a request receipt and a View request action. Repeating the same confirmation uses idempotent reconciliation so it cannot create a second request from the same confirmed action.',
            'Care requests', $requestOverview,
            ['FAM-REQUEST-031', 'FAM-REQUEST-032', 'FAM-REQUEST-033', 'FAM-REQUEST-043'],
            ['Open means eligible caregivers can see the request.', 'Publication alone does not hire or authorize payment.', 'Confirmed publication returns one authoritative receipt.'],
            ['That a caregiver applied or was hired.', 'That payment occurred.', 'That navigation proves publication.'],
            ['What happens after I post?', 'Did this hire someone?', 'Was my card charged?', 'Did retrying create two requests?'],
            ['Withdraw my request.', 'Archive a profile.', 'Approve hours.'],
            ['SRC-B5-REQUEST-001', 'SRC-B5-CONFIRM-001'],
            ['navigate:family.request.overview'], $handoff,
        ),
        $entry(
            'KB-B5-REQUEST-006',
            'Care-request status and applicant visibility',
            'Draft means not live. Open means eligible caregivers may apply. Filled means a caregiver was hired and the request has moved into the visit or care workflow. Cancelled means the Family withdrew the request. Expired means it is no longer live. The assistant may read the current status and Family-visible applicant counts, but it cannot claim who merely viewed a request or promise a response.',
            'Care requests', array_merge($requests, $requestOverview, $requestApplicants),
            ['FAM-REQUEST-034', 'FAM-REQUEST-035', 'FAM-REQUEST-044'],
            ['Request status comes from the current authorized record.', 'Applicant counts may be stated when visible to the Family.', 'Caregiver views and response times are not promised.'],
            ['That a caregiver viewed the request.', 'That an open request will receive applicants.', 'A status from stale chat text.'],
            ['What is my request status?', 'Did anyone apply?', 'When will a caregiver respond?', 'Why is this request no longer open?'],
            ['Change the saved card.', 'Edit a profile.', 'Show submitted hours.'],
            ['SRC-B5-REQUEST-001', 'SRC-B5-BOUNDARY-001'],
            ['navigate:family.request.overview', 'navigate:family.request.applicants'], $handoff,
        ),
        $entry(
            'KB-B5-REQUEST-007',
            'Validation, blocked publication, and stale confirmation recovery',
            'When a request cannot proceed, LoLo identifies the first exact missing or invalid field and asks only for that correction. Common blockers are missing recipient, task, address, schedule, past date, unsupported duration, incomplete recurring schedule, invalid state or ZIP, changed care profile, or stale confirmation. The saved draft remains available so the Family can correct the problem without restarting.',
            'Care requests', $newRequest,
            ['FAM-REQUEST-041', 'FAM-REQUEST-042'],
            ['The current validator supplies the correction message.', 'A saved usable draft can continue after a validation failure.', 'Stale confirmations require a new recap.'],
            ['A guessed fix.', 'That invalid data was accepted.', 'That a stale recap can still commit.'],
            ['Why did publication fail?', 'Fix the missing ZIP without restarting.', 'My confirmation expired.', 'The profile changed while I was confirming.'],
            ['Why did payment fail?', 'Why are submitted hours wrong?', 'Delete the profile.'],
            ['SRC-B5-REQUEST-001', 'SRC-B5-CONFIRM-001'],
            ['navigate:family.new_care_request'], $handoff,
        ),
        $entry(
            'KB-B5-REQUEST-008',
            'Live request changes use a reviewed replacement',
            'LoLo does not silently edit a live request in place. The assistant can start a separate private replacement draft from the current request, apply the Family’s requested changes, and show the complete new recap. Publishing the replacement does not automatically withdraw the original; withdrawing the original is a separate confirmed action so applicants and existing care are never changed unexpectedly.',
            'Care requests', array_merge($newRequest, $requestOverview),
            ['FAM-REQUEST-036', 'FAM-REQUEST-037'],
            ['Live-request changes use a separate reviewed replacement draft.', 'The original remains unchanged until a separate allowed withdrawal.', 'Request-type conversion is a new replacement request.'],
            ['That live applicants moved to the replacement.', 'That current care or a booking changed.', 'That the original was withdrawn automatically.'],
            ['Change the time on my live request.', 'Turn this one-time request into regular care.', 'Edit the tasks without affecting applicants.'],
            ['Cancel an active visit.', 'Change submitted hours.', 'Update a profile only.'],
            ['SRC-B5-REQUEST-001', 'SRC-B5-CONFIRM-001', 'SRC-B5-BOUNDARY-001'],
            ['navigate:family.new_care_request', 'navigate:family.request.overview'], $handoff,
        ),
        $entry(
            'KB-B5-REQUEST-009',
            'Withdraw an open request safely',
            'Only a Draft or Open request without a booking can be withdrawn through the request lifecycle. The recap shows that caregivers can no longer apply, active applications become not selected, and pending invitations are cancelled. A request that already has a booking must use the visit or care-change workflow instead. The assistant confirms the exact current request again before committing and verifies that its status became Cancelled.',
            'Care requests', $requestOverview,
            ['FAM-REQUEST-038'],
            ['Withdrawal is available only for Draft or Open requests without a booking.', 'Active applications and pending invitations are closed by withdrawal.', 'Success requires authoritative Cancelled status.'],
            ['That a booked visit was cancelled.', 'That a stale request state can be withdrawn.', 'That opening the request withdrew it.'],
            ['Withdraw my open request.', 'Stop caregivers applying to this request.', 'Cancel this request before anyone is hired.'],
            ['Cancel tomorrow’s booked visit.', 'Delete a profile.', 'End regular care.'],
            ['SRC-B5-REQUEST-001', 'SRC-B5-CONFIRM-001'],
            ['navigate:family.request.overview'], $handoff,
        ),
        $entry(
            'KB-B5-REQUEST-010',
            'Expired or withdrawn requests create a fresh copy',
            'An Expired or Cancelled request is not reopened in place. The assistant can create a new private draft from it, clear timing that must be chosen again, and ask for the first missing schedule detail. The old request stays unchanged as history. The new request becomes live only after a fresh full recap and explicit confirmation.',
            'Care requests', array_merge($newRequest, $requestOverview),
            ['FAM-REQUEST-039'],
            ['Expired and withdrawn requests are copied into a new draft.', 'The old request remains history.', 'The new request needs a fresh schedule, recap, and confirmation.'],
            ['That the old request was reopened.', 'That old dates remain valid.', 'That the copy is already live.'],
            ['Reopen my expired request.', 'Use the withdrawn request again.', 'Book the same care again.'],
            ['Restore an archived profile.', 'Resume a current draft.', 'Retry payment.'],
            ['SRC-B5-REQUEST-001', 'SRC-B5-CONFIRM-001'],
            ['navigate:family.new_care_request'], $handoff,
        ),
        $entry(
            'KB-B5-REQUEST-011',
            'Medical tasks and guaranteed caregiver responses are not supported promises',
            'LoLo provides non-medical care. A request for a clinical procedure, medical advice, or medication administration transfers to a person and is not added as an ordinary task. Response-window preferences tell caregivers when the Family hopes to hear back; they are not guarantees of an application, response, hire, or availability.',
            'Care requests', $newRequest,
            ['FAM-REQUEST-044', 'FAM-REQUEST-045'],
            ['Care requests contain approved non-medical tasks.', 'Response preferences are not guarantees.', 'Medical or clinical requests transfer.'],
            ['That LoLo guarantees a response.', 'That a caregiver can perform a clinical task.', 'A support wait time.'],
            ['Guarantee someone responds in an hour.', 'Add wound care to my request.', 'Can the caregiver inject insulin?'],
            ['Add companionship.', 'Show my request status.', 'Change the care address.'],
            ['SRC-B5-REQUEST-001', 'SRC-B5-BOUNDARY-001'],
            ['navigate:family.new_care_request'], $handoff,
        ),
    ],
];
