<?php

$review90 = '2026-11-12';
$review180 = '2027-02-10';

$source = static fn (
    string $sourceId,
    string $title,
    string $factSupported,
    ?string $sectionAnchor = null,
    ?string $url = null,
): array => [
    'source_id' => $sourceId,
    'title' => $title,
    'url' => $url,
    'section_anchor' => $sectionAnchor,
    'fact_supported' => $factSupported,
];

$entry = static fn (
    string $stableId,
    string $type,
    string $title,
    string $answerBody,
    string $productArea,
    array $roles,
    string $target,
    array $factsMayState,
    array $factsMustNotInfer,
    array $nextActions,
    array $escalationConditions,
    array $retrievalMatch,
    array $retrievalNoMatch,
    array $evaluationIds,
    string $reviewBy,
    array $sources,
): array => [
    'stable_id' => $stableId,
    'type' => $type,
    'title' => $title,
    'answer_body' => $answerBody,
    'sensitivity' => 'authenticated',
    'product_area' => $productArea,
    'locale' => 'en-US',
    'roles' => $roles,
    'membership_states' => ['active'],
    'route_target_ids' => [$target],
    'capability_ids' => ['support_answers_v1'],
    'facts_may_state' => $factsMayState,
    'facts_must_not_infer' => $factsMustNotInfer,
    'next_actions' => $nextActions,
    'escalation_conditions' => $escalationConditions,
    'retrieval_examples_match' => $retrievalMatch,
    'retrieval_examples_no_match' => $retrievalNoMatch,
    'evaluation_ids' => $evaluationIds,
    'change_note' => 'Initial approved English support definition imported as Draft under DEC-034 through DEC-046.',
    'review_by' => $reviewBy,
    'expires_on' => null,
    'sources' => $sources,
];

return [
    'version' => 'initial-kb-v1',
    'approved_at' => '2026-08-14',
    'entries' => [
        $entry(
            'KB-SUP-001',
            'escalation',
            'Talk to a person',
            'You can ask to talk to LoLo Support at any time. I can transfer this conversation now. You can keep using this chat, and you will not need to repeat what you already told me.',
            'Support',
            ['family', 'caregiver'],
            'support.center',
            [
                'A signed-in Family or Caregiver user may ask for a person at any time.',
                'Transfer stays in the same canonical support conversation.',
                'The user may continue typing after transfer.',
                'Automation stops after deterministic transfer confirmation.',
            ],
            [
                'A named person is already available.',
                'An immediate response, wait time, queue position, or queue status.',
                'Support in another language.',
                'Transfer itself resolves an emergency, medical, billing, payment, identity, safety, or account problem.',
            ],
            [
                'handoff:SUP-HANDOFF-001',
            ],
            [
                'The user asks for a person, agent, representative, or human support.',
                'Automation ownership or authorization cannot be resolved safely.',
                'Another approved entry requires human escalation.',
            ],
            [
                'Can I talk to a person?',
                'Please transfer me to LoLo Support.',
                'I do not want the automated assistant.',
            ],
            [
                'Where can I see my visits?',
                'What does Open mean on my care request?',
                'Take me to Account Settings.',
            ],
            [
                'EVAL-KB-SUP-001-POS',
                'EVAL-KB-SUP-001-BOUNDARY',
                'EVAL-KB-SUP-001-WRONG-ROLE',
                'EVAL-KB-SUP-001-UNSUPPORTED-STATE',
                'EVAL-KB-SUP-001-HANDOFF',
            ],
            $review90,
            [
                $source('SRC-AI-DECISIONS-001', 'Intelligent Support decision log', 'Canonical human-support conversation, transfer authority, and no queue-status promise.', 'DEC-001, DEC-008, DEC-035'),
                $source('SRC-SUPPORT-CHAT-001', 'Support live-chat specification', 'Same-conversation human support behavior and canonical transcript continuity.', 'Human transfer and conversation continuity'),
            ],
        ),
        $entry(
            'KB-SUP-002',
            'escalation',
            'Emergencies and non-medical support',
            "LoLo is not an emergency service. If someone is in immediate danger or needs urgent medical help, call 911 now. I can also transfer this conversation to LoLo Support, but that is not a substitute for emergency help.\n\nLoLo supports non-medical help at home. LoLo cannot provide medical advice, diagnosis, treatment, medication decisions, or clinical services. Please contact a licensed healthcare professional for medical help. I can transfer you to LoLo Support for help using the platform.",
            'Support and safety',
            ['family', 'caregiver'],
            'support.center',
            [
                'LoLo is not an emergency service.',
                "Immediate danger or urgent medical need requires calling 911 within LoLo's current United States scope.",
                'LoLo supports non-medical help and cannot provide medical or clinical advice or services.',
                'Human transfer is available for platform help but is not emergency or clinical help.',
            ],
            [
                'That LoLo or the assistant contacted 911 or another responder.',
                'That LoLo Support can assess, monitor, treat, or resolve an emergency.',
                'A diagnosis, severity assessment, medication decision, dosage, procedure, treatment, or clinical recommendation.',
                'That waiting for LoLo Support or a caregiver is safe.',
            ],
            [
                'safety:call_911_instruction',
                'safety:non_medical_boundary',
                'handoff:SUP-HANDOFF-001',
            ],
            [
                'Immediate danger, urgent medical need, self-harm, crisis, abuse, neglect, or other critical safety language.',
                'Requests for diagnosis, treatment, medication, dosage, clinical procedure, or medical advice.',
                'Ambiguous critical language that cannot safely be ruled out.',
            ],
            [
                'She cannot breathe. What do I do?',
                'Should I change his medication dose?',
                'Can the caregiver perform a medical procedure?',
            ],
            [
                'Where is my next visit?',
                'How do I update my email?',
                'What does Visit scheduled mean?',
            ],
            [
                'EVAL-KB-SUP-002-POS',
                'EVAL-KB-SUP-002-BOUNDARY',
                'EVAL-KB-SUP-002-WRONG-ROLE',
                'EVAL-KB-SUP-002-UNSUPPORTED-STATE',
                'EVAL-KB-SUP-002-HANDOFF',
            ],
            $review90,
            [
                $source('SRC-LOLO-SAFETY-001', 'Acceptable Use and Safety Policy', 'Emergency limitation and prohibition on medical or clinical services.', 'Emergency and medical limitations'),
                $source('SRC-LOLO-TERMS-001', 'Platform Terms of Service', 'LoLo is not for emergency use and does not provide medical or clinical services.', 'Emergency and medical limitations'),
                $source('SRC-LOLO-FAMILY-TERMS-001', 'Client and Family Terms', 'Family-role emergency and non-medical limitations.', 'Family emergency and clinical restrictions'),
                $source('SRC-LOLO-CAREGIVER-TERMS-001', 'Caregiver Terms', 'Caregiver-role clinical restrictions.', 'Caregiver medical and clinical restrictions'),
                $source('SRC-AI-DECISIONS-001', 'Intelligent Support decision log', 'Deterministic safety-first response and human-only transfer boundary.', 'DEC-035, DEC-036'),
            ],
        ),
        $entry(
            'KB-SUP-003',
            'product_fact',
            'English-only support',
            "LoLo's automated support is available in English only. I can continue in English or transfer this conversation to LoLo Support. LoLo does not promise support in another language.\n\nIf the language is unclear: Please write your question in English. You can also ask me to transfer this conversation to LoLo Support.",
            'Support',
            ['family', 'caregiver'],
            'support.center',
            [
                'Automated intelligent support is English only.',
                'The user may continue in English or request same-conversation human transfer.',
                'LoLo does not promise support in another language.',
            ],
            [
                'That automated or human translation is available.',
                'That a human will respond in another language.',
                'The meaning of a non-English message through improvised translation.',
                'That a name, address, code, typo, borrowed word, missing accent, or short ambiguous phrase proves another language.',
            ],
            [
                'clarify:english_only',
                'handoff:SUP-HANDOFF-001',
            ],
            [
                'The user clearly asks for another language.',
                'Input is clearly unsupported-language or too ambiguous to handle safely in English.',
                'The user asks for a person after receiving the language limitation.',
            ],
            [
                'Can you answer in Spanish?',
                'The message is clearly written in a language other than English.',
                'I need an interpreter.',
            ],
            [
                'A name or address containing non-English words.',
                'A typo in an otherwise clear English question.',
                'A short product code or mixed ambiguous phrase.',
            ],
            [
                'EVAL-KB-SUP-003-POS',
                'EVAL-KB-SUP-003-BOUNDARY',
                'EVAL-KB-SUP-003-WRONG-ROLE',
                'EVAL-KB-SUP-003-UNSUPPORTED-STATE',
                'EVAL-KB-SUP-003-HANDOFF',
            ],
            $review180,
            [
                $source('SRC-AI-DECISIONS-001', 'Intelligent Support decision log', 'English-only automation, no translation, ambiguity handling, and human-transfer wording.', 'DEC-016, DEC-035, DEC-037'),
            ],
        ),
        $entry(
            'KB-FAM-001',
            'navigation',
            'Your Family Care overview',
            'Care is the signed-in home for your Family care activity. Overview shows what needs attention and your care journeys. Actions collects decisions and problems, Schedule shows upcoming visits, Arrangements shows recurring care and care still being arranged, and History shows past care. What appears depends on your authorized Family Account and current care activity. I can take you to the Care overview.',
            'Family Care overview',
            ['family'],
            'family.care_requests',
            [
                'The Care overview is the signed-in Family home page.',
                'Overview, Actions, Schedule, Arrangements, and History organize the current Family care workspace.',
                'It conditionally prioritizes current next steps from authoritative account state.',
            ],
            [
                'That a request, caregiver reply, message, visit, booking, payment state, or required action exists without fresh authorized context.',
                'That opening Care creates, accepts, approves, pays, messages, or changes anything.',
                'Any Family care data to a Caregiver or a user outside the applicable Family Account.',
            ],
            [
                'navigate:family.care_requests',
            ],
            [
                'Family Account authorization cannot be resolved.',
                'The user asks for a person.',
                'The question requires a personalized status that fresh authoritative context does not provide.',
            ],
            [
                'Where do I see what needs attention?',
                'Take me to my Care overview.',
                'Where is my home page?',
            ],
            [
                'Take me to the Caregiver dashboard.',
                'Did a caregiver reply to my request?',
                'Change my payment method.',
            ],
            [
                'EVAL-KB-FAM-001-POS',
                'EVAL-KB-FAM-001-BOUNDARY',
                'EVAL-KB-FAM-001-WRONG-ROLE',
                'EVAL-KB-FAM-001-UNSUPPORTED-STATE',
                'EVAL-KB-FAM-001-HANDOFF',
            ],
            $review180,
            [
                $source('SRC-AI-DECISIONS-001', 'Intelligent Support decision log', 'Family-only orientation scope and generic navigation boundary.', 'DEC-032, DEC-038'),
                $source('SRC-FAMILY-WORKFLOW-001', 'Family care receiver workflow', 'Family lifecycle and Care workspace orientation design input.', 'Family Care workspace and care lifecycle'),
                $source('SRC-CODE-DASHBOARD-001', 'Current Family Care workspace implementation', 'Current Overview, Actions, Schedule, Arrangements, and History navigation with account isolation.', 'Family Care routes and views'),
            ],
        ),
        $entry(
            'KB-FAM-002',
            'product_fact',
            'Your Care overview and care journeys',
            "The Care overview shows current care and what needs attention. Open a care journey to follow a request from caregiver selection through the visit, submitted hours, and payment. Draft means a request has not been posted. Open means caregivers can respond. Visit scheduled means a caregiver was selected; the journey shows the visit's fresher status. Withdrawn or Expired requests no longer accept new caregiver responses. I can take you to the Care overview.",
            'Family Care overview',
            ['family'],
            'family.care_requests',
            [
                'The Family Care workspace includes Overview, Actions, Schedule, Arrangements, and History for the authorized Family Account.',
                'Available request filters are Open, Visit scheduled, Draft, Withdrawn, and Expired.',
                'Draft is not posted; Open is eligible for caregiver responses but guarantees none.',
                'Visit scheduled means a caregiver was selected, while the booking may show a newer visit state.',
                'Withdrawn and Expired requests no longer accept new caregiver responses.',
            ],
            [
                'That a particular request exists or has a status without fresh Family Account-scoped context.',
                'That Open guarantees a reply, hire, booking, or service outcome.',
                'That Visit scheduled proves the visit is still upcoming.',
                'Applicant count, caregiver identity, visit state, payment state, or next action not proven by authoritative context.',
            ],
            [
                'navigate:family.care_requests',
            ],
            [
                'Family Account authorization or request state cannot be resolved.',
                'The user asks for a person.',
                'The user asks for personalized request, applicant, visit, or payment information without authoritative context.',
            ],
            [
                'What do the care request statuses mean?',
                'Where can I find my existing requests?',
                'Take me to my Care overview.',
            ],
            [
                'Show me the Caregiver Work Inbox.',
                'Publish a new request for me.',
                'Has someone applied to my request?',
            ],
            [
                'EVAL-KB-FAM-002-POS',
                'EVAL-KB-FAM-002-BOUNDARY',
                'EVAL-KB-FAM-002-WRONG-ROLE',
                'EVAL-KB-FAM-002-UNSUPPORTED-STATE',
                'EVAL-KB-FAM-002-HANDOFF',
            ],
            $review180,
            [
                $source('SRC-AI-DECISIONS-001', 'Intelligent Support decision log', 'Family-only care-request status and navigation boundaries.', 'DEC-032, DEC-039'),
                $source('SRC-FAMILY-WORKFLOW-001', 'Family care receiver workflow', 'Family request and visit lifecycle design input.', 'Care request lifecycle'),
                $source('SRC-CODE-CARE-REQUESTS-001', 'Current Care Request and Family Care implementation', 'Current request labels, booking-aware status, account isolation, and registered target.', 'CareRequest, RequestsIndex, policy, and lifecycle service'),
            ],
        ),
        $entry(
            'KB-FAM-003',
            'navigation',
            'Start a new care request',
            'I can take you to the New care request page. You will choose who needs care, the kind of help, when care should happen, and the care address. You can review the details and estimated cost before selecting Publish request. Opening the page does not post anything to caregivers.',
            'Family care requests',
            ['family'],
            'family.new_care_request',
            [
                'The normal Family form covers Person, Help, Time, and Address.',
                'The schedule can describe one visit or a regular weekly schedule.',
                'The page provides a final review before the Family user publishes.',
                'A usable estimate depends on required schedule information.',
                'A request becomes Open only after the Family user submits Publish request and validation succeeds.',
            ],
            [
                'That opening the page creates or posts a request.',
                'A price, estimate, caregiver availability, response, hire, booking, or care outcome not proven by current context.',
                'That saved details or a previous request exists without fresh Family Account-scoped context.',
                'That the assistant may select details, enter or alter values, submit, or publish under this entry.',
            ],
            [
                'navigate:family.new_care_request',
            ],
            [
                'Family authorization cannot be resolved.',
                'The user asks the assistant to fill or publish the request.',
                'The user asks for a person while starting a request.',
            ],
            [
                'I need to start a new care request.',
                'Take me to the form to ask for care.',
                'Where do I tell LoLo what help we need?',
            ],
            [
                'Create and publish the request for me.',
                'Accept this caregiver for me.',
                'Where are my existing requests?',
            ],
            [
                'EVAL-KB-FAM-003-POS',
                'EVAL-KB-FAM-003-NO-PUBLISH',
                'EVAL-KB-FAM-003-WRONG-ROLE',
                'EVAL-KB-FAM-003-UNSUPPORTED-STATE',
                'EVAL-KB-FAM-003-HANDOFF',
            ],
            $review180,
            [
                $source('SRC-AI-DECISIONS-001', 'Intelligent Support decision log', 'Family-only form navigation and no-publish boundary.', 'DEC-032, DEC-040'),
                $source('SRC-FAMILY-WORKFLOW-001', 'Family care receiver workflow', 'Normal Family request creation lifecycle design input.', 'New care request flow'),
                $source('SRC-CODE-NEW-CARE-REQUEST-001', 'Current new care request implementation', 'Family-only route, four essentials, review/estimate presentation, and explicit publish boundary.', 'CreateCareRequestWizard and view'),
            ],
        ),
        $entry(
            'KB-FAM-004',
            'product_fact',
            'Family access and permissions',
            "Family access lets trusted people help manage care using their own LoLo login. The Account owner manages invitations, access removal, ownership, and account closure. Active Family members can help with day-to-day care, including scheduling care, approving care-related charges, and using the current secure shared payment-method flow. They cannot manage invitations, remove someone else's access, transfer ownership, or close the Family Account. I can take you to Family access.",
            'Family access',
            ['family'],
            'family.access',
            [
                'The only user-facing roles are Account owner and Family member.',
                'Each person uses their own login and actions remain attributed to the signed-in person.',
                'Active members share authorized Family care information and may perform day-to-day care actions, including disclosed charge-related actions.',
                'Only the Account owner manages invitations, access removal, ownership, and Family Account closure.',
                'The current secure shared payment-method flow is available to active Family Account members.',
                'A non-owner member can leave, and private invitations expire after seven days.',
            ],
            [
                'That the current user or a named person has a role or active access without fresh account-scoped membership context.',
                'Any name, email, invitation state, payment method, billing history, care record, or action not proven by authoritative context.',
                'That a Family member can invite or remove people, transfer ownership, or close the account.',
                'That the assistant itself may perform an invitation, access, ownership, leaving, closure, or payment-credential mutation.',
            ],
            [
                'navigate:family.access',
            ],
            [
                'Membership or owner status cannot be resolved safely.',
                'The user requests an ownership transfer or asks for a person.',
                'The user asks the assistant to perform an unsupported invitation, removal, ownership, leaving, closure, or payment mutation.',
            ],
            [
                'How can my daughter help manage care?',
                'What can a Family member do?',
                'Take me to Family access.',
            ],
            [
                'Invite this email address for me.',
                'Remove that person from the account.',
                'Show me the members of another Family Account.',
            ],
            [
                'EVAL-KB-FAM-004-POS',
                'EVAL-KB-FAM-004-OWNER-BOUNDARY',
                'EVAL-KB-FAM-004-NO-MUTATION',
                'EVAL-KB-FAM-004-WRONG-ROLE',
                'EVAL-KB-FAM-004-HANDOFF',
            ],
            $review90,
            [
                $source('SRC-AI-DECISIONS-001', 'Intelligent Support decision log', 'Family access explanation, financial disclosure, privacy, and no-mutation boundary.', 'DEC-041, DEC-074, DEC-075'),
                $source('SRC-FAMILY-ACCESS-001', 'Family account access specification', 'Owner/member capabilities, financial disclosure, invitation/removal/leave behavior, and security requirements.', 'Access model and managing access'),
                $source('SRC-CODE-FAMILY-ACCESS-001', 'Current Family access implementation', 'Current role labels, owner/member controls, seven-day invitations, account-scoped access, and target.', 'FamilyAccess, membership services, billing flow, and view'),
                $source('SRC-CODE-AI-GUIDE-001', 'Current app-aware guided assistance implementation', 'Active Family members receive only safe shared-card facts and the registered secure payment-method destination.', 'Guided payment-method implementation and tests'),
            ],
        ),
        $entry(
            'KB-FAM-005',
            'navigation',
            'Your Account Settings',
            'Your Account Settings page lets you update your own name, email address, and password. Family users can also open Care profiles and Family access from this page. I can take you to Account Settings.',
            'Account settings',
            ['family'],
            'account.profile',
            [
                'Account Settings contains separate profile-information and password sections.',
                'The profile form covers the signed-in user own name and email address.',
                'Changing the email address makes it unverified until normal verification succeeds.',
                'The secure password form requires the current password, new password, and confirmation.',
                'Family users can reach Care profiles and Family access from Account Settings.',
            ],
            [
                'The user current account fields, verification state, password state, Care profiles, membership, or role without fresh context.',
                'Any password, verification code, session token, invitation token, or other credential.',
                'That an account or related change saved unless an authoritative result proves it.',
                'That the assistant may enter fields, submit forms, resend verification, manage Care profiles/access, or delete/close an account.',
            ],
            [
                'navigate:account.profile',
            ],
            [
                'The user asks for a person or account authorization is uncertain.',
                'The user pastes a password, code, or token.',
                'The requested task requires an account, credential, Care profile, or access mutation.',
            ],
            [
                'Where do I change my email?',
                'Take me to Account Settings.',
                'How do I change my password securely?',
            ],
            [
                'Change my password to this value.',
                'Update the care recipient profile for me.',
                'Where is the Caregiver setup page?',
            ],
            [
                'EVAL-KB-FAM-005-POS',
                'EVAL-KB-FAM-005-CREDENTIAL',
                'EVAL-KB-FAM-005-NO-MUTATION',
                'EVAL-KB-FAM-005-WRONG-ROLE',
                'EVAL-KB-FAM-005-HANDOFF',
            ],
            $review180,
            [
                $source('SRC-AI-DECISIONS-001', 'Intelligent Support decision log', 'Family account-settings navigation and no-write boundary.', 'DEC-032, DEC-042'),
                $source('SRC-CODE-ACCOUNT-SETTINGS-001', 'Current Account Settings implementation', 'Authenticated route, name/email/password forms, email verification behavior, Family links, and registered target.', 'Profile view and Volt forms'),
                $source('SRC-FAMILY-ACCESS-001', 'Family account access specification', 'Family access is a separate governed product area linked from settings.', 'Family access entry point'),
                $source('SRC-RECIPIENT-001', 'Care recipient profile specification', 'Care profiles are a separate governed product area linked from settings.', 'Care profile management'),
            ],
        ),
        $entry(
            'KB-CGV-001',
            'product_fact',
            'Your Caregiver dashboard',
            'Your Caregiver dashboard brings together your most important next step, setup or profile status, Work Inbox, and visits. What appears depends on your current authorized profile and work activity. I can take you to your Caregiver dashboard.',
            'Caregiver dashboard and setup',
            ['caregiver'],
            'caregiver.dashboard',
            [
                'The signed-in Caregiver home experience is conditional and may redirect an onboarding-mode user to setup.',
                'The dashboard can prioritize an active/next visit, Work Inbox response, or incomplete setup.',
                'Setup orientation can include profile basics, identity verification, task comfort, payouts, insurance, and intro video.',
                'Authorized response counts, applications, visits, messages, and profile state may appear when current context provides them.',
            ],
            [
                'That a setup item, verification, application, message, invitation, visit, earning, or next action exists without fresh Caregiver context.',
                'That setup completion guarantees approval, search visibility, work, booking, earnings, or payout.',
                'An identity, background-check, credential, insurance, marketplace eligibility, suspension, or approval decision.',
                'Any Family dashboard/account data or any onboarding, verification, work, visit, message, payout, or profile mutation.',
            ],
            [
                'navigate:caregiver.dashboard',
            ],
            [
                'The user asks for a person.',
                'Caregiver authorization, setup, profile, or verification state cannot be resolved.',
                'The question asks the assistant to decide eligibility or perform a setup/work action.',
            ],
            [
                'Where do I see what I need to do next?',
                'Take me to my Caregiver dashboard.',
                'Where can I see setup and work updates?',
            ],
            [
                'Take me to the Family dashboard.',
                'Approve my identity verification.',
                'Do I have a new visit?',
            ],
            [
                'EVAL-KB-CGV-001-POS',
                'EVAL-KB-CGV-001-BOUNDARY',
                'EVAL-KB-CGV-001-VERIFICATION',
                'EVAL-KB-CGV-001-WRONG-ROLE',
                'EVAL-KB-CGV-001-HANDOFF',
            ],
            $review180,
            [
                $source('SRC-AI-DECISIONS-001', 'Intelligent Support decision log', 'Caregiver-only dashboard, onboarding, verification, and no-mutation boundaries.', 'DEC-033, DEC-043'),
                $source('SRC-CODE-DASHBOARD-001', 'Current role-aware dashboard implementation', 'Current Caregiver dashboard, onboarding redirect, setup cards, scoped activity, and registered target.', 'Dashboard Home caregiver mode and view'),
            ],
        ),
        $entry(
            'KB-CGV-002',
            'product_fact',
            'Your Work Inbox',
            'Your Work Inbox organizes caregiver opportunities and progress in one place. It can show items that need a response, new requests, applications, hired work, and completed work. Open an item to review its current details before deciding what to do. I can take you to Work Inbox.',
            'Caregiver work',
            ['caregiver'],
            'caregiver.work_inbox',
            [
                'Work Inbox views are All, Needs response, New requests, Applied, Hired, and Completed.',
                'Sort choices are Priority, Newest, Start soon, and Best fit.',
                'An item may represent an invitation, request, application, hired work, visit state, or regular-care opportunity.',
                'Labels, fit, schedule/location, and compensation are contextual rather than generic promises.',
                'Opening Work Inbox is not accepting, declining, or applying for work.',
            ],
            [
                'That an item, count, invitation, request, application, hire, visit, message, or family response exists without fresh Caregiver context.',
                'That a recommendation guarantees fit, eligibility, selection, scheduling, work, compensation, or payment.',
                'A deadline, amount, rate, applicant count, recipient/address/family detail, or action not proven by authoritative item context.',
                'That the assistant may accept/decline, apply, change an application, message, accept regular care, or operate a visit.',
            ],
            [
                'navigate:caregiver.work_inbox',
            ],
            [
                'The user asks for a person or item authorization cannot be resolved.',
                'The user requests a work, invitation, application, message, or visit mutation.',
                'The question requires personalized work data not present in authoritative context.',
            ],
            [
                'Where can I find new work?',
                'Take me to my Work Inbox.',
                'Where do I see applications and hired work?',
            ],
            [
                'Accept this invitation for me.',
                'How much will I earn on the request?',
                'Show me the Family Care page.',
            ],
            [
                'EVAL-KB-CGV-002-POS',
                'EVAL-KB-CGV-002-BOUNDARY',
                'EVAL-KB-CGV-002-NO-MUTATION',
                'EVAL-KB-CGV-002-WRONG-ROLE',
                'EVAL-KB-CGV-002-HANDOFF',
            ],
            $review180,
            [
                $source('SRC-AI-DECISIONS-001', 'Intelligent Support decision log', 'Caregiver-only Work Inbox orientation and no-response/action boundary.', 'DEC-033, DEC-044'),
                $source('SRC-CODE-CAREGIVER-WORK-INBOX-001', 'Current Caregiver Work Inbox implementation', 'Current filters, sorts, item types, labels, Caregiver isolation, response boundary, and registered target.', 'WorkInbox, builder, response service, and view'),
            ],
        ),
        $entry(
            'KB-CGV-003',
            'product_fact',
            'Your visits',
            'Your My visits page puts one-time, regular, and Continuous Coverage visits in one timeline. You can filter Scheduled, In progress, Paused, Completed, Reviewed, Issues, and Time to update. Open a visit to see its current details and available controls. I can take you to My visits.',
            'Caregiver visits',
            ['caregiver'],
            'caregiver.shifts',
            [
                'The timeline combines one-time, regular, and Continuous Coverage visits ordered by date.',
                'Filters are All, Scheduled, In progress, Paused, Completed, Reviewed, Issues, and Time to update.',
                'Authorized Active, Scheduled, Completed, Needs action counts, and the next visit may appear.',
                'Visit controls depend on authoritative type, state, timing, agreements, and server conditions.',
                'Opening My visits does not change a visit.',
            ],
            [
                'That a visit exists or has a type, status, schedule, address, family/recipient identity, issue, time state, or control without fresh context.',
                'That Scheduled means a visit can already be started.',
                'Expected/final earnings, payment setup, payout eligibility, family confirmation, dispute outcome, or required action not proven by current context.',
                'That the assistant may start, pause, resume, end, cancel, reschedule, edit time, respond to a correction, or resolve an issue.',
            ],
            [
                'navigate:caregiver.shifts',
            ],
            [
                'The user asks for a person about a visit.',
                'Visit authorization, state, timing, issue, or action availability is unresolved.',
                'The user requests a visit, time, issue, payment, or payout mutation.',
            ],
            [
                'Where are my upcoming visits?',
                'Take me to My visits.',
                'Where can I see completed shifts?',
            ],
            [
                'Start this visit for me.',
                'What is the address for my next visit?',
                'Open the Family visit page.',
            ],
            [
                'EVAL-KB-CGV-003-POS',
                'EVAL-KB-CGV-003-BOUNDARY',
                'EVAL-KB-CGV-003-NO-MUTATION',
                'EVAL-KB-CGV-003-WRONG-ROLE',
                'EVAL-KB-CGV-003-HANDOFF',
            ],
            $review180,
            [
                $source('SRC-AI-DECISIONS-001', 'Intelligent Support decision log', 'Caregiver-only visit orientation, generic navigation, and no-visit-action boundary.', 'DEC-033, DEC-045'),
                $source('SRC-CODE-CAREGIVER-VISITS-001', 'Current Caregiver My visits implementation', 'Current timeline types, status filters, Caregiver isolation, state-dependent controls, and target.', 'ShiftsIndex, timeline service, booking states, and view'),
            ],
        ),
        $entry(
            'KB-CGV-004',
            'navigation',
            'Your Account Settings',
            'Your Account Settings page is for your own name, email address, and password. Your professional Caregiver profile, services, availability, verification, and payouts are managed in separate Caregiver setup pages. I can take you to Account Settings.',
            'Account settings',
            ['caregiver'],
            'account.profile',
            [
                'Account Settings contains separate profile-information and password sections.',
                'The profile form covers the signed-in Caregiver own account name and email address.',
                'Changing the email address makes it unverified until normal verification succeeds.',
                'The secure password form requires the current password, new password, and confirmation.',
                'Account Settings is distinct from professional Caregiver setup for services, availability, verification, insurance, video, and payouts.',
            ],
            [
                'Current account fields, professional-profile data/status, services, availability, identity/background status, insurance, payout state, or credentials without fresh context.',
                'Any password, verification code, session/identity token, payout credential, or other secret.',
                'That an account/profile change, verification, or payout setup succeeded without an authoritative result.',
                'That Account Settings edits the professional profile or authorizes field entry, verification, service/availability, payout, upload, or deletion actions.',
            ],
            [
                'navigate:account.profile',
            ],
            [
                'The user asks for a person or account/setup authorization is uncertain.',
                'The user pastes a password, code, token, or payout credential.',
                'The request concerns professional profile, verification, availability, service, payout, file, or account-deletion mutation.',
            ],
            [
                'Where do I change my account email?',
                'Take me to Account Settings.',
                'What is the difference between Account Settings and my Caregiver profile?',
            ],
            [
                'Change my payout account for me.',
                'Approve my verification.',
                'Where is Family access?',
            ],
            [
                'EVAL-KB-CGV-004-POS',
                'EVAL-KB-CGV-004-CREDENTIAL',
                'EVAL-KB-CGV-004-PROFILE-BOUNDARY',
                'EVAL-KB-CGV-004-WRONG-ROLE',
                'EVAL-KB-CGV-004-HANDOFF',
            ],
            $review180,
            [
                $source('SRC-AI-DECISIONS-001', 'Intelligent Support decision log', 'Caregiver account-settings navigation, profile distinction, credential safety, and no-write boundary.', 'DEC-033, DEC-046'),
                $source('SRC-CODE-ACCOUNT-SETTINGS-001', 'Current Account Settings implementation', 'Authenticated route, name/email/password forms, email verification behavior, Caregiver presentation, and target.', 'Profile view and Volt forms'),
                $source('SRC-CODE-DASHBOARD-001', 'Current Caregiver dashboard and setup implementation', 'Professional Caregiver setup is separate from Account Settings.', 'Caregiver setup cards and routes'),
            ],
        ),
    ],
];
