<?php

namespace App\Support;

final class MarketplaceNotificationPresentation
{
    public const BRAND_NAME = 'LoLo Care';

    public const LOGO_PATH = 'images/marketing/lolo/lolo-lockup-warm-1024.png';

    /** @return list<string> */
    public static function eventsForRole(string $role): array
    {
        return match ($role) {
            'family' => [
                MarketplaceEvent::FAMILY_WELCOME,
                MarketplaceEvent::INVITATION_SENT,
                MarketplaceEvent::NEW_APPLICANT,
                MarketplaceEvent::INVITE_ACCEPTED,
                MarketplaceEvent::INVITE_DECLINED,
                MarketplaceEvent::HIRE_CONFIRMED,
                MarketplaceEvent::SHIFT_CANCELLED,
                MarketplaceEvent::SHIFT_STARTING_SOON,
                MarketplaceEvent::SHIFT_REMINDER_24H,
                MarketplaceEvent::SHIFT_STARTED,
                MarketplaceEvent::SHIFT_COMPLETED,
                MarketplaceEvent::TIMESHEET_AUTO_APPROVED,
                MarketplaceEvent::REVIEW_RECEIVED,
                MarketplaceEvent::MESSAGE_RECEIVED,
                MarketplaceEvent::BOOKING_CHANGE_REQUESTED,
                MarketplaceEvent::BOOKING_CHANGE_ACCEPTED,
                MarketplaceEvent::BOOKING_CHANGE_DECLINED,
                MarketplaceEvent::PAYMENT_AUTHORIZED,
                MarketplaceEvent::PAYMENT_ACTION_REQUIRED,
                MarketplaceEvent::PAYMENT_AUTHORIZATION_FAILED,
                MarketplaceEvent::PAYMENT_CAPTURED,
                MarketplaceEvent::PAYMENT_REFUNDED,
                MarketplaceEvent::REGULAR_CARE_ACCEPTED,
                MarketplaceEvent::REGULAR_CARE_COUNTERED,
                MarketplaceEvent::REGULAR_CARE_DECLINED,
                MarketplaceEvent::REGULAR_CARE_PAYMENT_ATTENTION,
                MarketplaceEvent::REGULAR_CARE_SCHEDULE_CHANGE_ACCEPTED,
                MarketplaceEvent::REGULAR_CARE_SCHEDULE_CHANGE_DECLINED,
                MarketplaceEvent::REGULAR_CARE_PAUSED,
                MarketplaceEvent::REGULAR_CARE_RESUMED,
                MarketplaceEvent::REGULAR_CARE_ENDED,
                MarketplaceEvent::TIME_CORRECTION_REQUESTED,
                MarketplaceEvent::TIME_CORRECTION_CHANGES_REQUESTED,
                MarketplaceEvent::TIME_CORRECTION_RESUBMITTED,
                MarketplaceEvent::TIME_CORRECTION_APPROVED,
                MarketplaceEvent::TIME_CORRECTION_PAYMENT_ACTION_REQUIRED,
                MarketplaceEvent::TIME_CORRECTION_APPLIED,
                MarketplaceEvent::TIME_CORRECTION_ESCALATED,
                MarketplaceEvent::TIME_CORRECTION_WITHDRAWN,
                MarketplaceEvent::COMPLETED_EXTRA_VISIT_SUBMITTED,
                MarketplaceEvent::COMPLETED_EXTRA_VISIT_RESUBMITTED,
                MarketplaceEvent::COMPLETED_EXTRA_VISIT_WITHDRAWN,
                MarketplaceEvent::COMPLETED_EXTRA_VISIT_APPLIED,
                MarketplaceEvent::COMPLETED_EXTRA_VISIT_PAYMENT_ACTION_REQUIRED,
                MarketplaceEvent::COMPLETED_EXTRA_VISIT_ESCALATED,
                MarketplaceEvent::SUPPORT_TICKET_REPLY,
                MarketplaceEvent::CONTINUOUS_COVERAGE_APPLICATION_RECEIVED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_TEAM_ACCEPTED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_LANE_ACCEPTED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_LANE_DECLINED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_SCHEDULE_CHANGED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_SHIFT_CONFIRMED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_SHIFT_RELEASED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_REPLACEMENT_ACCEPTED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_REPLACEMENT_CONFIRMED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_GAP_UNRESOLVED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_SHIFT_COMPLETED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_PAYMENT_ATTENTION,
            ],
            'caregiver' => [
                MarketplaceEvent::CAREGIVER_WELCOME,
                MarketplaceEvent::CAREGIVER_ONBOARDING_REMINDER_24H,
                MarketplaceEvent::INVITATION_RECEIVED,
                MarketplaceEvent::MATCHING_REQUEST_REMINDER,
                MarketplaceEvent::APPLICATION_SUBMITTED,
                MarketplaceEvent::CARE_REQUEST_WITHDRAWN,
                MarketplaceEvent::CAREGIVER_HIRED,
                MarketplaceEvent::SHIFT_CANCELLED,
                MarketplaceEvent::SHIFT_STARTING_SOON,
                MarketplaceEvent::SHIFT_REMINDER_24H,
                MarketplaceEvent::SHIFT_STARTED,
                MarketplaceEvent::SHIFT_COMPLETED,
                MarketplaceEvent::TIMESHEET_AUTO_APPROVED,
                MarketplaceEvent::REVIEW_RECEIVED,
                MarketplaceEvent::MESSAGE_RECEIVED,
                MarketplaceEvent::BOOKING_CHANGE_REQUESTED,
                MarketplaceEvent::BOOKING_CHANGE_ACCEPTED,
                MarketplaceEvent::BOOKING_CHANGE_DECLINED,
                MarketplaceEvent::PAYOUT_TRANSFERRED,
                MarketplaceEvent::PAYOUT_TRANSFER_FAILED,
                MarketplaceEvent::PAYMENT_REFUNDED,
                MarketplaceEvent::REGULAR_CARE_OFFERED,
                MarketplaceEvent::REGULAR_CARE_ACCEPTED,
                MarketplaceEvent::REGULAR_CARE_ENDED,
                MarketplaceEvent::REGULAR_CARE_SCHEDULE_CHANGE_REQUESTED,
                MarketplaceEvent::REGULAR_CARE_EXTRA_VISIT_REQUESTED,
                MarketplaceEvent::REGULAR_CARE_VISIT_SKIPPED,
                MarketplaceEvent::REGULAR_CARE_PAUSED,
                MarketplaceEvent::REGULAR_CARE_RESUMED,
                MarketplaceEvent::TIME_CORRECTION_REQUESTED,
                MarketplaceEvent::TIME_CORRECTION_CHANGES_REQUESTED,
                MarketplaceEvent::TIME_CORRECTION_RESUBMITTED,
                MarketplaceEvent::TIME_CORRECTION_APPROVED,
                MarketplaceEvent::TIME_CORRECTION_PAYMENT_ACTION_REQUIRED,
                MarketplaceEvent::TIME_CORRECTION_APPLIED,
                MarketplaceEvent::TIME_CORRECTION_ESCALATED,
                MarketplaceEvent::TIME_CORRECTION_WITHDRAWN,
                MarketplaceEvent::COMPLETED_EXTRA_VISIT_CHANGES_REQUESTED,
                MarketplaceEvent::COMPLETED_EXTRA_VISIT_APPROVED,
                MarketplaceEvent::COMPLETED_EXTRA_VISIT_DISPUTED,
                MarketplaceEvent::COMPLETED_EXTRA_VISIT_APPLIED,
                MarketplaceEvent::COMPLETED_EXTRA_VISIT_ESCALATED,
                MarketplaceEvent::SUPPORT_TICKET_REPLY,
                MarketplaceEvent::CONTINUOUS_COVERAGE_TEAM_INVITATION,
                MarketplaceEvent::CONTINUOUS_COVERAGE_CAREGIVER_APPROVED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_LANE_OFFERED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_SCHEDULE_CHANGED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_SHIFT_CONFIRMED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_SHIFT_REMINDER,
                MarketplaceEvent::CONTINUOUS_COVERAGE_REPLACEMENT_OFFERED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_REPLACEMENT_CONFIRMED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_REPLACEMENT_NOT_SELECTED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_SHIFT_COMPLETED,
                MarketplaceEvent::CONTINUOUS_COVERAGE_EARNINGS_FINALIZED,
            ],
            'admin' => [
                MarketplaceEvent::SUPPORT_TICKET_CREATED,
                MarketplaceEvent::SUPPORT_TICKET_REPLY,
                MarketplaceEvent::CONTINUOUS_COVERAGE_GAP_UNRESOLVED,
            ],
            default => [],
        };
    }

    public static function label(string $eventKey): string
    {
        return match ($eventKey) {
            MarketplaceEvent::INVITATION_SENT => 'Invitation sent',
            MarketplaceEvent::INVITATION_RECEIVED => 'Care invitation',
            MarketplaceEvent::NEW_APPLICANT => 'New caregiver application',
            MarketplaceEvent::APPLICATION_SUBMITTED => 'Application submitted',
            MarketplaceEvent::CARE_REQUEST_WITHDRAWN => 'Request withdrawn',
            MarketplaceEvent::INVITE_ACCEPTED => 'Invitation accepted',
            MarketplaceEvent::INVITE_DECLINED => 'Invitation declined',
            MarketplaceEvent::MESSAGE_RECEIVED => 'New message',
            MarketplaceEvent::BOOKING_CHANGE_REQUESTED => 'Visit change requested',
            MarketplaceEvent::BOOKING_CHANGE_ACCEPTED => 'Visit change accepted',
            MarketplaceEvent::BOOKING_CHANGE_DECLINED => 'Visit change declined',
            MarketplaceEvent::CAREGIVER_HIRED => 'You were selected',
            MarketplaceEvent::HIRE_CONFIRMED => 'Caregiver selected',
            MarketplaceEvent::SHIFT_CANCELLED => 'Visit cancelled',
            MarketplaceEvent::SHIFT_REMINDER_24H => 'Visit tomorrow',
            MarketplaceEvent::SHIFT_STARTING_SOON => 'Visit starting soon',
            MarketplaceEvent::SHIFT_STARTED => 'Visit started',
            MarketplaceEvent::SHIFT_COMPLETED => 'Visit completed',
            MarketplaceEvent::TIMESHEET_AUTO_APPROVED => 'Visit hours approved',
            MarketplaceEvent::TIME_CORRECTION_REQUESTED => 'Visit time correction',
            MarketplaceEvent::TIME_CORRECTION_CHANGES_REQUESTED => 'Time correction needs changes',
            MarketplaceEvent::TIME_CORRECTION_RESUBMITTED => 'Updated visit time',
            MarketplaceEvent::TIME_CORRECTION_APPROVED => 'Corrected time approved',
            MarketplaceEvent::TIME_CORRECTION_PAYMENT_ACTION_REQUIRED => 'Payment confirmation needed',
            MarketplaceEvent::TIME_CORRECTION_APPLIED => 'Visit time updated',
            MarketplaceEvent::TIME_CORRECTION_ESCALATED => 'LoLo Care review',
            MarketplaceEvent::TIME_CORRECTION_WITHDRAWN => 'Time correction withdrawn',
            MarketplaceEvent::REVIEW_RECEIVED => 'New review',
            MarketplaceEvent::MATCHING_REQUEST_REMINDER => 'Care opportunity',
            MarketplaceEvent::PAYMENT_AUTHORIZED => 'Payment confirmed',
            MarketplaceEvent::PAYMENT_AUTHORIZATION_FAILED => 'Payment method needs attention',
            MarketplaceEvent::PAYMENT_ACTION_REQUIRED => 'Payment action needed',
            MarketplaceEvent::PAYMENT_CAPTURED => 'Payment completed',
            MarketplaceEvent::PAYMENT_REFUNDED => 'Payment adjusted',
            MarketplaceEvent::PAYOUT_TRANSFERRED => 'Payout sent',
            MarketplaceEvent::PAYOUT_TRANSFER_FAILED => 'Payout delayed',
            MarketplaceEvent::CAREGIVER_WELCOME => 'Welcome to LoLo Care',
            MarketplaceEvent::FAMILY_WELCOME => 'Welcome to LoLo Care',
            MarketplaceEvent::CAREGIVER_ONBOARDING_REMINDER_24H => 'Finish your caregiver profile',
            MarketplaceEvent::SUPPORT_TICKET_CREATED => 'New support request',
            MarketplaceEvent::SUPPORT_TICKET_REPLY => 'Support reply',
            MarketplaceEvent::REGULAR_CARE_OFFERED => 'Regular care offer',
            MarketplaceEvent::REGULAR_CARE_ACCEPTED => 'Regular care accepted',
            MarketplaceEvent::REGULAR_CARE_COUNTERED => 'Regular care counteroffer',
            MarketplaceEvent::REGULAR_CARE_DECLINED => 'Regular care declined',
            MarketplaceEvent::REGULAR_CARE_ENDED => 'Regular care ended',
            MarketplaceEvent::REGULAR_CARE_PAYMENT_ATTENTION => 'Regular care payment',
            MarketplaceEvent::REGULAR_CARE_SCHEDULE_CHANGE_REQUESTED => 'Schedule change requested',
            MarketplaceEvent::REGULAR_CARE_EXTRA_VISIT_REQUESTED => 'Extra visit requested',
            MarketplaceEvent::REGULAR_CARE_SCHEDULE_CHANGE_ACCEPTED => 'Schedule change accepted',
            MarketplaceEvent::REGULAR_CARE_SCHEDULE_CHANGE_DECLINED => 'Schedule change declined',
            MarketplaceEvent::REGULAR_CARE_VISIT_SKIPPED => 'Regular visit skipped',
            MarketplaceEvent::REGULAR_CARE_PAUSED => 'Regular care paused',
            MarketplaceEvent::REGULAR_CARE_RESUMED => 'Regular care resumed',
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_SUBMITTED => 'Extra visit reported',
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_CHANGES_REQUESTED => 'Extra visit needs changes',
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_RESUBMITTED => 'Updated extra visit',
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_APPROVED => 'Extra visit approved',
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_DISPUTED => 'Extra visit disputed',
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_WITHDRAWN => 'Extra visit withdrawn',
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_APPLIED => 'Extra visit recorded',
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_PAYMENT_ACTION_REQUIRED => 'Extra visit payment needed',
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_ESCALATED => 'LoLo Care review',
            MarketplaceEvent::CONTINUOUS_COVERAGE_TEAM_INVITATION => 'Continuous Coverage invitation',
            MarketplaceEvent::CONTINUOUS_COVERAGE_APPLICATION_RECEIVED => 'Coverage application received',
            MarketplaceEvent::CONTINUOUS_COVERAGE_CAREGIVER_APPROVED => 'Approved for a care team',
            MarketplaceEvent::CONTINUOUS_COVERAGE_TEAM_ACCEPTED => 'Care team invitation accepted',
            MarketplaceEvent::CONTINUOUS_COVERAGE_LANE_OFFERED => 'Recurring coverage offer',
            MarketplaceEvent::CONTINUOUS_COVERAGE_LANE_ACCEPTED => 'Recurring coverage accepted',
            MarketplaceEvent::CONTINUOUS_COVERAGE_LANE_DECLINED => 'Recurring coverage declined',
            MarketplaceEvent::CONTINUOUS_COVERAGE_SCHEDULE_CHANGED => 'Coverage schedule changed',
            MarketplaceEvent::CONTINUOUS_COVERAGE_SHIFT_CONFIRMED => 'Coverage shift confirmed',
            MarketplaceEvent::CONTINUOUS_COVERAGE_SHIFT_REMINDER => 'Coverage shift reminder',
            MarketplaceEvent::CONTINUOUS_COVERAGE_SHIFT_RELEASED => 'Coverage shift needs a replacement',
            MarketplaceEvent::CONTINUOUS_COVERAGE_REPLACEMENT_OFFERED => 'Backup coverage offer',
            MarketplaceEvent::CONTINUOUS_COVERAGE_REPLACEMENT_ACCEPTED => 'Backup caregiver accepted',
            MarketplaceEvent::CONTINUOUS_COVERAGE_REPLACEMENT_CONFIRMED => 'Replacement confirmed',
            MarketplaceEvent::CONTINUOUS_COVERAGE_REPLACEMENT_NOT_SELECTED => 'Backup offer not selected',
            MarketplaceEvent::CONTINUOUS_COVERAGE_GAP_UNRESOLVED => 'Coverage gap needs attention',
            MarketplaceEvent::CONTINUOUS_COVERAGE_SHIFT_COMPLETED => 'Coverage shift completed',
            MarketplaceEvent::CONTINUOUS_COVERAGE_PAYMENT_ATTENTION => 'Coverage payment needs attention',
            MarketplaceEvent::CONTINUOUS_COVERAGE_EARNINGS_FINALIZED => 'Coverage earnings finalized',
            default => 'LoLo Care update',
        };
    }

    public static function actionLabel(string $eventKey): string
    {
        return match ($eventKey) {
            MarketplaceEvent::INVITATION_SENT,
            MarketplaceEvent::INVITE_ACCEPTED,
            MarketplaceEvent::INVITE_DECLINED,
            MarketplaceEvent::NEW_APPLICANT => 'Open care request',
            MarketplaceEvent::INVITATION_RECEIVED,
            MarketplaceEvent::MATCHING_REQUEST_REMINDER => 'Review care details',
            MarketplaceEvent::APPLICATION_SUBMITTED,
            MarketplaceEvent::CAREGIVER_HIRED,
            MarketplaceEvent::HIRE_CONFIRMED => 'View care details',
            MarketplaceEvent::CARE_REQUEST_WITHDRAWN => 'Open work inbox',
            MarketplaceEvent::MESSAGE_RECEIVED => 'Read message',
            MarketplaceEvent::BOOKING_CHANGE_REQUESTED,
            MarketplaceEvent::BOOKING_CHANGE_ACCEPTED,
            MarketplaceEvent::BOOKING_CHANGE_DECLINED => 'Review visit change',
            MarketplaceEvent::SHIFT_REMINDER_24H,
            MarketplaceEvent::SHIFT_STARTING_SOON,
            MarketplaceEvent::SHIFT_CANCELLED,
            MarketplaceEvent::SHIFT_STARTED,
            MarketplaceEvent::SHIFT_COMPLETED,
            MarketplaceEvent::TIMESHEET_AUTO_APPROVED,
            MarketplaceEvent::REVIEW_RECEIVED => 'View visit',
            MarketplaceEvent::PAYMENT_AUTHORIZATION_FAILED,
            MarketplaceEvent::PAYMENT_ACTION_REQUIRED,
            MarketplaceEvent::REGULAR_CARE_PAYMENT_ATTENTION,
            MarketplaceEvent::TIME_CORRECTION_PAYMENT_ACTION_REQUIRED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_PAYMENT_ACTION_REQUIRED => 'Review billing',
            MarketplaceEvent::PAYMENT_AUTHORIZED,
            MarketplaceEvent::PAYMENT_CAPTURED,
            MarketplaceEvent::PAYMENT_REFUNDED => 'View payment details',
            MarketplaceEvent::PAYOUT_TRANSFERRED,
            MarketplaceEvent::PAYOUT_TRANSFER_FAILED => 'View earnings',
            MarketplaceEvent::TIME_CORRECTION_REQUESTED,
            MarketplaceEvent::TIME_CORRECTION_RESUBMITTED => 'Review corrected time',
            MarketplaceEvent::TIME_CORRECTION_CHANGES_REQUESTED => 'Update corrected time',
            MarketplaceEvent::TIME_CORRECTION_APPROVED,
            MarketplaceEvent::TIME_CORRECTION_APPLIED,
            MarketplaceEvent::TIME_CORRECTION_WITHDRAWN => 'View visit time',
            MarketplaceEvent::TIME_CORRECTION_ESCALATED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_ESCALATED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_DISPUTED => 'View LoLo Care review',
            MarketplaceEvent::CAREGIVER_WELCOME,
            MarketplaceEvent::CAREGIVER_ONBOARDING_REMINDER_24H => 'Finish caregiver setup',
            MarketplaceEvent::FAMILY_WELCOME => 'Find care',
            MarketplaceEvent::SUPPORT_TICKET_CREATED,
            MarketplaceEvent::SUPPORT_TICKET_REPLY => 'Open support request',
            MarketplaceEvent::REGULAR_CARE_OFFERED,
            MarketplaceEvent::REGULAR_CARE_SCHEDULE_CHANGE_REQUESTED,
            MarketplaceEvent::REGULAR_CARE_EXTRA_VISIT_REQUESTED => 'Review regular care',
            MarketplaceEvent::REGULAR_CARE_ACCEPTED,
            MarketplaceEvent::REGULAR_CARE_COUNTERED,
            MarketplaceEvent::REGULAR_CARE_DECLINED,
            MarketplaceEvent::REGULAR_CARE_ENDED,
            MarketplaceEvent::REGULAR_CARE_SCHEDULE_CHANGE_ACCEPTED,
            MarketplaceEvent::REGULAR_CARE_SCHEDULE_CHANGE_DECLINED,
            MarketplaceEvent::REGULAR_CARE_VISIT_SKIPPED,
            MarketplaceEvent::REGULAR_CARE_PAUSED,
            MarketplaceEvent::REGULAR_CARE_RESUMED => 'View regular care',
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_SUBMITTED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_RESUBMITTED => 'Review extra visit',
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_CHANGES_REQUESTED => 'Update visit report',
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_APPROVED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_APPLIED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_WITHDRAWN => 'View care history',
            MarketplaceEvent::CONTINUOUS_COVERAGE_TEAM_INVITATION,
            MarketplaceEvent::CONTINUOUS_COVERAGE_CAREGIVER_APPROVED,
            MarketplaceEvent::CONTINUOUS_COVERAGE_LANE_OFFERED,
            MarketplaceEvent::CONTINUOUS_COVERAGE_SCHEDULE_CHANGED,
            MarketplaceEvent::CONTINUOUS_COVERAGE_REPLACEMENT_OFFERED => 'Review coverage offer',
            MarketplaceEvent::CONTINUOUS_COVERAGE_APPLICATION_RECEIVED => 'Review coverage applicant',
            MarketplaceEvent::CONTINUOUS_COVERAGE_REPLACEMENT_NOT_SELECTED => 'Open Continuous Coverage',
            MarketplaceEvent::CONTINUOUS_COVERAGE_PAYMENT_ATTENTION => 'Review coverage billing',
            MarketplaceEvent::CONTINUOUS_COVERAGE_EARNINGS_FINALIZED => 'View coverage earnings',
            MarketplaceEvent::CONTINUOUS_COVERAGE_TEAM_ACCEPTED,
            MarketplaceEvent::CONTINUOUS_COVERAGE_LANE_ACCEPTED,
            MarketplaceEvent::CONTINUOUS_COVERAGE_LANE_DECLINED,
            MarketplaceEvent::CONTINUOUS_COVERAGE_SHIFT_CONFIRMED,
            MarketplaceEvent::CONTINUOUS_COVERAGE_SHIFT_REMINDER,
            MarketplaceEvent::CONTINUOUS_COVERAGE_SHIFT_RELEASED,
            MarketplaceEvent::CONTINUOUS_COVERAGE_REPLACEMENT_ACCEPTED,
            MarketplaceEvent::CONTINUOUS_COVERAGE_REPLACEMENT_CONFIRMED,
            MarketplaceEvent::CONTINUOUS_COVERAGE_GAP_UNRESOLVED,
            MarketplaceEvent::CONTINUOUS_COVERAGE_SHIFT_COMPLETED => 'Open Continuous Coverage',
            default => 'Open LoLo Care',
        };
    }

    public static function tone(string $eventKey): string
    {
        return match ($eventKey) {
            MarketplaceEvent::INVITATION_SENT,
            MarketplaceEvent::APPLICATION_SUBMITTED,
            MarketplaceEvent::INVITE_ACCEPTED,
            MarketplaceEvent::CAREGIVER_HIRED,
            MarketplaceEvent::HIRE_CONFIRMED,
            MarketplaceEvent::SHIFT_STARTED,
            MarketplaceEvent::TIMESHEET_AUTO_APPROVED,
            MarketplaceEvent::PAYMENT_AUTHORIZED,
            MarketplaceEvent::PAYMENT_CAPTURED,
            MarketplaceEvent::PAYOUT_TRANSFERRED,
            MarketplaceEvent::REGULAR_CARE_ACCEPTED,
            MarketplaceEvent::REGULAR_CARE_SCHEDULE_CHANGE_ACCEPTED,
            MarketplaceEvent::REGULAR_CARE_RESUMED,
            MarketplaceEvent::TIME_CORRECTION_APPROVED,
            MarketplaceEvent::TIME_CORRECTION_APPLIED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_APPROVED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_APPLIED => 'success',
            MarketplaceEvent::INVITATION_RECEIVED,
            MarketplaceEvent::NEW_APPLICANT,
            MarketplaceEvent::MATCHING_REQUEST_REMINDER,
            MarketplaceEvent::SHIFT_REMINDER_24H,
            MarketplaceEvent::SHIFT_STARTING_SOON,
            MarketplaceEvent::TIME_CORRECTION_REQUESTED,
            MarketplaceEvent::TIME_CORRECTION_RESUBMITTED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_SUBMITTED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_RESUBMITTED,
            MarketplaceEvent::FAMILY_WELCOME,
            MarketplaceEvent::CAREGIVER_WELCOME => 'info',
            MarketplaceEvent::INVITE_DECLINED,
            MarketplaceEvent::CARE_REQUEST_WITHDRAWN,
            MarketplaceEvent::SHIFT_CANCELLED,
            MarketplaceEvent::PAYMENT_AUTHORIZATION_FAILED,
            MarketplaceEvent::PAYMENT_ACTION_REQUIRED,
            MarketplaceEvent::PAYMENT_REFUNDED,
            MarketplaceEvent::PAYOUT_TRANSFER_FAILED,
            MarketplaceEvent::REGULAR_CARE_COUNTERED,
            MarketplaceEvent::REGULAR_CARE_DECLINED,
            MarketplaceEvent::REGULAR_CARE_PAYMENT_ATTENTION,
            MarketplaceEvent::REGULAR_CARE_SCHEDULE_CHANGE_DECLINED,
            MarketplaceEvent::REGULAR_CARE_VISIT_SKIPPED,
            MarketplaceEvent::REGULAR_CARE_PAUSED,
            MarketplaceEvent::REGULAR_CARE_ENDED,
            MarketplaceEvent::TIME_CORRECTION_CHANGES_REQUESTED,
            MarketplaceEvent::TIME_CORRECTION_PAYMENT_ACTION_REQUIRED,
            MarketplaceEvent::TIME_CORRECTION_ESCALATED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_CHANGES_REQUESTED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_DISPUTED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_PAYMENT_ACTION_REQUIRED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_ESCALATED => 'warning',
            default => 'neutral',
        };
    }

    /** @return list<string> */
    public static function nextSteps(string $eventKey, string $role): array
    {
        return match ($eventKey) {
            MarketplaceEvent::INVITATION_RECEIVED => [
                'Review the schedule, location, care tasks, and rate before responding.',
                'Accept only if the visit fits; the family will be notified of your response.',
            ],
            MarketplaceEvent::MATCHING_REQUEST_REMINDER => [
                'Review the request and apply only if the care needs and schedule are a good fit.',
            ],
            MarketplaceEvent::NEW_APPLICANT => [
                'Review the caregiver’s profile, proposed rate, and message before deciding what to do next.',
            ],
            MarketplaceEvent::SHIFT_REMINDER_24H,
            MarketplaceEvent::SHIFT_STARTING_SOON => $role === 'caregiver'
                ? ['Review the visit plan and travel details before leaving. Check in through LoLo Care when you arrive.']
                : ['Review the visit details and contact your caregiver in LoLo Care if anything has changed.'],
            MarketplaceEvent::SHIFT_COMPLETED => $role === 'family'
                ? ['Review the submitted visit hours. If you do nothing, eligible hours are approved automatically after 24 hours.']
                : ['The family can now review the recorded visit hours.'],
            MarketplaceEvent::PAYMENT_ACTION_REQUIRED,
            MarketplaceEvent::PAYMENT_AUTHORIZATION_FAILED,
            MarketplaceEvent::REGULAR_CARE_PAYMENT_ATTENTION,
            MarketplaceEvent::TIME_CORRECTION_PAYMENT_ACTION_REQUIRED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_PAYMENT_ACTION_REQUIRED => [
                'Open Billing & Payments, confirm your payment method, and return to the visit when finished.',
            ],
            MarketplaceEvent::PAYOUT_TRANSFER_FAILED => [
                'No family action is needed. LoLo Care will retry the transfer; check that your payout account is ready.',
            ],
            MarketplaceEvent::TIME_CORRECTION_REQUESTED,
            MarketplaceEvent::TIME_CORRECTION_RESUBMITTED => [
                'Compare the corrected start, end, break, and total time before approving or requesting changes.',
            ],
            MarketplaceEvent::TIME_CORRECTION_CHANGES_REQUESTED => [
                'Review the family’s note and submit a new corrected version.',
            ],
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_SUBMITTED,
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_RESUBMITTED => [
                'Confirm that the visit happened and review its date, hours, notes, and estimated charge before approving.',
            ],
            MarketplaceEvent::COMPLETED_EXTRA_VISIT_CHANGES_REQUESTED => [
                'Review the family’s note and submit an updated visit report.',
            ],
            MarketplaceEvent::SUPPORT_TICKET_REPLY => [
                'Open the support request to read the full reply and respond if anything is still unresolved.',
            ],
            default => [],
        };
    }
}
